### ISSUE TITLE
BLE not picking up Tile devices

### ISSUE THREAD

**Issue by ekkesa** [andrewjfreyer/monitor#10]
The script is running and publishing to my mqtt broker, but I also added the -b switch to monitor, but it doesn't seem to pick up my Tile devices, however when running hcitool lescan from the command line they do show up.

**Comment by ekkesa** [comment]
I tested on the newest version with the -b flag and the mac addresses in known_beacon_addresses, but still shows unknown. Any ideas what could be wrong?

**Comment by xenio** [comment]
Any way to make it works with Tile devices? I am trying the v. 0.2.184 Beta branch but Monitor alway return "confidence": "0" and in the console I can see:
[-] 0.2.184 22-04-2019 10:47:47 PM [CMD-NAME]	XX:XX:XX:XX:XX:XX Tile  Unknown
