### ISSUE TITLE
Monitor keeps disconnecting from mqtt

### ISSUE THREAD

**Issue by paulmona** [andrewjfreyer/monitor#106]
setup presence only to discover monitor, thanks for all the work!  

I have monitor installed on one (so far) Pi Zero W.  It seems to be having issues with mqtt pub - and while I understand that my monsqutto logs could show lots of connect disconnect because of mosquitto-pub, monitor itself is also complaining:  The no route to host is weird given everything is on the same network.  

0.1.985 08:37:16 am [ERROR]     mqtt broker went offline. attempting subscribe in 10 seconds.
 {
    "id":"00:00:00:00:00:00",
    "confidence":"100",
    "name":"SomeonePhone ",
    "manufacturer":"LG Electronics Mobile Communications",
    "type":"KNOWN_MAC",
    "retained":"false",
    "timestamp":"Sat Feb 09 2019 08:37:15 GMT-0500 (EST)",
    "version":"0.1.985"
 }
Error: No route to host
Error: No route to host

The above no route to host appears after each scan too:

0.1.985 08:44:37 am [CMD-INFO]  **** started arrival scan. [x1 max rep] ****
Error: No route to host

**Comment by andrewjfreyer** [comment]
This is a very rare error, and should nearly never happen. Can you tell me a bit about your broker?

**Comment by andrewjfreyer** [comment]
Does your mqtt broker have a static IP address?

**Comment by paulmona** [comment]
Yeah static IP, no SSL, password protected running in docker from official
package on docker hub.

**Comment by andrewjfreyer** [comment]
Can you run mosquitto_sub, subscribe to some topic, and see whether it exits with an error unexpectedly?

**Comment by paulmona** [comment]
Works fine, was on the same host where I'm getting the error message.tried
from another machine too and that worked.

**Comment by andrewjfreyer** [comment]
That's exceptional. Since this is a bash script, mosquitto_pub in monitor should perform no differently from command line. What do you have in your mqtt_preferences file?

**Comment by paulmona** [comment]
Great, hopefully you see some typo here.

# ---------------------------
#
# MOSQUITTO PREFERENCES
#
# ---------------------------

# IP ADDRESS OR HOSTNAME OF MQTT BROKER
mqtt_address=XXX.XXX.XXX.XXX

# MQTT BROKER USERNAME (OR BLANK FOR NONE)
mqtt_user=monitor

# MQTT BROKER PASSWORD (OR BLANK FOR NONE)
mqtt_password=XXXXXXXX

# MQTT PUBLISH TOPIC ROOT
mqtt_topicpath=monitor

# PUBLISHER IDENTITY
mqtt_publisher_identity='FamilyRoom'

# MQTT PORT
mqtt_port='1883'

# MQTT CERTIFICATE FILE (LEAVE BLANK IF NONE)
mqtt_certificate_path=''

#MQTT VERSION (LEAVE BLANK FOR DEFAULT; EXAMPLE: 'mqttv311')
mqtt_version=''

**Comment by andrewjfreyer** [comment]
Hmm. No typos. Try version v311

**Comment by andrewjfreyer** [comment]
Fixed! There was a bug another user found that has been corrected. Related to using the same topic path as the publisher identity. Update, and yous hould be good to go!

**Comment by paulmona** [comment]
Thanks Andrew!  I gave it a go, same issue, tried mqttv31 too, no change.

====================== DEBUG ======================
starting monitor.sh (v. 0.2.007)...
> removing web request caches
> removing public name cache
> preference: using mqtt protocol version mqttv31
> preference: minimum time between the same type of scan = 15
> preference: regex filter for flags to accept = .*
> preference: regex filter for flags to reject = NONE
> preference: regex filter for manufacturers to accept = .*
> preference: regex filter for manufacturers to reject = NONE
> preference: maximum sequential arrive scan attempts = 1
> preference: maximum sequential depart scan attempts = 2
> preference: selected HCI device = hci0
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
> xx:xx:xx:xx:xx:xx publishes to: monitor/mainfloor/xx:xx:xx:xx:xx:xx (has
not previously connected to hci0)
> xx:xx:xx:xx:xx:xx publishes to: monitor/mainfloor/xx:xx:xx:xx:xx:xx (has
not previously connected to hci0)
================== BEGIN LOGGING ==================
0.2.007 07:34:13 am [CMD-RAND]  [passed filter] data: xx:xx:xx:xx:xx:xx
pdu: ADV_IND rssi: -64 dBm flags: 0x1a man: Apple, Inc. delay: 0
0.2.007 07:34:13 am [CMD-INFO]  **** started arrival scan. [x1 max rep] ****
0.2.007 07:34:15 am [CMD-RAND]  [passed filter] data: xx:xx:xx:xx:xx:xx
pdu: ADV_SCAN_IND rssi: -43 dBm flags: none man: unknown delay: 1
Error: No route to host
0.2.007 07:34:15 am [ERROR]     mqtt broker went offline. attempting
subscribe in 10 seconds.
0.2.007 07:34:15 am [CMD-SCAN]  (No. 1) xx:xx:xx:xx:xx:xx arrival?
monitor/mainfloor/xx:xx:xx:xx:xx:xx
 {
    "id":"xx:xx:xx:xx:xx:xx",
    "confidence":"100",
    "name":"Paul ",
    "manufacturer":"LG Electronics Mobile Communications",
    "type":"KNOWN_MAC",
    "retained":"false",
    "timestamp":"Fri Feb 15 2019 07:34:20 GMT-0500 (EST)",
    "version":"0.2.007"
 }
Error: No route to host
0.2.007 07:34:26 am [ERROR]     mqtt broker went offline. attempting
subscribe in 10 seconds.
Error: No route to host
0.2.007 07:34:28 am [CMD-RAND]  [passed filter] data: xx:xx:xx:xx:xx:xx
pdu: ADV_SCAN_IND rssi: -61 dBm flags: none man: unknown delay: 13
^CExited.

**Comment by andrewjfreyer** [comment]
I think this must be a port issue, whether opened on docker or otherwise. Try this command in a shell:

```
mosquitto_sub -I "FamilyRoom" -F "%t|%p" -u "monitor" -P "BROKER_PASSWORD"  -h "IP ADDRESS OF BROKER" -p "1883" -t "monitor/scan/#" --will-topic "monitor/FamilyRoom/status" --will-payload "offline"
```

**Comment by paulmona** [comment]
What does: -F "%t|%p" do?  my mosquitto_sub doesn't have the -F switch and
a google isn't coming up with much.

**Comment by andrewjfreyer** [comment]
I have been able to duplicate this - fix coming.

**Comment by andrewjfreyer** [comment]
The issue is that the standard repo for mosquitto is not showing an update to v 1.5, which is when the formatting flag -F was added.

**Comment by andrewjfreyer** [comment]
Ok - after some extensive testing, I appear to have a solution. Please confirm and reopen the issue if it is not working on your end. 

The issue is with which version of mosquitto_pub is installed. Since this can vary widely by user, I opted for the largest backward compatiblity and removed dependency on v1.5+.

**Comment by paulmona** [comment]
Seems I'm running 1.4.10

**Comment by andrewjfreyer** [comment]
Yup. The feature `-F` was available on mosquitto_pub 1.5+. I downgraded mosquitto on a hunch to discover that it was the cause of the disconnection. 

If you update to 0.2.015 is the issue solved?

**Comment by paulmona** [comment]
No, same symptom unfortunately.

**Comment by andrewjfreyer** [comment]
I have this working fine on 1.4.10 - can you copy the output of monitor here? Also the output of mosquitto_pub?

**Comment by paulmona** [comment]
Here is output of monitor.  Do you want anything specific with
mosquitto_pub?

sudo bash monitor.sh
====================== DEBUG ======================
starting monitor.sh (v. 0.2.015)...
> removing web request caches
> removing public name cache
> preference: using mqtt protocol version mqttv31
> preference: minimum time between the same type of scan = 15
> preference: regex filter for flags to accept = .*
> preference: regex filter for flags to reject = NONE
> preference: regex filter for manufacturers to accept = .*
> preference: regex filter for manufacturers to reject = NONE
> preference: maximum sequential arrive scan attempts = 1
> preference: maximum sequential depart scan attempts = 2
> preference: selected HCI device = hci0
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
mkfifo: cannot create fifo 'packet_pipe': File exists
> xx:xx:xx:xx:xx:xx publishes to: monitor/MainFloor/xx:xx:xx:xx:xx:xx (has
not previously connected to hci0)
> xx:xx:xx:xx:xx:xx publishes to: monitor/MainFloor/xx:xx:xx:xx:xx:xx (has
not previously connected to hci0)
================== BEGIN LOGGING ==================
Error: No route to host
0.2.015 07:19:08 pm [CMD-RAND] [passed filter] data: xx:xx:xx:xx:xx:xx pdu:
ADV_SCAN_IND rssi: -58 dBm flags: none man: unknown delay: 0
0.2.015 07:19:09 pm [CMD-INFO] **** started arrival scan. [x1 max rep] ****
0.2.015 07:19:10 pm [CMD-ERRO] mqtt broker went offline. attempting
subscribe in 10 seconds...
0.2.015 07:19:10 pm [CMD-RAND] [passed filter] data: xx:xx:xx:xx:xx:xx:xx
pdu: ADV_SCAN_IND rssi: -57 dBm flags: none man: unknown delay: 2
0.2.015 07:19:15 pm [CMD-SCAN] (No. 1) xx:xx:xx:xx:xx:xx arrival?
0.2.015 07:19:16 pm [CMD-ERRO] mqtt broker went offline. attempting
subscribe in 10 seconds...
monitor/MainFloor/xx:xx:xx:xx:xx:xx
{
"id":"xx:xx:xx:xx:xx:xx",
"confidence":"0",
"name":"Paul",
"manufacturer":"LG Electronics Mobile Communications",
"type":"KNOWN_MAC",
"retained":"false",
"timestamp":"Fri Feb 15 2019 19:19:21 GMT-0500 (EST)",
"version":"0.2.015"
}
0.2.015 07:19:23 pm [CMD-ERRO] mqtt broker went offline. attempting
subscribe in 10 seconds... (x2)
0.2.015 07:19:26 pm [CMD-ERRO] mqtt broker went offline. attempting
subscribe in 10 seconds... (x3)
Error: No route to host
0.2.015 07:19:29 pm [CMD-RAND] [passed filter] data: xx:xx:xx:xx:xx:xx pdu:
SCAN_RSP rssi: -67 dBm flags: none man: unknown delay: 20
0.2.015 07:19:36 pm [CMD-RAND] [passed filter] data: xx:xx:xx:xx:xx:xx pdu:
ADV_IND rssi: -66 dBm flags: 0x1a man: Apple, Inc. delay: 24
0.2.015 07:19:36 pm [CMD-SCAN] (No. 1) xx:xx:xx:xx:xx:xx arrival?
0.2.015 07:19:40 pm [CMD-ERRO] mqtt broker went offline. attempting
subscribe in 10 seconds... (x2)
monitor/MainFloor/xx:xx:xx:xx:xx:xx
{
"id":"xx:xx:xx:xx:xx:xx",
"confidence":"0",
"name":"Kristina",
"manufacturer":"Apple Inc",
"type":"KNOWN_MAC",
"retained":"false",
"timestamp":"Fri Feb 15 2019 19:19:42 GMT-0500 (EST)",
"version":"0.2.015"
}
Error: No route to host
0.2.015 07:19:44 pm [CMD-RAND] [passed filter] data: xx:xx:xx:xx:xx:xx pdu:
SCAN_RSP rssi: -69 dBm flags: none man: unknown delay: 32
^CExited.

**Comment by paulmona** [comment]
Fixed! I'm an idiot, had a typo in mqtt preferences for IP address, 168
rather than 68. Didn't notice the 100x I looked at the file. Might be nice
to provide IP address in the banner on startup, but really this is my own
dumb fault.

**Comment by andrewjfreyer** [comment]
Phew! Good to hear. I was pulling my hair out trying to figure out what might be wrong!

**Comment by paulmona** [comment]
Yeah sorry man totally on me.
