### ISSUE TITLE
Problem with mosquitto mqtt server

### ISSUE THREAD

**Issue by Klagio** [andrewjfreyer/monitor#107]
I do have mosquitto on a different host with no username and passwword set, after various try for which is the correct configuration for no username no password, this seems to work
```

    # MQTT BROKER USERNAME (OR BLANK FOR NONE)
    mqtt_user=" "
    # MQTT BROKER PASSWORD (OR BLANK FOR NONE)
    mqtt_password=" "

```

but I receive lots of errors on my mosquitto server, eventually the mosquitto server  disconnects of all other clients trying to connect to it. If I stop the monitor script, restart mosquitto, all the mosquitto server errors are gone

**Comment by Klagio** [comment]
below the log, there are errors

```

====================== DEBUG ======================
starting monitor.sh (v. 0.1.985)...
> removing web request caches
> removing public name cache
> preference: using default mqtt protocol version
> preference: minimum time between the same type of scan = 15
> preference: regex filter for flags to accept = .*
> preference: regex filter for flags to reject = NONE
> preference: regex filter for manufacturers to accept = .*
> preference: regex filter for manufacturers to reject = NONE
> preference: maximum sequential arrive scan attempts = 1
> preference: maximum sequential depart scan attempts = 2
> preference: selected HCI device = hci0
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
> 4C:49:E3:xxxxxx publishes to: monitor/office_pi3/4C:49:E3xxxxxx (has not previously connected to hci0)
================== BEGIN LOGGING ==================
Error: The connection was lost.
0.1.985 03:27:37 PM [CMD-RAND]  [passed filter] data: 69:29:29:xxxxxx pdu: ADV_SCAN_IND rssi: -71 dBm flags: none man: unknown delay: 0
0.1.985 03:27:37 PM [CMD-INFO]  **** started arrival scan. [x1 max rep] ****
0.1.985 03:27:37 PM [CMD-RSSI]  PUBL AC:9A:22:xxxxxx RSSI: -97 dBm (stationary)
0.1.985 03:27:38 PM [CMD-RSSI]  PUBL B8:BB:AF:xxxxxx RSSI: -80 dBm (stationary)
0.1.985 03:27:38 PM [CMD-SCAN]  (No. 1) 4C:49:E3:xxxxxx arrival?
monitor/office_pi3/4C:49:E3:xxxxxx
 {
    "id":"4C:49:E3:xxxxxx",
    "confidence":"0",
    "name":"Phone",
    "manufacturer":"Xiaomi Communications Co Ltd",
    "type":"KNOWN_MAC",
    "retained":"false",
    "timestamp":"Sun Feb 10 2019 15:27:43 GMT+0000 (UTC)",
    "version":"0.1.985"
 }
Error: The connection was lost.
Error: The connection was lost.
Error: The connection was lost.
0.1.985 03:27:43 PM [CMD-INFO]  **** Completed arrival scan. ****
0.1.985 03:27:49 PM [CMD-RSSI]  PUBL 50:1E:2D:xxxxxx RSSI: -79 dBm (stationary)
0.1.985 03:27:49 PM [CMD-NAME]  4C:49:E3xxxxxx Phone  Xiaomi Communications Co Ltd
```

**Comment by andrewjfreyer** [comment]
Looks like there's a space in your configuration variables. Should just be an empty quote:

```
  # MQTT BROKER USERNAME (OR BLANK FOR NONE)
    mqtt_user=""
    # MQTT BROKER PASSWORD (OR BLANK FOR NONE)
    mqtt_password=""
```

**Comment by Klagio** [comment]
No as you say it gives error. Not sure if its your code or its the mosquitto server, nevertheless my mosquitto server works with lots of devices

This on my mosquitto log
1549872898: New connection from 192.168.1.238 on port 1883.
1549872898: Socket error on client <unknown>, disconnecting.

This on your log

Connection Refused: not authorised.
Error: The connection was refused.
Connection Refused: not authorised.
Error: The connection was refused.
Connection Refused: not authorised.
Error: The connection was refused.
0.1.985 08:15:04 AM [CMD-INFO]  **** Completed arrival scan. ****


this in configuration

mqtt_address=192.168.1.12


mqtt_user=""
mqtt_password=""

**Comment by Klagio** [comment]
Thisa my mosquitto config (works 100% with other devices)


{
  "logins": [
    {
      "username": "",
      "password": ""
    }
  ],
  "anonymous": true,
  "customize": {
    "active": false,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}

**Comment by andrewjfreyer** [comment]
Looks like mosquitto may have changed how it handles blank variables as arguments. I'm pushing a beta test fix soon, please update when it's up and let me know if this solves the issue for you.

**Comment by andrewjfreyer** [comment]
Update is pushed. Closing the issue for now per testing on my end. Please let me know if this should be reopened.
