### ISSUE TITLE
Connecting to mqtt

### ISSUE THREAD

**Issue by talk2dug** [andrewjfreyer/monitor#108]
Hi there,

This is the second solution I have tried for room presence, and this one is doing the same as the others. Due to reasons i don't want to go into right now, i am running anonymous on my mqtt server. I can not get this to connect. I receive the Connection Refused: not authorised.
Error: The connection was refused.
error. And on the broker I receive  New connection from 192.168.0.174 on port 1883.
1549864926: Socket error on client <unknown>, disconnecting.

Now I have been able to setup many different devices to this broker. I even wrote my own little script in NodeJS and can connect subscribe and post to the mqtt broker. 

I have tried all the ports, still nothing. I do not have ACL setup, and I am on the same local network. I have also tried adding a user to HASSIO, which the add-on states I can create users within home assistant to use in the broker, and that didn't work either. 

Ideas?

**Comment by talk2dug** [comment]
Bit of an update. I looked through the closed issues and found how you need to add the -V mqttv311 flag if you are using the broker that comes with HA. However that didn't help, and I am using the HASSIO add-on for mosquitto.

Getting the same results. 
Connection Refused: not authorised.
Error: The connection was refused.
and on the broker
1549866414: New connection from 192.168.0.174 on port 1883.
1549866414: Socket error on client <unknown>, disconnecting.

**Comment by andrewjfreyer** [comment]
Are you anon for sub and pub? If so, set blank username and password of `''` and update to the most recent beta.
