### ISSUE TITLE
Arrive/Depart Scans Timer

### ISSUE THREAD

**Issue by Odianosen25** [andrewjfreyer/monitor#11]
Hello @andrewjfreyer,

If one was to manually set the system to scan using either `[topic]/scan/ARRIVE` or `[topic]/scan/DEPART`, is it possible to reset the internal scan timer of the system? 

What I mean is since I have mine set to scan every 120 sec, if send a scan using my system when its 60 secs in, it resets its internal timer and scans after another 120 secs.

Thanks

**Comment by andrewjfreyer** [comment]
Interesting. I'll see if I can work that in.

**Comment by andrewjfreyer** [comment]
Unfortunately, not particularly simple to implement given the structure of the timer. Shelving this request for now.

**Comment by Odianosen25** [comment]
ok no worries boss, I did think same due to how its setup :). Thanks for considering it, much appreciated
