### ISSUE TITLE
MQTT Triggers won't work if publisher is same as topic root

### ISSUE THREAD

**Issue by jcastro** [andrewjfreyer/monitor#115]
Hello @andrewjfreyer. I think I've finally discovered what was going on. It seems there's a bug that if you setup `mqtt_topicpath` and `mqtt_publisher_identity` with same value, MQTT triggers won't work. I used to have both with `monitor` value and I was unable to trigger anything using MQTT, from ARRIVE/DEPART to UPDATE or RESTART.

Now I've changed `mqtt_publisher_identity` to `pi3` while leaving `mqtt_topicpath` set to `monitor` and I can successfully send commands through MQTT that show up in the monitor console as MQTT Instructions.

I'm using beta version 0.2.002

**Comment by andrewjfreyer** [comment]
Interesting. I'll look into this - I'm not sure why the publisher_identity would matter for MQTT triggers though, since the path is `$mqtt_topicpath/scan/arrive` or `$mqtt_topicpath/scan/depart`

I'll investigate. Thanks for the report!

**Comment by jcastro** [comment]
I have no idea but I wasn't able to make it work in 2 different Raspberry until I changed the publisher identity. Maybe it's something else, but I can reproduce this behaviour 100% of the time!.

Thanks to you, Andrew!

**Comment by andrewjfreyer** [comment]
> ... but I can reproduce this behaviour 100% of the time!

And that's why its 100% likely this is a bug on my part! haha

**Comment by andrewjfreyer** [comment]
fixed!

Poor parsing on my part.

**Comment by jcastro** [comment]
Cool! thanks Andrew!
