### ISSUE TITLE
Option -u not adding correct syntax

### ISSUE THREAD

**Issue by jcastro** [andrewjfreyer/monitor#118]
Hello Andrew,

Today I tried to use the option `-u` to change monitor service and I believe I found a small bug (or maybe I'm just doing it wrong)

If I do `sudo bash monitor -utad` to add `-tad` options to the monitor.service file it will end up adding only `tad`, so effectively it will look like `sudo bash monitor tad` and it won't work.

I had to execute `sudo monitor -u -tad` to get the monitor.service file changed correctly.

Thanks for all your hard work!
Jonatan

**Comment by andrewjfreyer** [comment]
The update flag is a separate flag, so the second method is correct. I'll add some filtering to make sure that the first method doesn't cause issues for future users!

Thanks!
