### ISSUE TITLE
new generic public beacons not reporting on arrival

### ISSUE THREAD

**Issue by j-klier** [andrewjfreyer/monitor#126]
I have several Bluetooth low energy devices like fitbits that I'm trying to track using monitor.  I was expecting to see these devices report when they first connect and again when they go out of range, but nothing was reported without the -a switch
`sudo  bash monitor.sh -b -a`

I've been debugging the issue for a while and it seems that the `is_new` flag could be used make sure that these devices report at 100% then they first advertise within rage.  This change is working well for me.
```
sudo bash monitor.sh -v
====================== DEBUG ======================
starting monitor.sh (v. 0.2.022)...

git diff
diff --git a/monitor.sh b/monitor.sh
index 36bb784..8b1b2de 100644
--- a/monitor.sh
+++ b/monitor.sh
@@ -1623,7 +1623,8 @@ while true; do
                                "movement=$change_type"
                        fi

-               elif [ "$cmd" == "PUBL" ] && [ "$PREF_BEACON_MODE" == true ] && [ "$should_update" == true ]; then
+               elif [ "$cmd" == "PUBL" ] && [ "$PREF_BEACON_MODE" == true ] && ([ "$should_update" == true ] || [ "$is_new" == true ]) ; then
+

                        #PUBLISH PRESENCE MESSAGE FOR BEACON
                        if [ -z "${blacklisted_devices[$mac]}" ]; then
```

**Comment by andrewjfreyer** [comment]
Thanks. I’ll test and incorporate soon.

**Comment by andrewjfreyer** [comment]
Incorporated. Thanks!
