### ISSUE TITLE
MQTT password in mqtt_preferences does not accept special Characters

### ISSUE THREAD

**Issue by cdk222** [andrewjfreyer/monitor#131]
Firstly great project

I am using monitor on a Pi Zero connected to an MQTT broker on another Pi. I correctly configured mqtt_preferences with my Broker credentials; however I have discovered that monitor does not like passwords with special characters such as:

& 
$

I have many other devices that connect successfully to my broker using my password which contains special characters; however when I attempt connection from Monitor it spits out:

"a password/username combination was rejected"

My Broker also registers an error with an "invalid password hash". 

When I then changed the password to a simple  word - "test" and it connects with no issue and works fine.

I would like to use special characters in my password....and also dont want to have to go and change the password in all of my other MQTT clients so could you please incorporate this fix in your code.

I tried it with both the Master and Beta versions.

Thank You

**Comment by andrewjfreyer** [comment]
I’ll investigate. thank you

**Comment by andrewjfreyer** [comment]
I'm not able to duplicate this. Are you on the most updated version of mosquitto_sub/_pub? What version of `monitor` are you running?

**Comment by cdk222** [comment]
I have tried both your latest Master and dev versions of monitor with the same results. 

With regards to mosquitto I have scoured the net for the command to get my version numbers but cant find it....could you point me in the right direction.

**Comment by cdk222** [comment]
lol - found it mosquitto v 1.4.10 (17/10/18) with a v3.1 MQTT broker

**Comment by andrewjfreyer** [comment]
Can you run a command from an ssh session to see the output? 

```bash
sudo mosquitto_sub -h "{{BROKER_HOSTNAME_OR_IP}}" -u "{{USERNAME}}" -P "{{PASSWORD}}" -t "#"
```

This should subscribe you to everything. Does it return an error?

**Comment by cdk222** [comment]
I get the following error message:
-bash: Mo6218iQ: command not found
Error: You must specify a topic to subcribe to

Then when I change my password on the broker to one with no special characters (eg: no $ & or @) then it starts pumping out all the data from the wildcard topic

**Comment by cdk222** [comment]
I also tried to update mosquitto to version 1.5 but still no luck

**Comment by andrewjfreyer** [comment]
Are you enclosing your password in quotes?

**Comment by cdk222** [comment]
Nope - should i do this (....in mqtt_password)?

it connects fine when I dont have special characters in the password (which is unquoted in mqtt_password)

**Comment by andrewjfreyer** [comment]
Yes, enclose your passwords in quotes. For clarity, if your username is `username` and your password is `password` and your host is `hostname` the command would be: 

```bash 
sudo mosquitto_sub -h "hostname" -u "username" -P "password" -t "#"


```

**Comment by cdk222** [comment]
Results were slightly different in terms of the error message but outcome the same. 

So when using special characters in password I not get the message:
    "Connection Refused: not authorised"

When I change the password to one with no special characters it connects fine and starts pulling MQTT states

**Comment by cdk222** [comment]
.......appologies for delayed response each time. Im in Australia so probably big timezone difference

**Comment by cdk222** [comment]
ok so i cracked it.

In both the mosquitto_sub command and the mqtt_preferences I needed to have hostname, username, password, and Topic all enclosed in   '   '     and not "   "

As I have mentioned it works fine without    '   '   as long as the password has no special characters.

Thank you again for you help - you last message got me trying things out until it worked
