### ISSUE TITLE
sed: -e expression #1, char 17: unknown option to `s'

### ISSUE THREAD

**Issue by pittbull** [andrewjfreyer/monitor#132]
Activating the following configuration in behavior_preferences, triggers the above error messages:

PREF_MQTT_REPORT_SCAN_MESSAGES=true

sed: -e expression #1, char 17: unknown option to `s'

I only have limited knowledge about bash, so I cannot find where it is produced.

**Comment by andrewjfreyer** [comment]
Thanks. I’ll investigate.

**Comment by andrewjfreyer** [comment]
Another user has reported this for a previous version, but I still can't reproduce on my end even with that option enabled. 

Are you on the most recent beta? If not, can you test? 

```bash
sudo git checkout beta
sudo git pull
sudo systemctl restart monitor
```

**Comment by pittbull** [comment]
Installed the beta earlier today and it is currently running at home - with the same error.

**Comment by pittbull** [comment]
This is fresh out of the logs just now:

`Mar 05 19:31:28 raspberrypi bash[466]: 0.2.017 07:31:28 pm [CMD-SCAN]        (No. 1) D4:DC:CD:B6:0F:AE arrival?
Mar 05 19:31:29 raspberrypi bash[466]: 0.2.017 07:31:29 pm [CMD-INST]        [fail mqtt] topic: data: monitor/scan/arrival/start {"identity":"main floor"}
Mar 05 19:31:36 raspberrypi bash[466]: 0.2.017 07:31:36 pm [CMD-SCAN]        (No. 1) 78:67:D7:47:D8:1A arrival?
Mar 05 19:31:45 raspberrypi bash[466]: 0.2.017 07:31:45 pm [CMD-SCAN]        (No. 1) F8:2D:7C:EF:94:38 arrival?
Mar 05 19:31:53 raspberrypi bash[466]: 0.2.017 07:31:53 pm [CMD-INFO]        **** Completed arrival scan. ****
Mar 05 19:31:53 raspberrypi bash[466]: 0.2.017 07:31:53 pm [CMD-NAME]        D4:DC:CD:B6:0F:AE user1  Apple Inc
Mar 05 19:31:53 raspberrypi bash[466]: sed: -e expression #1, char 17: unknown option to `s'
Mar 05 19:31:53 raspberrypi bash[466]: 0.2.017 07:31:53 pm [CMD-NAME]        78:67:D7:47:D8:1A user2  Apple Inc
Mar 05 19:31:53 raspberrypi bash[466]: 0.2.017 07:31:53 pm [CMD-NAME]        F8:2D:7C:EF:94:38 user3  Apple Inc
Mar 05 19:31:53 raspberrypi bash[466]: 0.2.017 07:31:53 pm [CMD-INST]        [fail mqtt] topic: data: monitor/scan/arrival/end {"identity":"main floor"}
Mar 05 19:33:33 raspberrypi bash[466]: 0.2.017 07:33:33 pm [DEL-RAND]        RAND 61:87:59:8A:49:AD expired after 189 seconds
Mar 05 19:33:33 raspberrypi bash[466]: 0.2.017 07:33:33 pm [DEL-RAND]        RAND 58:A4:A1:81:11:95 expired after 189 seconds
Mar 05 19:34:02 raspberrypi bash[466]: 0.2.017 07:34:02 pm [CMD-RAND]        [failed filter] data: 42:14:DF:F0:6C:F4 pdu: ADV_SCAN_IND rssi: -32 dBm flags: none man: unknown delay: 0
Mar 05 19:34:45 raspberrypi bash[466]: 0.2.017 07:34:45 pm [CMD-RAND]        [passed filter] data: 58:A4:A1:81:11:95 pdu: ADV_IND rssi: -73 dBm flags: 0x1a man: Apple, Inc. delay: 0
Mar 05 19:34:45 raspberrypi bash[466]: 0.2.017 07:34:45 pm [CMD-INFO]        **** started arrival scan. [x1 max rep] ****
Mar 05 19:34:45 raspberrypi bash[466]: sed: -e expression #1, char 17: unknown option to `s'
Mar 05 19:34:45 raspberrypi bash[466]: 0.2.017 07:34:45 pm [CMD-SCAN]        (No. 1) D4:DC:CD:B6:0F:AE arrival?
Mar 05 19:34:45 raspberrypi bash[466]: 0.2.017 07:34:45 pm [CMD-RAND]        [failed filter] data: 47:6F:A6:E7:02:D1 pdu: SCAN_RSP rssi: -66 dBm flags: none man: unknown delay: 1
Mar 05 19:34:45 raspberrypi bash[466]: 0.2.017 07:34:45 pm [CMD-INST]        [fail mqtt] topic: data: monitor/scan/arrival/start {"identity":"main floor"}
Mar 05 19:34:53 raspberrypi bash[466]: 0.2.017 07:34:53 pm [CMD-SCAN]        (No. 1) 78:67:D7:47:D8:1A arrival?
Mar 05 19:35:01 raspberrypi bash[466]: 0.2.017 07:35:01 pm [CMD-SCAN]        (No. 1) F8:2D:7C:EF:94:38 arrival?
Mar 05 19:35:09 raspberrypi bash[466]: 0.2.017 07:35:09 pm [CMD-INFO]        **** Completed arrival scan. ****
Mar 05 19:35:09 raspberrypi bash[466]: 0.2.017 07:35:09 pm [CMD-NAME]        D4:DC:CD:B6:0F:AE user1  Apple Inc
Mar 05 19:35:09 raspberrypi bash[466]: sed: -e expression #1, char 17: unknown option to `s'
Mar 05 19:35:09 raspberrypi bash[466]: 0.2.017 07:35:09 pm [CMD-NAME]        78:67:D7:47:D8:1A user2  Apple Inc
Mar 05 19:35:09 raspberrypi bash[466]: 0.2.017 07:35:09 pm [CMD-NAME]        F8:2D:7C:EF:94:38 user3  Apple Inc
Mar 05 19:35:09 raspberrypi bash[466]: 0.2.017 07:35:09 pm [CMD-INST]        [fail mqtt] topic: data: monitor/scan/arrival/end {"identity":"main floor"}
Mar 05 19:35:38 raspberrypi bash[466]: 0.2.017 07:35:38 pm [DEL-RAND]        RAND 7C:65:72:CB:C1:57 expired after 183 seconds
`

**Comment by andrewjfreyer** [comment]
Thanks for the log.

**Comment by pittbull** [comment]
Well, that was embarrassing - did as instructed to update the beta and it now runs on v. 0.2.046. And the error message is gone. 

Thanks for your assistance.

**Comment by andrewjfreyer** [comment]
Excellent! Thanks for the report.

**Comment by andrewjfreyer** [comment]
The beta is always leading the master on features while I test improvements. I merge the two periodically.
