### ISSUE TITLE
support/btle: line 258: printf: write error: Broken pipe

### ISSUE THREAD

**Issue by pittbull** [andrewjfreyer/monitor#134]
This error appears in my log. (Running latest beta)

`Mar 07 02:44:54 btscanner1 bash[477]: ./support/btle: line 258: printf: write error: Broken pipe`

```
Mar 07 02:44:52 btscanner1 bash[477]: 0.2.046 02:44:52 am [CMD-RAND]        [failed filter] data: 41:D5:4A:83:36:A0 pdu: ADV_NONCONN_IND rssi: 4 dBm flags: none man: Apple, Inc. delay: 0
Mar 07 02:44:54 btscanner1 bash[477]: ./support/btle: line 258: printf: write error: Broken pipe
Mar 07 02:44:55 btscanner1 bash[477]: 0.2.046 02:44:55 am [CMD-SCAN]        (No. 1) F8:2D:7C:EF:94:38 arrival?
Mar 07 02:45:03 btscanner1 bash[477]: 0.2.046 02:45:03 am [CMD-INFO]        **** Completed arrival scan. ****
```

**Comment by keithmichael** [comment]
I have same problem - if I can help in anyway please let me know.

**Comment by andrewjfreyer** [comment]
This is possibly a result of a low-noise bluetooth environment. I have pushed a new update to try and compensate. Please reopen if the error continues to report

**Comment by pittbull** [comment]
The previous one has not been seen for awhile - but a new one has come:

```
Mar 15 04:26:22 btscanner1 bash[24171]: ./support/btle: line 307: printf: write error: Broken pipe
```

**Comment by Frits1980** [comment]
I've just setup a new rpi with Monitor and get this error too. Every time after the first beacon is "discovered" so it ends there and never goes on to the second beacon. How can I solve this issue?
