### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by keithmichael** [andrewjfreyer/monitor#135]
Hi, I wasn't able to find another way to message you through Github. Thank you for all the time you spent on this project, I'm running it now on 4 Pi's and will probably add 2 more. I appreciate all the time you put into this to make it easy for the hobbyist like me.

**Comment by nephilic** [comment]
I'm going to add to this also. I completely agree. This is exactly what I was looking for my implementation and you've done an excellent job. Please let me know if you have a patreon or some other way to support.

**Comment by jcastro** [comment]
Me too, extremely grateful for this tool. I was able to finally create automations based on presence. Buy him a coffee!

**Comment by andrewjfreyer** [comment]
The support from the community is just awesome. Thanks, yall!!

**Comment by pittbull** [comment]
Adding myself to this list. This script is awesome and suits my purpose perfectly. :)

Thank you for you time and dedication.
