### ISSUE TITLE
Added support for smartthings devices

### ISSUE THREAD

**Issue by jmbinette** [andrewjfreyer/monitor#136]
Added in mqtt :

#SHOULD WE BE REPORTING AS A SMARTTHINGS PRESENCE SENSOR? 
		if [ "$PREF_SMARTTHINGS_REPORT" == true ]; then 

			if [[ $message =~ \"confidence\":\"100\" ]]; then 
				#OVERRIDE MESSAGE
				device_tracker_message="present"
			elif [[ $message =~ \"confidence\":\"0\" ]]; then 
				#OVERRIDE MESSAGE
 				device_tracker_message="not present"
 			else 
 				#NO MQTT MESSAGES IF NOT ZERO OR 100
 				device_tracker_message=""
 			fi

 			#ONLY POST A MESSAGE TO DEVICE TRACKER BOARD IF WE HAVE 
 			#A COMPLETE CONFIDENCE MESSAGE
 			if [ -n "$device_tracker_message" ]; then 
	 			#PRINT FOR DEVICE TRACKER
	 			printf "%s\n" "${PURPLE}$topic/presence $device_tracker_message${NC}"

	 			#POST TO MQTT
				($mosquitto_pub_path \
				-I "$mqtt_publisher_identity" \
				$should_retain \
				$mqtt_version_append \
				$mqtt_ca_file_append \
				-P "$mqtt_password" -u "$mqtt_user" \
				-h "$mqtt_address" \
				-p "$mqtt_port" \
				-t "$topic/presence" \
				-m "$device_tracker_message" 2>&1)
			fi
 		fi

**Comment by andrewjfreyer** [comment]
Added support for this in beta 0.2.050:

* Generic: 

```bash
PREF_DEVICE_TRACKER_HOME_STRING='home' 
PREF_DEVICE_TRACKER_AWAY_STRING='away'
```

**Comment by jmbinette** [comment]
Thanks @andrewjfreyer 
Please note that the line "-t "$topic/presence" \" was also different from your original "-t "$topic/device_tracker" \" Device Tracker code .. 

Regards

**Comment by andrewjfreyer** [comment]
Noted. I'll update

**Comment by andrewjfreyer** [comment]
Updated 0.2.051 to include PREF_DEVICE_TRACKER_TOPIC_BRANCH as well. 

Thanks!
