### ISSUE TITLE
Default trigger others 

### ISSUE THREAD

**Issue by Odianosen25** [andrewjfreyer/monitor#14]
Hello @andrewjfreyer,

Thanks for the updates again.

Please it seems the new updates, the main sensor no longer triggers the others when it’s doing its periodic scans.

iOS this by design? I think it’s a good thing pls, and if it’s not can you kindly look into it or at least make it an option.

Thanks

**Comment by Odianosen25** [comment]
> Do you mean your nodes are not receiving "[topicpath]/scan/arrive" or "[topicpath]/scan/depart" messages?

Yes basically that. They receive it when my app sends it, but I don't think they do receive and are being triggered to scan by the main one when its running its regular scans.

regards

**Comment by andrewjfreyer** [comment]
I cannot duplicate this issue. Please let me know if you can provide any logs or other documentation or tracing of this report. Closing for now.

**Comment by Odianosen25** [comment]
Ok no worries, will look into it when I get home.

Thanks for looking into it.

regards

**Comment by Odianosen25** [comment]
Hello @andrewjfreyer,

I am sorry I need to bring this up again, but this is what I think is going on.

Now I have two monitor systems, one running default and the other running only as trigger.

Now when in my room, the default one sometimes registers my home with a confidence of 0, then later brings it up again. So basically it reads the phone intermittently which is fine due to distance.

Now I have a monitor system just at the side of my room, which is able to pick up my phone easily when i am in the room. So now this is what happens I think

When the default one registers a lower confidence, it doesn't ask the other to scan until it has registers a 0 first. Now this I don't think is cool.

My reason is that, I think its better that as the default starts the scan, it should instruct the others also. Waiting for it to get to output a confidence of 0 before telling the others, makes my system to register a false negative since my system starts its own internal timer after the first confidence reading.

I could increase my timer, but that will increase my detection time. I could wait till it gets to 0, but that is still gonna increase detection time. 

But if all are triggered at once, when one is going to 0, the other still registers 100 so I will not have any false negative.

Hope it all makes sense?

Regards

**Comment by andrewjfreyer** [comment]
I understand what you're saying, but let me restate the problem to be sure that I understand what's going on. If your "triggered" monitor is registering 0 (and not scanning since it's only triggered scanning), the only device that recognizes that you are home is the "close" monitor. So, in your example, once the "close" monitor recognizes that you are away, BOTH nodes are already at zero, causing the system to think you are away. Then a scan is triggered and the "triggered" monitor may pick you back up again, although probably not for a while since the trigger will be for a departure scan. 
 
Is that right?

**Comment by Odianosen25** [comment]
Yep that is it, so at a point they both think I am away when actually I am home, until the default one (which I believe you refereed to as close), goes to 0, then the other is triggered.

If you don't want to start the scan of the triggered ones immediately the default starts, as I recognise there will be good reason not to. Since default takes about 4 scans to confirm (I also recognise this is depended on user), you can activate the other ones, once default gets a confidence below a certain level. Or if its first scan is below 100 or something.

This way before it gets to 0, the triggered ones are beginning to confirm that, actually this device is not away, but probably in a different section of the house.

**Comment by Odianosen25** [comment]
Please let me know when you done, so I can update my system. Regards
