### ISSUE TITLE
typo on Device Tracker Topic Branch 

### ISSUE THREAD

**Issue by hatemzidi** [andrewjfreyer/monitor#143]
hello, 

while testing the latest version (0.2.51), i observed that the device tracker topic is always set to "home"

```
monitor.sh-test | > xx:xx:xx:xx:xx:xx device_tracker topic: ehome/monitor/xx:xx:xx:xx:xx:xx/home [not_home or home]
```

it seems that there is a typo in this line : 
https://github.com/andrewjfreyer/monitor/blob/17ef4ce71192e007e35caa79150318dbdf33aeb3/support/setup#L276

**Comment by andrewjfreyer** [comment]
Good catch. Fixed in 0.2.052.
