### ISSUE TITLE
mqtt_topicpath multiple levels causes error

### ISSUE THREAD

**Issue by Loafdude** [andrewjfreyer/monitor#149]
To conform to my mqtt topic structure I am trying to use 
`mqtt_topicpath="Home/Presence/BT"`

If I publish to topic
`Home/Presence/BT/scan/arrive`
monitor.sh drops the error
`sed: -e expression #1, char 17: unknown option to `\`s'`

The scans are still performed but the error is repeated for any arrival or departure scan

**Comment by andrewjfreyer** [comment]
Try using single quotes in your configuration file.

**Comment by andrewjfreyer** [comment]
Fixed in 0.2.065, verified in my testing. Please comment if this is not the case.
