### ISSUE TITLE
Repeated online announcements

### ISSUE THREAD

**Issue by pittbull** [andrewjfreyer/monitor#150]
I was expecting the MQ online/offline announcements to take place when the service actually starts and stops, but from the logs they seem to be repeating much more often. I am developing a python script to react to these statuses and wonder if they could be tweaked? :)

```` 
SCRIPT STARTED
monitor/main floor/status online
monitor/main floor/status online
monitor/scan/arrival/start {"identity":"main floor"}
monitor/main floor/status online
monitor/main floor/Device1 {JSON}
monitor/main floor/Device1/rssi -99
monitor/main floor/status online
monitor/scan/depart {"identity":"main floor"}
monitor/main floor/status offline
SCRIPT STOPPED
```

**Comment by andrewjfreyer** [comment]
The online messages are repeated to overcome an issue with Home Assistant's availability topics. I'll investigate to see if it is still necessary.

**Comment by pittbull** [comment]
If this is needed for HA then I will not object.

I'll let you know if something comes to mind. :)

**Comment by andrewjfreyer** [comment]
Its the best working solution that i have found so far for HA’s poor handling of availability topics. I’m sure it will be corrected eventually. :-)
