### ISSUE TITLE
Topic question

### ISSUE THREAD

**Issue by pittbull** [andrewjfreyer/monitor#152]
This is not so much an issue but more of a discussion point.

After testing your script (which works brilliantly I must say) I initially had some issues with the final portion of the topic that is being posted to. By default this is the MAC of the device, and you can create the mqtt_alias file to configure a name for the device.

I am running Samsung Smartthings as my hub and I use [smartthings-mqtt-bridge](https://github.com/stjohnjohnson/smartthings-mqtt-bridge) to facilitate the communication. As I have no immediate plans to implement HA I am writing a Python script that will handle the logic.

When I connect my bluetooth devices to the mqtt-bridge they create topics based on their actual names, and I have done a couple of modifications to your code to align the naming conventions used:

**I have commented out this line to make sure a name is always used. (Strictly not needed)**
```
                #IF THE VALUE DOES NOT EXIST, USE THE KEY (MAC ADDRESS INSTEAD)
                #value=${value//[^A-Za-z0-9]/_}
````

**I have commented out this line so that the casing will match Smartthings**
```
                #LOWERCASE
                #value=${value,,}
```

**I have inserted a space here to eliminate a trailing space in the name**
Line 198-199 (column 83)
```
        #WAS THERE A NAME HERE?
        known_name=$(grep "$addr" "$PUB_CONFIG" | tr "\\t" " " | sed 's/  */ /g;s/ #.\{0,\}//g' | sed "s/$addr //g;s/  */ /g" )
```

Is there someway to implement these changes so that the git processes will update without user interaction?

**Comment by andrewjfreyer** [comment]
See [this](https://community.home-assistant.io/t/monitor-reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/68505/1148?u=andrewjfreyer) comment for updating via git while also retaining local changes to specific files.
