### ISSUE TITLE
MQTT_pub failing to connect to broker

### ISSUE THREAD

**Issue by Villhellm** [andrewjfreyer/monitor#155]
`mqtt broker went offline, or a password/username combination was rejected.`
` [fail mqtt] topic: Unable to connect (Lookup error.). data: Unable to connect (Lookup error.).`

This is happening on both of my pis running this script as of this morning. On both of them I can manually publish and subscribe to topics without issue. Haven't changed a thing in my preference files for months, this just started happening this morning. Was there a preference change or something?

**Comment by andrewjfreyer** [comment]
Did you upgrade to the most recent version?

**Comment by Villhellm** [comment]
1.5.8 is the current version on the pi zero, but my broker is on the latest version available for Ubuntu which is 1.4.15. I upgraded after having to dig through your commits to see what changes were recently made. Is there a reason you don't make proper commit messages or release notes?

Monitor version is 0.2.066. I haven't changed anything on my network, no.

**Comment by andrewjfreyer** [comment]
Is your connection to the broker TLS/SSL?

**Comment by Villhellm** [comment]
Nope, it's all local.

**Comment by andrewjfreyer** [comment]
are you setting the host variable via IP address or hostname?

**Comment by Villhellm** [comment]
IP address

**Comment by Villhellm** [comment]
Downgraded to 0.2.053 for now, working fine with no changes to preferences. I can upgrade again if it will help you debug. Not sure what else to try.

**Comment by andrewjfreyer** [comment]
it'd be helpful to have logs and your mqtt config, which of course you should redact personal details from before posting 

try connecting to your broker using -L option following the format

mqtt://username:password@hostname:port/topic_path -m "test message"

and see if there's an issue

**Comment by Villhellm** [comment]
It's being caused because I have an `@` character in my password.

**Comment by andrewjfreyer** [comment]
Ok, thanks for the report. Let me work on a solution.

**Comment by andrewjfreyer** [comment]
After a review, it does not appear that there's a way around using a password with an '@' in it while retaining support for all other special characters and while retaining support for users who do not want to use a password. 

I recommend creating a new user on your broker for monitor that does not use the '@' sign in its password or in the username. Apologies for the inconvenience to you, but it seems to me at this time, there's no way around this. I'll continue to research. This recent structural change for MQTT handling is necessary to broaden general password support.

**Comment by denis-domanskii** [comment]
@andrewjfreyer please add it to README or at least FAQ. I spent 2 hours to found the issue.
