### ISSUE TITLE
Bash 5 fails minimum version check

### ISSUE THREAD

**Issue by grewhit25** [andrewjfreyer/monitor#156]
@andrewjfreyer, First off thank you for this great tool. I have being aware of 'monitor' for a while but only recently started trailing it. My intention is to have 'monitor' at the front end integrated over mqtt with my esp32s at the backend in each my rooms.

### The issue

Raspberry Pi 3B
OS Raspbian Lite
Linux 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
Docker Version:  18.09.0

monitor version: (v. 0.2.065)
GNU bash, version 5.0.0(1)-release (armv7-alpine-linux-musleabihf)
mosquitto_sub version 1.5.7 running on libmosquitto 1.5.7
mosquitto_pub version 1.5.7 running on libmosquitto 1.5.7

I have been running 'monitor' on one of my old Raspberry Pis in a Docker Alpine container without any problems with mqtt login, even though I don't have username or password set.

However, due to the latest version: (v. 0.2.065) requirements for mosquitto 1.5+, I duly upgraded my docker image in the meantime also having to switch to Alpine Edge to overcome the mosquitto version limitation of 1.4+ in standard Alpine.

Rebuilding my Docker image also increased the 'Bash' version to 5.0+ which breaks your minimum version checks.

I have in the meantime just tweaked the test so that I can workaround the issue until an official fix becomes available.

Thanks again and keep up the good work.

**Comment by andrewjfreyer** [comment]
Interesting. That should have passed. I’ll investigate.

**Comment by andrewjfreyer** [comment]
Yeah, I did a stupid thing. Should be fixed now. Bash requirement is rolled back to a warning right now since I haven't yet implemented the bash 4.4+ specific features. Please report back on this thread if you continue to notice an issue.

**Comment by grewhit25** [comment]
@andrewjfreyer I can confirm the problem has been fixed. Thank you.

**Comment by andrewjfreyer** [comment]
Awesome. Thanks for the followup!
