### ISSUE TITLE
monitor not working anymore 

### ISSUE THREAD

**Issue by theHasp** [andrewjfreyer/monitor#167]
Hi @all,

I have a fresh installation and I'm using the internal bluetooth adapzter of my zero.
I do NOT have a trigger to do an arrival or departure scan (as my door is not connected)

monitor was working quite a while but stopped at some point. Thats why I updated the pi and monitor but the result got worse ...

`-- Logs begin at Tue 2019-04-09 15:15:55 CEST, end at Tue 2019-04-09 15:18:56 CEST. --
Apr 09 15:16:20 presencepi bash[416]: > 58:48:22:9A:52:FA confidence topic: eg/kueche/presencepi { id: 58:48:22:9A:52:FA ... } (has not previously connected to hci0)
Apr 09 15:16:20 presencepi bash[416]: > B4:CD:27:13:0E:AA confidence topic: eg/kueche/presencepi { id: B4:CD:27:13:0E:AA ... } (has not previously connected to hci0)
Apr 09 15:16:15 presencepi bash[416]: > starting monitor.sh (v. 0.2.148)...
Apr 09 15:16:15 presencepi systemd[1]: Started Monitor Service.
`

Logs do not show anything interesting ... Even when my phone lies beside the raspi. 

In the moment an IP ping is much more trustworthy ...
Anything you can do about?

Thanks
Hannes

**Comment by andrewjfreyer** [comment]
Have you restored preferences? You are using single topic mode according to these two log lines, is this your intention? 

Can you show the logs with verbose output `-V` when run from the command line?

**Comment by andrewjfreyer** [comment]
I found an error related to single topic mode. Please update and see if your issue was related.

**Comment by theHasp** [comment]
Hi, thanks for the offered help...
I updated monitor (rm -rf and than a clone) and copied only the mqtt_pref and the known_static_addr ... and had a semi success the first run showed the status of the two "known" android devices ...
But any change afterwards was ignored (it seems no departure scan or any arrival scan were introduced) ... That I added -b (because I was curios if my garmin would be recognized) and viola it worked like a charm ... (even with no edit in the known_beacon_adresses) ... so I gave it a try and deleted the known_static_adr as well (I commented the 00:00:00:00 line) but the behavior with the phones did not change ...

**Comment by theHasp** [comment]
THANKS
a lot
Hannes

**Comment by andrewjfreyer** [comment]
Hi Hannes, 

I’m confused by the last message here - is your issue solved?

**Comment by theHasp** [comment]
Sorry to be not precise ...
NO issue is not solved. It seems that the "beacon" part is working (as my garmin was recognized) but none of my phones is recognized properly ...

There is only one arrival scan in the beginning. Removing the phone (or turning off BL) is not recognized. So the initial state stays for ever

THANKS for your help
Hannes

**Comment by theHasp** [comment]
This is the output of -V
I started with the sony BL on, and the Huawei BL off and started monitor ... everythings fine. Than I turned off BL on the sony and turned BL on on the Huawei ... but monitor was not able to recognize ...
The prefernces are untouched and not changed after the generation ...
pi@presencepi:~/monitor $ sudo bash monitor.sh -V  
> starting monitor.sh (v. 0.2.150)...
> removing web request caches
> warning: verbose logging is enabled. this setting is only for informational and debugging purposes
> preference: minimum time between the same type of scan = 15
> preference: regex filter for flags to accept = .*
> preference: regex filter for flags to reject = NONE
> preference: regex filter for manufacturers to accept = .*
> preference: regex filter for manufacturers to reject = NONE
> preference: maximum sequential arrive scan attempts = 1
> preference: maximum sequential depart scan attempts = 2
> preference: selected HCI device = hci0
> mqtt trigger: eg/kueche/scan/ARRIVE
> mqtt trigger: eg/kueche/scan/DEPART
mkfifo: der FIFO 'packet_pipe' kann nicht erzeugt werden: Die Datei existiert bereits
> B4:CD:27:13:0E:AA confidence topic: eg/kueche/presencepi/B4:CD:27:13:0E:AA (has previously connected to hci0)
> 58:48:22:9A:52:FA confidence topic: eg/kueche/presencepi/58:48:22:9A:52:FA (has previously connected to hci0)
rm: das Entfernen von '.pids' ist nicht m�glich: Datei oder Verzeichnis nicht gefunden
> log listener pid = 12340
> btle scan pid = 12341
> btle text pid = 12344
> btle listener pid = 12345
> mqtt listener pid = 12348
> packet listener pid = 12351
> beacon database time trigger pid = 12354
[+] 0.2.150 10-04-2019 10:31:34  [CMD-INFO]     **** started arrival scan [x1 max rep] **** 
[+] 0.2.150 10-04-2019 10:31:41  [CMD-SCAN]     (No. 1) B4:CD:27:13:0E:AA arrival? 
[+] 0.2.150 10-04-2019 10:31:48  [CMD-POST]     eg/kueche/presencepi/B4:CD:27:13:0E:AA
 {
    "id":"B4:CD:27:13:0E:AA",
    "confidence":"0",
    "name":"haspDroid ",
    "manufacturer":"HUAWEI TECHNOLOGIES COLTD",
    "type":"KNOWN_MAC",
    "retained":"false",
    "timestamp":"Mi Apr 10 2019 22:31:46 GMT+0200 (CEST)",
    "version":"0.2.150"
 }
[+] 0.2.150 10-04-2019 10:31:50  [CMD-POST]     eg/kueche/presencepi/B4:CD:27:13:0E:AA/rssi
[+] 0.2.150 10-04-2019 10:31:55  [CMD-NAME]     B4:CD:27:13:0E:AA haspDroid  HUAWEI TECHNOLOGIES COLTD
[+] 0.2.150 10-04-2019 10:32:02  [CMD-SCAN]     (No. 1) 58:48:22:9A:52:FA arrival? 
[+] 0.2.150 10-04-2019 10:32:04  [CMD-NAME]     58:48:22:9A:52:FA lineDroid  Sony Mobile Communications Inc
[+] 0.2.150 10-04-2019 10:32:06  [CMD-POST]     eg/kueche/presencepi/58:48:22:9A:52:FA
 {
    "id":"58:48:22:9A:52:FA",
    "confidence":"100",
    "name":"lineDroid ",
    "manufacturer":"Sony Mobile Communications Inc",
    "type":"KNOWN_MAC",
    "retained":"false",
    "timestamp":"Mi Apr 10 2019 22:32:04 GMT+0200 (CEST)",
    "version":"0.2.150"
 }
[+] 0.2.150 10-04-2019 10:32:08  [CMD-INFO]     **** completed arrival scan **** 
[+] 0.2.150 10-04-2019 10:32:16  [CMD-POST]     eg/kueche/presencepi/58:48:22:9A:52:FA/rssi
[+] 0.2.150 10-04-2019 10:32:19  [CMD-RSSI]     58:48:22:9A:52:FA BOFF RSSI: -99 dBm 
Can't create connection: Input/output error
[+] 0.2.150 10-04-2019 10:34:31  [CMD-POST]     eg/kueche/presencepi/58:48:22:9A:52:FA/rssi
[+] 0.2.150 10-04-2019 10:34:32  [CMD-RSSI]     58:48:22:9A:52:FA BOFF RSSI: -99 dBm 
Can't create connection: Input/output error
[+] 0.2.150 10-04-2019 10:36:41  [CMD-POST]     eg/kueche/presencepi/58:48:22:9A:52:FA/rssi
Error: Network is unreachable
[+] 0.2.150 10-04-2019 10:36:41  [CMD-RSSI]     58:48:22:9A:52:FA BOFF RSSI: -99 dBm

**Comment by andrewjfreyer** [comment]
The [+] in the log indicates that the service is running in the background. Essentially, there are two instances of monitor operating, and fighting for control of the bluetooth hardware. Make sure to `sudo systemctl stop monitor` before testing. 

Second, it is possible that neither of your android phones randomly advertise, which is why you're not seeing any random/public advertisements in this log.  I suggest reviewing the FAQ sections regarding android troubleshooting. Enabling filesharing may cause your devices to advertise, connecting to other bluetooth devices may cause your devices to advertise, and so on. 

It also appears that you're in a radio-isolated area - I don't see any random advertisements in this log. Is that correct?

**Comment by andrewjfreyer** [comment]
The best bet here, as with this other issue #161, is to use periodic scan mode, which I have reintroduced.

**Comment by theHasp** [comment]
Thanks I will give it a try
