### ISSUE TITLE
Home Assistant restart

### ISSUE THREAD

**Issue by bigbigblue** [andrewjfreyer/monitor#171]
I am using monitor to detect family phones, none of which seem to transmit BTLE random advertisements. I am therefore triggering arrival and departure scans regularly through MQTT. Most of the time this works very well, however I have noticed that in the event Home assistant is restarted, some of the devices are not reported correctly and are showing as 0% confidence when they are present and showed 100% prior to the HA restart. 
I suspect this is due to HA and monitor somehow being out of sync and monitor not reporting presence to the newly restarted HA. Would it be possible to add a facility to FORCE monitor to issue a name scan and report the device status, perhaps via an MQTT message.

Thanks for taking the time to develop and support monitor, it is very much appreciated.

**Comment by vladtepz** [comment]
@bigbigblue 

If you're NOT using the `-x` flag in Monitor,

This is because by default, Monitor doesn't retain the messages on the mqtt server so the not persistent. So, when you restart HA, the topic appears empty even if it had just been updated by Monitor prior to HA restart.

- Try using the `-x` flag in Monitor to retain mqtt status messages and make the statuses persistent.
<hr>

If you're ARE using the `-x` flag in Monitor,

- You can try having HA send a scan request to monitor upon restarting via an automation using the `monitor/scan/arrive` topic and maybe the `monitor/scan/depart`  topic, if necessary.

- You can try using or creating a app/script/automation to save HA states to a separate DB and restore them to HA on restart.
I use a modified version of [this script](https://github.com/home-assistant/appdaemon/blob/dev/conf/example_apps/switch_reset.py) with Appdaemon. Although I don't specifically use it for the issue you describe, one of it's features includes saving/restoring device_tracker states.

**Comment by bigbigblue** [comment]
@vladtepz 
Thanks for taking the time to reply, however retained MQTT messages are unsatisfactory for my scenario. The presence detection is used to arm/disarm a security system based on the presence or otherwise of the property's inhabitants. If monitor were down for some time, the use of retained MQTT messages would report the status as it was before monitor went down. It is not so much of an issue to incorrectly report a device as 'Away' when it is in fact home, as the alarm can be manually reset by a returning occupant if it goes off. However incorrectly reporting a device as 'Home' when it is actually absent means the property alarm would not be armed even though no-one is present. I would much prefer for HA to be able to ask monitor to 'recheck all known devices and report their current status' at will (for example via an MQTT message).

I currently do not use the -x flag for the above reason. I do ask for an arrival and then a departure scan on HA restart, but it does not seem ALWAYS to correctly report the status of all devices. A forced scan of all devices would solve that issue and avoids the possibility of  incorrect status due to retained MQTT messages.

**Comment by vladtepz** [comment]
@bigbigblue Understandable with your setup and security concerns. 

In regards to the argument against using the `-x` flag in case of a Monitor fail, wouldn't you suffer from the same results without using retained messages? 

HA would still be reporting the last status reported from Monitor before it failed.

<hr>

Now that I understand your situation and reasons, although not 100% positive, unfortunately I don't think a "scan all devices" would work any better if currently running a arrive+depart scan on HA restart isn't 100% accurate, as it would be in theory, the same exact thing.

But that would be better answered by @andrewjfreyer

**Comment by bigbigblue** [comment]
vladtepz 
Thanks,
I actually use the lack of MQTT messages from monitor as a trigger to notify myself that there is a problem, so there is a difference between the retained / not retained situation. I have a timer which is reset every time a monitor MQTT message is received by HA, it none are received before the timer expires then it notifies me of a problem.
If indeed the arrive+depart scan on HA restart causes monitor to send a name request to all known devices and report their status, then I definitely have a problem somewhere as I would expect to be able to see an MQTT for each and every known device, but I do not.... or (more likely) I don't quite understand how monitor works.

**Comment by bigbigblue** [comment]
Here are the MQTT messages captured when a restarted HA requests an arrival and then a departure scan: 
11). topic : monitor/scan/departure/end, messageId : , length : 49, Raw payload : 1233410510010111011610511612134583471971149710310134125
10). topic : monitor/Garage/status, messageId : , length : 29, Raw payload : 111110108105110101
 9). topic : monitor/scan/arrival/end, messageId : , length : 47, Raw payload : 1233410510010111011610511612134583471971149710310134125
 8). topic : monitor/Garage/status, messageId : , length : 29, Raw payload : 111110108105110101
 7). topic : monitor/scan/departure/start, messageId : , length : 51, Raw payload : 1233410510010111011610511612134583471971149710310134125
 6). topic : monitor/Garage/status, messageId : , length : 29, Raw payload : 111110108105110101
 5). topic : monitor/scan/depart, messageId : , length : 21, Raw payload :
 4). topic : monitor/scan/arrival/start, messageId : , length : 49, Raw payload : 1233410510010111011610511612134583471971149710310134125
 3). topic : monitor/Garage/status, messageId : , length : 29, Raw payload : 111110108105110101
 2). topic : monitor/scan/arrive, messageId : , length : 21, Raw payload :-7
 1). topic : monitor/Garage/11:22:33:44:55:66/rssi, messageId : , length : 41, Raw payload : 4555

Line 1) is unilaterally issued by monitor as that particular mac address was paired with the PiZero and therefore the RSSI is reported by monitor.
Line 2) is HA requesting the arrival scan
Line 3) is the 'online' status message from monitor
Line 4) is monitor confirming the arrival scan has started
Line 5)  is HA requesting the departure scan  10 seconds after the arrival scan
Line 6)  is the 'online' status message from monitor
Line 7) is monitor confirming the departure scan has started
Line 8) is the 'online' status message from monitor
Line 9) is  monitor confirming the end of the arrival scan
Line 10) is yet another 'online' status message from monitor
Line 11) is monitor confirming the end of the departure scan

Note - there are no MQTT messages giving the status of any of the (4) known devices. Therefore it would appear that arrival+departure scan is not the same as monitor issuing a name request for each know device and reporting their status. Or have I misunderstood how monitor works?

Cheers

**Comment by bigbigblue** [comment]
Over 30 minutes after the above MQTT message capture and the status of all the unknown devices in HA was still incorrect. I then rebooted the PiZero running monitor and as soon as monitor restarted, it issued the status messages for all devices and they showed correctly in HA.

**Comment by bigbigblue** [comment]
I had a look at the code and to my amazement I worked out that issuing the MQTT topic "monitor/scan/RESTART" restarts the monitor service and offers a circumvention of my issue :-)

**Comment by vladtepz** [comment]
> I had a look at the code and to my amazement I worked out that issuing the MQTT topic "monitor/scan/RESTART" restarts the monitor service and offers a circumvention of my issue :-)

Awesome, Glad you found a viable workaround. :smiley:

FWIW, I think the issue you were having before was running the Arrive & Depart scans at the same time instead of waiting for each scan to complete before calling the next. It may have been messing with the temp cache? Monitor uses to keep track of what devices are actually home or away which caused not all your devices actually getting scanned.

i.e. Depart only scans devices that it thinks are home, Arrive only scans devices it thinks are away.

**Comment by bigbigblue** [comment]
> i.e. Depart only scans devices that it thinks are home, Arrive only scans devices it thinks are away.

I think that is the root of the problem I am experiencing. I would like to be able to tell monitor to scan ALL devices. That way no assumptions are made which could lead to HA and monitor being out of sync.

Cheers

**Comment by andrewjfreyer** [comment]
I understand your scenario. I think it’s a good idea to add an MQTT - triggered force scan.  In the interim, an easy solution is to restart your monitor nodes via MQTT

**Comment by bigbigblue** [comment]
Andrew.  A forced scan would be great. In the mean time, as you suggest, I am currently simply restarting the nodes via MQTT every 60 seconds. Seems to work at the moment.

**Comment by andrewjfreyer** [comment]
Thanks. Closing this for now.
