### ISSUE TITLE
Report status by Nickname rather than MAC address

### ISSUE THREAD

**Issue by bigbigblue** [andrewjfreyer/monitor#172]
Currently the topic for the MQTT status reports from monitor are of the form 'monitor/location/macaddress'. I would like to be able to have them in the form 'monitor/location/nickname' as a selectable option. The reason being that should someone buy a new mobile phone, currently you have to update known_devices to include the mac address of the new device, but also because the MQTT status reports are also linked to the MAC address, all Home assistant automations which work on the status reports for that device must be updated too. If status reports were by nickname rather than mac address, the user would only need  to update know_devices and as long as they do not change the nickname, they would not have to update any automations. Less effort = :-)

**Comment by vladtepz** [comment]
Monitor has a `mqtt_aliases` function which reports to `monitor/location/alias` and should achieve exactly what you're asking for.

https://github.com/andrewjfreyer/monitor/blob/master/support/README.md#its-annoying-to-have-to-keep-track-of-mac-addresses-cant-i-just-use-an-alias-for-the-mac-addresses-for-mqtt-topics

**Comment by bigbigblue** [comment]
Awesome. Thank you. I will use that facility, however there are still 2 places to update the information, whereas if the alias from the known_devices could be used, then it would only be one, which would be even better.
