### ISSUE TITLE
Seemingly no verification for MQTT publishing

### ISSUE THREAD

**Issue by Villhellm** [andrewjfreyer/monitor#173]
I have an intermittent problem that I'm trying to debug. Sometimes a device will show `100` confidence in my mqtt broker (a device I know to not be home), but when I check the status of the monitor service and force a depart scan, the device doesn't show up as a device that's being scanned for departure. Restarting the service fixes the stuck value.

My theory is that the pi zero loses wifi connection during the time that the departure scan for that device occurs so the messages aren't actually being published to anything, and the broker is never informed thereafter that the device state has changed. Occasionally I will have a device get stuck on a level between 0 and 100 according to my broker, which further supports this theory.

Is there any sort of "broker online" check before publishing messages? Or are they sent blind?

If this problem is what I think it is I think the easiest fix would be to publish confidence levels regardless of previous status. So during each arrival/departure scan each known device confidence gets published to the broker even if it is a repeat.

**Comment by andrewjfreyer** [comment]
> Is there any sort of "broker online" check before publishing messages? Or are they sent blind?

Interesting point. I'll think on a solution to this. As for your proposed suggestion, a lot of users have concern over MQTT noise. I'm trying to avoid redundant messaging for now.

**Comment by Villhellm** [comment]
Maybe subscribe to the topic and read the current value before posting? I don't know how practical that would be.

Thanks for taking the time to look at the problem. It doesn't happen often, maybe only once or twice a month for that perfect storm of departure and wifi disconnection.

**Comment by andrewjfreyer** [comment]
I'm sure there's a "attempt delivery XX times" setting in mosquitto_pub. This is probably an easy fix, although I won't have much time to investigate in the near term. 

Thanks for the report!

**Comment by andrewjfreyer** [comment]
Updated to qos 2 on the beta - this should alleviate your issue of short hiccups. Please test and let me know! 

Closing for now.

**Comment by Villhellm** [comment]
Thanks! Just pulled and switched to beta for both my nodes, I'll keep you updated.
I like the change in device topic, by the way. Much easier to work with.

**Comment by abien** [comment]
I might have a similar issue. Occasionally the rpi will lose its network:

`Apr 30 08:18:22 pi_0-1 bash[446]: Error: Network is unreachable
Apr 30 08:18:22 pi_0-1 bash[446]: [+] 0.2.186 30-04-2019 08:18:22 am #033[01;33m[CMD-POST]#033[0m#011#033[01;33mlocation/EG/abien#033[0m
Apr 30 08:18:22 pi_0-1 bash[446]: Error: Network is unreachable
Apr 30 08:18:34 pi_0-1 bash[446]: Error: Network is unreachable
Apr 30 08:18:35 pi_0-1 bash[446]: Error: Network is unreachable
Apr 30 08:18:35 pi_0-1 bash[446]: Error: Network is unreachable
Apr 30 08:18:35 pi_0-1 bash[446]: #033[1A[+] 0.2.186 30-04-2019 08:18:35 am #033[01;33m[CMD-POST]#033[0m#011#033[01;33mlocation/EG/abien#033[0m (x2)
Apr 30 08:18:35 pi_0-1 bash[446]: Error: Network is unreachable
Apr 30 08:18:38 pi_0-1 bash[446]: Error: Network is unreachable
Apr 30 08:18:38 pi_0-1 bash[446]: #033[1A[+] 0.2.186 30-04-2019 08:18:38 am #033[01;33m[CMD-POST]#033[0m#011#033[01;33mlocation/EG/abien#033[0m (x3)
Apr 30 08:18:38 pi_0-1 bash[446]: Error: Network is unreachable
Apr 30 08:18:38 pi_0-1 bash[446]: Error: Network is unreachable
Apr 30 08:18:38 pi_0-1 bash[446]: [+] 0.2.186 30-04-2019 08:18:38 am #033[1;36m[CMD-NAME]#011#033[0mC4:98:80:D0:DE:00 #033[1;32mabien #033[0m Apple Inc#033[0m` 

This will only happen during arive/depart scans. I am thinking the BT is interfering with the WLAN.
Would it be possible to create a configurable/optional delay in sending the mqtt messages?

**Comment by andrewjfreyer** [comment]
> Would it be possible to create a configurable/optional delay in sending the mqtt messages?

I think I can come up with a solution without causing a delay. One thing you might consider is setting the PREF_INTERSCAN_DELAY to a value greater than 3 seconds. Consider 10?

**Comment by Villhellm** [comment]
The beta does not fix the issue as far as I can tell. It also appears that manual arrival/departure scans are no longer working. Is that a beta thing or did something change?

**Comment by andrewjfreyer** [comment]
@Villhellm so are you still seeing "stuck" confidence values?

**Comment by Villhellm** [comment]
Yes, one of my nodes got stuck on `90` this morning. I just updated to the latest beta

**Comment by andrewjfreyer** [comment]
Can you post logs from this morning?

**Comment by Villhellm** [comment]
```
May 01 13:45:00 raspberrypi bash[14937]: [+] 0.2.185 01-05-2019 01:45:00 pm [CMD-NAME] Michelle  Samsung Electronics CoLtd
May 01 13:44:59 raspberrypi bash[14937]: [111B blob data]
May 01 13:41:24 raspberrypi bash[14937]: [+] 0.2.185 01-05-2019 01:41:24 pm [CMD-NAME] Will  Samsung Electronics CoLtd
May 01 13:41:24 raspberrypi bash[14937]: Error: Network is unreachable
May 01 13:41:24 raspberrypi bash[14937]: Error: Network is unreachable
May 01 13:41:24 raspberrypi bash[14937]: [82B blob data]
May 01 13:41:24 raspberrypi bash[14937]: Error: Network is unreachable
May 01 13:41:21 raspberrypi bash[14937]: Error: Network is unreachable
May 01 13:41:21 raspberrypi bash[14937]: [82B blob data]
May 01 13:41:21 raspberrypi bash[14937]: Error: Network is unreachable
May 01 13:41:12 raspberrypi bash[14937]: [+] 0.2.185 01-05-2019 01:41:12 pm [CMD-POST]        location/garage/will
May 01 13:33:42 raspberrypi bash[14937]: [+] 0.2.185 01-05-2019 01:33:41 pm [DEL-RAND]        RAND expired after 189 seconds
May 01 13:30:53 raspberrypi bash[14937]: [+] 0.2.185 01-05-2019 01:30:53 pm [CMD-NAME] Matt  Apple Inc
May 01 13:30:53 raspberrypi bash[14937]: [+] 0.2.185 01-05-2019 01:30:53 pm [CMD-NAME] Michelle  Samsung Electronics CoLtd
May 01 13:30:34 raspberrypi bash[14937]: [+] 0.2.185 01-05-2019 01:30:34 pm [CMD-POST]        location/garage/will
```

So it looks like, according to Home Assistant history and this log, my phone (location/garage/will) was detected by the garage node at 5:30 this morning (my pi clock is wrong, so 5:30 is 13:30 in this log)  and then started the departure scan at 5:41, lost connection when `90` was posted (according to HA) and thereafter I see no `CMD-POST` for `location/garage/will` (I left home shortly after this happened so it's unsurprising that my phone was not detected again).

**Comment by andrewjfreyer** [comment]
Ok. Am I correct in predicting that your garage is decently far from an access point? So not only are we dealing with the potential for 2.4GHz interference, we're potentially dealing with general wifi connection integrity too? 

I'll think on a solution.

**Comment by Villhellm** [comment]
Yes it periodically loses connection for a short while due to it's positioning.

When the "network is unreachable" error comes up could it be set to retry in 30 seconds (or some other possibly configurable time)? It seems as though the script sees the error, but just kinda ignores it and tries to post anyway.

Maybe a LWT could be utilized to retry posting upon reconnecting

**Comment by andrewjfreyer** [comment]
Beta has a rudimentary failure handler for mqtt messaging. Right now, it'll halt everything and infinitely loop if a network error prevents a message from being delivered. 

Obviously, this will be updated to timeout but I'm letting you know that this is available.

**Comment by Villhellm** [comment]
Sounds perfect. I'll load it up now. I'll try to keep an eye out for the network error

**Comment by andrewjfreyer** [comment]
Update to 0.2.196 - this is the "final" version of the mqtt error handling that I'm actively testing now. It will not infinitely loop - you'll have a window of 45 seconds for your network to come back online. in other words, mosquitto will try again up to 3 times separated by 15 second delays. 

I'll close this issue as fixed in beta unless I hear otherwise from your testing. Thanks!
