### ISSUE TITLE
Monitor detection range very lacking

### ISSUE THREAD

**Issue by trueppp** [andrewjfreyer/monitor#174]
Hi, i've been using your presence script for a long time and it works perfectly. But as suggested, I tried monitor and am having problems with it not detecting our phones until we are in the house, while presence detects us as soon as we enter the property. Is there any way to fix that?

I mean presence detects us from 15 ft away from the door if we arrive by car and 50 ft on foot. Monitor has trouble in the house

**Comment by andrewjfreyer** [comment]
You'll have to be a lot more specific if you'd like assistance here. Have you reviewed the FAQ? What phones are you using? What settings are you using? etc. etc.
