### ISSUE TITLE
a mqtt message for monitor's status ?

### ISSUE THREAD

**Issue by hatemzidi** [andrewjfreyer/monitor#177]
hi,  

i was wondering if is it possible to add an mqtt message for monitor.sh' status like it's already done with zigbee2mqtt? 
in fact, the later has a "zigbee2mqtt/bridge/state" that returns it's online, running ... etc (cf : https://www.zigbee2mqtt.io/integration/home_assistant.html )

this will be helpful to monitor if everything is running correctly especially from home assistant.

thanks

**Comment by andrewjfreyer** [comment]
Monitor responds to `monitor/echo` with an online message. many users use this as a replacement for a heartbeat. 

Monitor also send status updates to `monitor/status`. Online is sent prior to each device status message and offline is sent as a last will.
