### ISSUE TITLE
README reflects a change that doesn't seem to be live yet

### ISSUE THREAD

**Issue by Villhellm** [andrewjfreyer/monitor#178]
[This change](https://github.com/andrewjfreyer/monitor/blob/master/support/README.md#its-annoying-to-have-to-keep-track-of-mac-addresses-cant-i-just-use-a-nickname-for-the-mac-addresses-for-mqtt-topics) still only appears to be live in the beta branch. I switched to master and it is still publishing to the MAC address topic by default.

**Comment by andrewjfreyer** [comment]
I just switched back to master to test, and messages are being published to aliases just fine. Can you provide any further detail? 

Can you post your behavior preferences, static addresses file, and logs showing the incorrect mqtt topic path?

**Comment by Villhellm** [comment]
I'm a dummy and forgot to pull after switching branches...

**Comment by Villhellm** [comment]
Sorry about that. Apparently I'm still waking up.

**Comment by andrewjfreyer** [comment]
All good. I prefer overreporting of issues to underreporting 100% of the time!
