### ISSUE TITLE
mqtt_preferences password hash

### ISSUE THREAD

**Issue by KnottySean** [andrewjfreyer/monitor#179]
Any way to use mosquitto_passwd hashed creds file instead of user/password?  Not super pumped about having username/password in ps output.

**Comment by andrewjfreyer** [comment]
yes, you can specify a certfile in mqtt_preferences using `$mqtt_certificate_path`

**Comment by andrewjfreyer** [comment]
Huh, I though this was documented. Must have been removed. Sorry! [Updated the FAQ.](https://github.com/andrewjfreyer/monitor/tree/beta/support#can-i-use-a-certfile-for-mosquitto-instead-of-my-password)
