### ISSUE TITLE
MiBand2 Data

### ISSUE THREAD

**Issue by Odianosen25** [andrewjfreyer/monitor#18]
Hello @andrewjfreyer,

Not an issue, but just got [this](https://medium.com/machine-learning-world/how-i-hacked-xiaomi-miband-2-to-control-it-from-linux-a5bd2f36d3ad) and [this](https://github.com/creotiv/MiBand2) is the code, for I don't know if you have seen this already. its a way to get data from the MiBand2 devices.

Do you think its something that can be integrated? Its written in Python and so I could possible modify it to work over MQTT. But as your script takes control of the hardware occasionally, might be not so easy managing the interaction. 

So my thoughts are, is it possible to assume when the `monitor` is idle, the hardware is released and this code can be ran to carry out its tasks? I am thinking of buying this device, but mainly so I can get out of it all these data.

Regards

**Comment by Odianosen25** [comment]
> I wont add support for individual devices like this - that'll get out of control very, very fast

Oh no I am not requesting that, that will be mean of me as I know the amount of work involved; and as you said will get out of hand.

> I could send an MQTT message when lescan operations are idle and add an expected idle duration

This I think will be very cool, especially with the time duration.

> How much time do you anticipate needing to pair and collect data?

Honestly no clue as I am yet to test it

> There's a flag now to specify which hci device montior uses - perhaps get device-specific information from a separate bluetooth device?

Now this is my best solution, as I didn't know this was now possible. I was going to ask you if it was possible to have multiple Bluetooth devices on the same Pi and specify which to use; so I guess its now possible. With this, one can then use another for this one.

I still think having the ability to tell when its idle with time duration will really be very great. Then I can have an Appdaemon app that acts like a "coordinator" and tell the python script over mqtt when to scan and when to stop.

Thanks and regards

**Comment by andrewjfreyer** [comment]
@Odianosen25 as you may have noticed, I'm now messaging the complete advertisement packet received for a given device. Although this may not get all information from a btle beacon that requires connection, you may be able to extract some useful information for your usecases.

closing for now. 

Thanks!

**Comment by Odianosen25** [comment]
Hello @andrewjfreyer,

many thanks for this, and your work and support is very much appreciated. 

I updated to the latest 1.639 and after the first scan at start up, began to get the following errors:

```
0.1.639 06:50:58 am [CMD-INFO]  **** Completed departure scan. ****
0.1.639 06:50:59 am [ERROR]     Correcting HCI error: Invalid device: Network is0.1.639 06:51:09 am [ERROR]     Correcting HCI error: Invalid device: Network is down (x2)
0.1.639 06:51:23 am [CHECK-DEL] 50:A0:18:E5:CD:EE expired after 76 (15 bias) seconds RAND_NUM: 5
0.1.639 06:51:24 am [CHECK-DEL] 78:16:E1:A9:83:21 expired after 75 (15 bias) seconds RAND_NUM: 4
0.1.639 06:51:25 am [ERROR]     Correcting HCI error: Disable scan failed: Input/output error
0.1.639 06:51:35 am [ERROR]     Correcting HCI error: Invalid device: Network is0.1.639 06:51:45 am [ERROR]     Correcting HCI error: Invalid device: Network is down (x2)
0.1.639 06:51:56 am [CMD-RSSI]  08:1C:B9:E2:72:27 Undiscoverable Device Name RAND RSSI: -76 dBm (Slow/No Motion, changed -11)
0.1.639 06:52:01 am [ERROR]     Correcting HCI error: Disable scan failed: Input/output error
0.1.639 06:52:11 am [ERROR]     Correcting HCI error: Invalid device: Network is0.1.639 06:52:21 am [ERROR]     Correcting HCI error: Invalid device: Network is down (x2)
0.1.639 06:52:37 am [ERROR]     Correcting HCI error: Disable scan failed: Input/output error
0.1.639 06:52:47 am [ERROR]     Correcting HCI error: Invalid device: Network is0.1.639 06:52:58 am [ERROR]     Correcting HCI error: Invalid device: Network is down (x2)
0.1.639 06:53:13 am [ERROR]     Correcting HCI error: Disable scan failed: Input/output error
0.1.639 06:53:24 am [ERROR]     Correcting HCI error: Invalid device: Network is0.1.639 06:53:34 am [ERROR]     Correcting HCI error: Invalid device: Network is down (x2)
0.1.639 06:53:44 am [CMD-RSSI]  08:1C:B9:E2:72:27 Undiscoverable Device Name RAND RSSI: -66 dBm (Slow/No Motion, changed 17)
0.1.639 06:53:44 am [INSTRUCT] mqtt trigger arrive {presence/scan/Arrive (null)
0.1.639 06:53:50 am [ERROR]     Correcting HCI error: Disable scan failed: Input/output error
0.1.639 06:54:00 am [ERROR]     Correcting HCI error: Invalid device: Network is0.1.639 06:54:10 am [ERROR]     Correcting HCI error: Invalid device: Network is down (x2)
```

I was really making the system slow, and even if I sent scan messages, it would ignore for over 10 seconds or so until it connects again.

Due to this, I had to revert back to 1.631 for the mean time.

Also another thing, when the system boots up, the name of the device it sends if the device's name itself. But after that time, it sends the name specified in the `known_static_addresses`. This causes a bit of a confusion, as it will mean one must use the same device name. That wouldn't be an issue, but in some cases the device name is determined not be user, but by company. So it becomes a bit harder to use the same across in the file.

Regards
