### ISSUE TITLE
MQTT / Misc Questions

### ISSUE THREAD

**Issue by ragenhe** [andrewjfreyer/monitor#181]
Are the install / setup procedures installing a new broker?
Or can an existing broker be used?

Are there known issues attempting to run this on a Debian host, instead of Raspbian?

**Comment by andrewjfreyer** [comment]
No, the instructions presume you have a broker already set up. Instructions to set up and use an mqtt broker are beyond the scope of this project. 

The script should work perfectly fine on Debian.

**Comment by ragenhe** [comment]
Perfect!! Thank you!!!

Thank you!
Ragen

________________________________
