### ISSUE TITLE
Active scanner + overrule HA 'consider_home'

### ISSUE THREAD

**Issue by SaturnusDJ** [andrewjfreyer/monitor#183]
After the reading the README, I still have to admit I am not fully understanding this software.

I guess the best approach is to explain my situation.

Currently Home Assistant runs on a Raspberry Pi 3b. It's okay but the speed can be annoying at times, thus considering to move it to the file server. However, I use the Bluetooth chip of the RPi for presence detection of (currently only) 1 device.

HA config:
```
device tracker:
  - platform: bluetooth_le_tracker
    interval_seconds: 30
    consider_home: 120
```
In known_devices.yaml:
```
X:
  hide_if_away: false
  mac: BLE_xx:xx:xx:xx:xx:xx
  name: X
  track: true
```

Arrival and departure of this device cannot be made 'passive' because taking the device outside of the house will not always trigger a sensor on the way. Thus the MQTT arrival/depart message will not always be send from HA.

I am dependent on a scanner that will scan actively, let's say (as in current HA config) each 30 seconds. And also to mark the device away as soon as a scan is done in which the device has not been found.

This last requirement gives trouble in current HA config, as https://www.home-assistant.io/components/device_tracker/ says that "Device tracker will only look for global settings under the configuration of the first configured platform." Because of other device tracker components scanning every 90 seconds due to the system load more frequent scans would give, I am keeping the `consider_home` value at 120, but for Bluetooth devices a much lower number would be preferred. Therefore the 'consider home value' should be component specific. Not possible in HA, as far as I know.

So I have 2 reasons to move to a setup where HA goes to a faster server, and Monitor will report from the Pi, but only if Monitor can report actively and force a device to be present or not present every 30 seconds, somehow ignoring the 'consider_home' value in HA.

I guess it is possible to have HA send the arrival/departure MQTT messages automatically every 30 seconds, but maybe there is a better solution for this plus I am not sure if that would work around the 'consider_home' problem.

**Comment by andrewjfreyer** [comment]
do you have a question I can help answer?

**Comment by SaturnusDJ** [comment]
> 
> 
> do you have a question I can help answer?

Haha yes!

1. Can Monitor scan actively?
2. Can Monitor report to HA in such way that device state changes are reported within 30 seconds, regardless of the HA 'consider_home value?'

**Comment by andrewjfreyer** [comment]
Yes to both of your questions. 

But primarily, `monitor` is focused on providing presence *data* via mqtt. It is not a sensing endpoint (e.g., nmap, icloud, HA btle, etc) that needs to queried at any interval by Home Assistant. 

Think about it like this. The `device_tracker` global settings you're referencing above wouldn't at all be necessary if those devices/methods were reliable at all. Instead, nmap just answers the question of "did DEVICE respond to a ping *right now*"? There's no error checking there, so you need a timeout window like the `consider_home` value. 

`monitor` is a higher level tool. It outputs data is more or less a binary indication of presence. No processing or thresholding on HA's part is required, although it can be helpful for automations and whatnot. 

So, the true answer to your question above is "it doesn't matter what those values are, that's not how monitor works." The more helpful answer is to use `monitor` as a sensor or an mqtt device_tracker and not worry about HA configuration vars. 

Follow the instructions in the readme to set up monitor as a sensor - that's a great place to start.

**Comment by SaturnusDJ** [comment]
@andrewjfreyer 

Got the https://www.home-assistant.io/components/device_tracker.mqtt variant setup. MQTT connection is working. Put the MAC addresses in 'known_static_addresses' with correct names. Then started 'experimenting.' Now, hours later the best I get is: run with -b -r, but a few seconds after confidence 100, it becomes 0 and devices are marked as not home, while being home. What am I doing wrong?

**Comment by andrewjfreyer** [comment]
Canyou send logs? Unless you need `-r` for a specific purpose, it's more efficient and faster to use default confugration.

**Comment by SaturnusDJ** [comment]
I just don't have much clue how to configure. Doesn't happen to me often that I'm so stuck. Maybe because I am not well know with Bluetooth terminology. So it becomes very much trial and error.

Let's say I have a Tile Mate and a phone I would like to use. Plus I am not interested in any other BT device that's near; they should not be reported, nor collected in an ignore list, because the list might be huge in a busy street. Tile mate goes into known_beacon_addresses? The phone is not paired with the RPi and never has been. Phone goes into known_static_addresses? That at least gives some results when running with `-b`.

This is what happens when using `PREF_BEACON_EXPIRATION=60` and `PREF_DEPART_SCAN_ATTEMPTS=1`


Log:
```
root@Home_Controller:~/monitor-master# ./monitor.sh -b
./monitor.sh: line 45: git: command not found
> starting monitor.sh (v. 0.2.196)...
> removing web request caches
> warning: Recommended package 'git' not found. please consider installing for regular updates.
> warning: variable mqtt_publisher_identity does not appear in: mqtt_preferences. using hostname: Home_Controller.
> 22:22:22:22:22:22 confidence topic: monitor/Home_Controller/phone (has not previously connected to hci0)
> 22:22:22:22:22:22 device_tracker topic: monitor/Home_Controller/phone/device_tracker [not_home or home]
> known beacon: 11:11:11:11:11:11 publishes to: monitor/Home_Controller/tile
03-05-2019 10:07:40 PM [CMD-PUBL]   99:99:99:99:99:99 Undeterminable Apple, Inc. -91 dBm
03-05-2019 10:07:47 PM [CMD-MQTT]   monitor/Home_Controller/99:99:99:99:99:99/device_tracker { ... confidence : 100 ... }
03-05-2019 10:07:49 PM [CMD-MQTT]   monitor/Home_Controller/99:99:99:99:99:99 { ... confidence : 100 ... }
03-05-2019 10:07:50 PM [CMD-PUBL]   11:11:11:11:11:11 Tile Tile, Inc. -38 dBm
03-05-2019 10:07:53 PM [CMD-MQTT]   monitor/Home_Controller/tile/device_tracker { ... confidence : 100 ... }
03-05-2019 10:07:57 PM [CMD-MQTT]   monitor/Home_Controller/tile { ... confidence : 100 ... }
03-05-2019 10:07:59 PM [CMD-MQTT]   monitor/Home_Controller/phone/device_tracker { ... confidence : 0 ... }
03-05-2019 10:08:01 PM [CMD-MQTT]   monitor/Home_Controller/phone { ... confidence : 0 ... }
03-05-2019 10:08:03 PM [CMD-NAME]   22:22:22:22:22:22 Phone  Apple Inc
03-05-2019 10:08:39 PM [CMD-INFO]   cycling bluetooth hardware on hci0. please wait a moment...
03-05-2019 10:08:43 PM [CMD-MQTT]   monitor/Home_Controller/tile { ... confidence : 40 ... }
03-05-2019 10:08:48 PM [CMD-MQTT]   monitor/Home_Controller/99:99:99:99:99:99 { ... confidence : 47 ... }
03-05-2019 10:08:52 PM [CMD-MQTT]   monitor/Home_Controller/tile { ... confidence : 29 ... }
03-05-2019 10:08:52 PM [CMD-PUBL]   99:99:99:99:99:99 Undeterminable Apple, Inc. -90 dBm
03-05-2019 10:08:56 PM [CMD-MQTT]   monitor/Home_Controller/99:99:99:99:99:99/device_tracker { ... confidence : 100 ... }
03-05-2019 10:08:58 PM [CMD-MQTT]   monitor/Home_Controller/99:99:99:99:99:99 { ... confidence : 100 ... }
03-05-2019 10:08:58 PM [CMD-PUBL]   11:11:11:11:11:11 Tile Tile, Inc. -37 dBm
03-05-2019 10:09:02 PM [CMD-MQTT]   monitor/Home_Controller/tile/device_tracker { ... confidence : 100 ... }
03-05-2019 10:09:04 PM [CMD-MQTT]   monitor/Home_Controller/tile { ... confidence : 100 ... }
03-05-2019 10:10:54 PM [DEL-PUBL]   PUBL 99:99:99:99:99:99 expired after 64 seconds
03-05-2019 10:10:58 PM [CMD-MQTT]   monitor/Home_Controller/99:99:99:99:99:99/device_tracker { ... confidence : 0 ... }
03-05-2019 10:11:00 PM [CMD-MQTT]   monitor/Home_Controller/99:99:99:99:99:99 { ... confidence : 0 ... }
03-05-2019 10:11:00 PM [DEL-PUBL]   PUBL 11:11:11:11:11:11 expired after 62 seconds
03-05-2019 10:11:04 PM [CMD-MQTT]   monitor/Home_Controller/tile/device_tracker { ... confidence : 0 ... }
03-05-2019 10:11:06 PM [CMD-MQTT]   monitor/Home_Controller/tile { ... confidence : 0 ... }
03-05-2019 10:11:06 PM [CMD-RSSI]   PUBL 99:99:99:99:99:99 RSSI: -92 dBm (initial reading | 108 dBm)
03-05-2019 10:11:06 PM [CMD-PUBL]   99:99:99:99:99:99 Undeterminable Apple, Inc. -92 dBm
03-05-2019 10:11:10 PM [CMD-MQTT]   monitor/Home_Controller/99:99:99:99:99:99/device_tracker { ... confidence : 100 ... }
03-05-2019 10:11:12 PM [CMD-MQTT]   monitor/Home_Controller/99:99:99:99:99:99 { ... confidence : 100 ... }
03-05-2019 10:11:13 PM [CMD-PUBL]   11:11:11:11:11:11 Tile Tile, Inc. -39 dBm
03-05-2019 10:11:17 PM [CMD-MQTT]   monitor/Home_Controller/tile/device_tracker { ... confidence : 100 ... }
03-05-2019 10:11:19 PM [CMD-MQTT]   monitor/Home_Controller/tile { ... confidence : 100 ... }
03-05-2019 10:11:21 PM [CMD-NAME]   22:22:22:22:22:22 Phone  Apple Inc
03-05-2019 10:12:03 PM [CMD-MQTT]   monitor/Home_Controller/tile { ... confidence : 45 ... }
03-05-2019 10:12:04 PM [CMD-PUBL]   11:11:11:11:11:11 Tile Tile, Inc. -40 dBm
03-05-2019 10:12:08 PM [CMD-MQTT]   monitor/Home_Controller/tile/device_tracker { ... confidence : 100 ... }
03-05-2019 10:12:10 PM [CMD-MQTT]   monitor/Home_Controller/tile { ... confidence : 100 ... }
```
(Removed [-] 0.2.196 from each line)

What am I doing wrong. I am trying to get to that 30 seconds goal.
Let's say: Within 60 seconds HA should know when a BT device is not home. Within 30 seconds HA should know when a BT is home.

**Comment by SaturnusDJ** [comment]
If you prefer, we can move to https://community.home-assistant.io/t/monitor-reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/68505.

Another log:
```
02:45:42 PM [CMD-PUBL] 11:11:11:11:11:11 Tile Tile, Inc. -75 dBm
02:45:48 PM [CMD-MQTT] monitor/HC/tile/device_tracker { ... confidence : 100 ... }
02:45:50 PM [CMD-MQTT] monitor/HC/tile { ... confidence : 100 ... }
02:45:51 PM [CMD-PUBL] 99:99:99:99:99:99 Undeterminable Apple, Inc. -100 dBm
02:45:55 PM [CMD-MQTT] monitor/HC/99:99:99:99:99:99/device_tracker { ... confidence : 100 ... }
02:45:57 PM [CMD-MQTT] monitor/HC/99:99:99:99:99:99 { ... confidence : 100 ... }
02:46:44 PM [CMD-MQTT] monitor/HC/tile { ... confidence : 47 ... }
02:46:48 PM [CMD-MQTT] monitor/HC/tile { ... confidence : 40 ... }
02:46:53 PM [CMD-MQTT] monitor/HC/tile { ... confidence : 34 ... }
02:46:53 PM [CMD-PUBL] 11:11:11:11:11:11 Tile Tile, Inc. -75 dBm
02:46:57 PM [CMD-MQTT] monitor/HC/tile/device_tracker { ... confidence : 100 ... }
02:46:59 PM [CMD-MQTT] monitor/HC/tile { ... confidence : 100 ... }
```
Config:
```
# ---------------------------
#
# BEHAVIOR PREFERENCES
#
# ---------------------------

#MAX RETRY ATTEMPTS FOR ARRIVAL
PREF_ARRIVAL_SCAN_ATTEMPTS=1

#MAX RETRY ATTEMPTS FOR DEPART
PREF_DEPART_SCAN_ATTEMPTS=1

#SECONDS UNTIL A BEACON IS CONSIDERED EXPIRED
#240
PREF_BEACON_EXPIRATION=80

#MINIMUM TIME BEWTEEN THE SAME TYPE OF SCAN (ARRIVE SCAN, DEPART SCAN)
#15
PREF_MINIMUM_TIME_BETWEEN_SCANS=10

#ARRIVE TRIGGER FILTER(S)
PREF_PASS_FILTER_ADV_FLAGS_ARRIVE=".*"
PREF_PASS_FILTER_MANUFACTURER_ARRIVE=".*"

#ARRIVE TRIGGER NEGATIVE FILTER(S)
PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE="NONE"
PREF_FAIL_FILTER_MANUFACTURER_ARRIVE="NONE"


PREF_DEVICE_TRACKER_REPORT=true
PREF_INTERSCAN_DELAY=2

# -r only
PREF_DEPART_SCAN_INTERVAL=15
PREF_ARRIVE_SCAN_INTERVAL=15
```
`-b` flag used.

Since I won't be using phones in production environment let's ignore that topic for now. The focus thus in on the Tile Mate. Which I still assume is a beacon class device. My Tile Mate is not paired anymore with a device. It's purely used for presence detection. There will not be a trigger for Monitor to start arrival/departure scans, since I don't have sensors for that. Thus Monitor itself should find out when the Tile comes and goes.

So what happened this morning is that the Tile left. Cannot make conclusions about how quickly that was detected, but it worked. When it came back I observed the same behaviour as in the log.

The Tile is on a static position within a few meters from the Bluetooth chip.
Why is confidence dropping?
Why is confidence dropping sometimes, but not always?

Please explain me how this works. Is the Tile sending a beacon message at a static or dynamic interval and is my '80 seconds' too tight? Or is Monitor asking the Tile for a beacon?
What should I do to make it reliable?

Question 2: It is possible to ignore all device except the specified ones? (Thus not collecting a list of addresses to ignore.)

**Comment by andrewjfreyer** [comment]
Unfortunately, I have to be brief right now. I'll expand on these answers later in the day. 

• Your Tile is reporting as a public beacon, as shown in the logs. There is no need (although no negative effect) to include in your static beacons file (this file is reserved for beacons that advertise with random addresses, but the addresses do not change frequently).

• Your interval of 80 is very low and will cause confidence drops. Most beacons only advertise every 30 - 90 seconds. Realistically, your bluetooth hardware won't receive 100% of advertisements (e.g., it might miss one), so missing one advertisement at 60 second intervals means that there is 120 seconds between advertisements received by `monitor`. If Tile advertises on 90 second intervals, the problem is worse - clearly confidence will drop in this interval. 

Also, `monitor` bases confidence of beacons on an "observed interval" between sequential advertisements. So, if monitor observes two sequential advertisements from your tile at 90 seconds apart, it will start losing confidence after 90 seconds has passed. (not quite exactly 90 seconds, but this is the gist. The more detailed answer is more complex given montor's sturcture).

Confidence is a percentage, not a binary value. Confidence dropping is a sign that your device *may* have left. If you want binary values only, ignore any confidences except 100 and 0. 

If you are not using phones, -tad and -b should be suitable options.

**Comment by SaturnusDJ** [comment]
Thanks! Slowly starting to understand.

The Tile Mate takes on and drops many addresses, but luckily it is keeping one specific address all of the time.

Your paragraph starting with "Also"... Do you mean to say that Monitor tries to figure out what the beacon interval is? The user input is a reference number?

I will have to tweak the beacon interval. So I started doing that 2 hours ago with good results. 90 seconds deserves real life tests. 

Except...
Took it out of range again half an hour ago, and didn't see the 'beacon expire,' even after 7 minutes. So now I am lost again for how that is possible. Did not see weird messages in the log.

**Comment by andrewjfreyer** [comment]
yes, its a beacon. the cmd-beac refers to an ibeacon. 

logging can be clustered, but it certainly could be related to your area and would be normal if your beacon intervals are set properly

observed interval is automatically determined by monitor

verbose logging is helpful to see

**Comment by andrewjfreyer** [comment]
Please reopen if you have identified an issue, else please feel free to continue commenting here so we can work through your intstallation and use of this script. 

Thanks!

**Comment by SaturnusDJ** [comment]
Thanks @andrewjfreyer. Seems to be getting more stable now.

After a HA restart the Tile is marked as away. Which option or flag should I set to prevent state change due to broker restart? Running `-b -x` now and I thought `-x` would be for that, but apparently not. I expect `-a` to solve this for sure but that is a bit drastic.

**Comment by andrewjfreyer** [comment]
-x should retain your beacons, but there's a feature upcoming that will solve this problem. Stay tuned.

**Comment by SaturnusDJ** [comment]
@andrewjfreyer 
It runs reasonably stable except when HA restarts. When HA comes back I force Monitor to restart, otherwise trouble, but often the Tile gets timed out any ways after a while. `PUBL 11:11:11:11:11:11 expired after 98 seconds`.
When restarting Monitor manually it is okay again. Any idea why?

**Comment by SaturnusDJ** [comment]
Going very bad after the restarts of HA yesterday.

I feel like there is some interval going on and when restarting Monitor in a certain range of this interval, trouble occurs...*yet* after restart, the Tile always gets detected immediately.
As if the startup scan is something active, and after that only passive.

**Comment by SaturnusDJ** [comment]
Same situation still. It can be stable for days, but as soon as HA restarts, I am getting those beacon time outs, thus an away state and within a few seconds (<10) home again. This can happen immediately after HA restart or maybe 20-40 minutes later. Then I keep restarting Monitor until this does not happen anymore. Most of the times a single restart is enough. I also restart Monitor automatically on HA restart, apparently not enough.

My conclusion is that this is not BLE packet loss or so, because it never happens after it has been 'stabilized.'

**Comment by SaturnusDJ** [comment]
Btw, I set PREF_BEACON_EXPIRATION=120 instead of 90/95, and it is getting worse.
