### ISSUE TITLE
Change hci device

### ISSUE THREAD

**Issue by ezraholm50** [andrewjfreyer/monitor#184]
Hey,

Thanks for this great project! I'm trying to set everything up in my home using an RPI3 and 2x RPI zero. Still a bit overwhelmed but i'm getting there. 

Now my RPI3 has a Bluetooth dongle which i passthrough over the network using Virtualhere, and for monitor i use the onboard Bluetooth. 

Now the script is trying to use HCI0 but i would like it to use HCI1. (I've removed the dongle during the setup and added it back later, to avoid just this.)

```
> xx:xx:xx:xx:44 device_tracker topic: monitor/alarmble/iphone/device_tracker [not_home or home]
[+] 0.2.186 04-05-2019 08:49:22  [CMD-INFO]	cycling bluetooth hardware on hci0. please wait a moment...
Can't get device info: No such device
```
I can see that there is an $PREF_HCI_DEVICE in monitor.sh but not how it is obtained, to try a dirty workaround for this to test.

Please advise.

Thanks again.

Ezra

Edit:

I've tried a `sed -i 's|$PREF_HCI_DEVICE|hci1|g' /home/pi/monitor/monitor.sh` but it seems to hang afterwards.

```
root@raspberrypi:/home/pi/monitor# hcitool dev
Devices:
	hci1	B8:xx:xx:xx:xx:xx
```

Note that the USB dongle does not show up since it is in use by a remote system, but the onboard does get assigned to hci1 instead of hci0

**Comment by andrewjfreyer** [comment]
set PREF_HCI_DEVICE in your behavior preferences file to whichever device you want  :-)

**Comment by ezraholm50** [comment]
Darn thats fast! Great work, thanks!
