### ISSUE TITLE
RSSI Tracking cannot obtain measurement after connecting device

### ISSUE THREAD

**Issue by jimmymesinkers** [andrewjfreyer/monitor#191]
I've followed the instructions to get RSSI readings by running for a known device: 
`sudo bash monitor.sh -c 12:34:56:78:AB:CD`
So I then paired the device. Then when I run monitor I am getting:
```
[-] 0.2.197 15-05-2019 01:12:35 AM [CMD-MQTT]   monitor/bedroom/bt/james_laptop
 {
    "id":"12:34:56:78:AB:CD",
    "confidence":"100",
    "name":"james_laptop",
    "manufacturer":"Intel Corporate",
    "type":"KNOWN_MAC",
    "retained":"false",
    "timestamp":"Wed May 15 2019 01:12:31 GMT+1000 (AEST)",
    "version":"0.2.197"
 }
[-] 0.2.197 15-05-2019 01:12:37 AM [CMD-INFO]   **** completed arrival scan ****
[-] 0.2.197 15-05-2019 01:13:50 AM [CMD-MQTT]   monitor/bedroom/bt/james_laptop/rssi
[-] 0.2.197 15-05-2019 01:13:52 AM [CMD-RSSI]  **12:34:56:78:AB:CD BOFF RSSI: -99 dBm**
```

When messing around I managed to get the RSSI reporting correctly - but I wasn't paying a huge amount of attention and can't seem to reproduce the steps I had taken (playing around with btmgmt, bluetoothctl I think).

It seems to be a connection issue because: 
```
hcitool cc 12:34:56:78:AB:CD
hcitool rssi 12:34:56:78:AB:CD
```
reports "Not connected."

At the same time I am able to connect and report RSSI with a [python script](https://github.com/ewenchou/bluetooth-proximity/blob/master/examples/test_address.py)
so I'm a bit confused why hcitools wouldn't be connecting. 

Do you know what could be the issue here?

**Comment by andrewjfreyer** [comment]
The connection is closing when the hcitool cc command finishes, so try: 

```
hcitool cc 12:34:56:78:AB:CD && hcitool rssi 12:34:56:78:AB:CD
```

**Comment by jimmymesinkers** [comment]
Thanks - the command you have responded reports the RSSI as expected.  
With a little more digging, hcitools is working correctly inside monitor, and monitor is currently reading RSSI values, but is reporting out RSSI readings of 0 as -99dBm because of this line:
`[[ "$scan_result" == "0" ]] && scan_result=99;`
Could you explain why RSSI readings of 0 are being mapped to 99?  As far as I can tell the value I am getting of 0 from my dongle is due to the phone/laptop being very close to the dongle, which if I walk slightly further away goes to e.g. RSSI reading of -4 - or am I mistaken and 0 is not a valid reading?  Or is this just the inconsistency of devices reporting out RSSI values differently making life difficult?

For some more detail: I added an echo immediately after the RSSI was requested:
```
do scan_result=$(hcitool cc "$known_addr" && hcitool rssi "$known_addr" 2>&1); \
echo "$scan_result"
```
Here's the output: 
[-] 0.2.197 15-05-2019 02:12:34 PM [CMD-RSSI]   12:34:56:78:AB:CD BOFF RSSI: **-**RSSI return value: 0
[-] 0.2.197 15-05-2019 02:12:34 PM RSSI return value: 0
[-] 0.2.197 15-05-2019 02:12:34 PM RSSI return value: 0
[-] 0.2.197 15-05-2019 02:12:34 PM **99 dBm**
You can see I get the 3 values of 0 returned, with -99dBm returned (NB my echos are breaking up the return string into "-" and "99dBm")

Also just a general question for my interest - I noticed that the average computed for the RSSI looks like it's doing integer division.  Did you think it wasn't worthwhile to do float division + rounding because RSSI isn't very accurate anyway plus would require extra dependencies?  Just interested in your thought process.

Thanks for your help and this great tool.

**Comment by andrewjfreyer** [comment]
I am sure the averaging algorithm can use some improvement. I will investigate and keep you posted. Thanks!

Closing this issue for now.
