### ISSUE TITLE
json published message with typo?

### ISSUE THREAD

**Issue by luisbarreto** [andrewjfreyer/monitor#193]

**Comment by luisbarreto** [comment]
Hi,
First of all let me thank you very much for such a great and complete project.

I am struggling with the message that `monitor` posts for one of the devices I want to monitor. Considering that the problematic device is mine, it was the only I had configured for the first tests. I only got any progress when by _desperation_, I added the other two devices - this led me to see a tiny difference between published MQTT messages of devices,
Below are the messages published to my MQTT server (I am subscribing `monitor/#` to see everything that's published)  
If you see carefully, the third device gets what I think it is an `Enter` when published to MQTT - there is a `cariage return / line feed` that sepparates the JSON formatted message in the field "name": from the value of the field. This causes the HA sensor to have the `UNKNOWN` value forever. 

```
online
{"id":"AA:AA:AA:AA:AA:AA","confidence":"0","name":"user1","manufacturer":"Samsung Electronics CoLtd","type":"KNOWN_MAC","retained":"false","timestamp":"ter mai 14 2019 23:45:10 GMT+0100 (WEST)","version":"0.2.197"}
-99
online
{"id":"BB:BB:BB:BB:BB:BB","confidence":"0","name":"user2 ","manufacturer":"Samsung Electronics CoLtd","type":"KNOWN_MAC","retained":"false","timestamp":"ter mai 14 2019 23:45:20 GMT+0100 (WEST)","version":"0.2.197"}
-99
online
{"id":"4C:DD:31:CF:C3:E3","confidence":"0","name":"
user3","manufacturer":"Samsung Electronics CoLtd","type":"KNOWN_MAC","retained":"false","timestamp":"ter mai 14 2019 23:45:30 GMT+0100 (WEST)","version":"0.2.197"}

```
I alreade edited the `known_static_addresses` several times confirming that the there is no special character at the end of the line/alias that has the affected device, I also changed the line to the end of the list, to the middle but the problem keeps ocurring.

My current `known_static_addresses` file is: 
```# ---------------------------
#
# STATIC MAC ADDRESS LIST
#
# 00:00:00:00:00:00 Alias #comment
# ---------------------------
b4:74:43:a4:1a:cc user1#User 1 comment
dc:f7:56:f3:6f:01 user2#User 2 comment
4c:dd:31:cf:c3:e3 user3#User3 comment
```

Can you please try to see what can I possibly be doing wrong?
Thanks

**Comment by luisbarreto** [comment]
It's always good to answer our own questions - even not knowing exactly what happened :-) after all tests and changes already made before.

I recreated the `known_static_addresses` from scratch and restarted _mosquitto_ that resides in the same computer as HA. Suddenly the strange behavior I mentioned stopped, and everything is working as expected now.
Thank you once more for this great project and all time spent developing and supporting it.

**Comment by andrewjfreyer** [comment]
Excellent. Thank you for the follow up.
