### ISSUE TITLE
Can we have the option to trigger arrive/depart on a single node?

### ISSUE THREAD

**Issue by gieljnssns** [andrewjfreyer/monitor#194]
Instead of  ```monitor/scan/arrive```    ```monitor/{{name of monitor install}}/scan/arrive```
or ```monitor/scan/depart```    ```monitor/{{name of monitor install}}/scan/depart```
or ```monitor/scan/restart```    ```monitor/{{name of monitor install}}/scan/restart```
or ..........

**Comment by andrewjfreyer** [comment]
Yes, I can support this format.

**Comment by michaelblight** [comment]
In the meantime, you can have different topics for different devices in `mqtt_preferences`. For example I have:

```
# MQTT PUBLISH TOPIC ROOT 
mqtt_topicpath=monitor/81
```
In my case, 81 is the last part of the IP address. Then I trigger a scan with `monitor/81/scan/arrive`, `monitor/82/scan/arrive`, etc.

**Comment by gieljnssns** [comment]
> In the meantime, you can have different topics for different devices in `mqtt_preferences`. For example I have:
> 
> ```
> # MQTT PUBLISH TOPIC ROOT 
> mqtt_topicpath=monitor/81
> ```
> 
> In my case, 81 is the last part of the IP address. Then I trigger a scan with `monitor/81/scan/arrive`, `monitor/82/scan/arrive`, etc.

Good thinking!

**Comment by andrewjfreyer** [comment]
On reconsideration, @michaelblight's solution is much more elegant than incorporating something into the script itself. Thanks!
