### ISSUE TITLE
Monitor Echo

### ISSUE THREAD

**Issue by Odianosen25** [andrewjfreyer/monitor#198]
Hello @andrewjfreyer,

I used the ~/echo as you suggested, as the `heartbeat` been removed. With a single system it works great, and I get the response which I can use within my system.

When I added another monitor instance, for some reasons it seems a loop is created in the system as the response of one, seems to be fed into another and it continues.

I can only stop it when I restart my system, and for now I had to reduce my system to one, as I use the echo for reliability.

Please can you look into this?

Kind regards

**Comment by gieljnssns** [comment]
I think you can try the beta...
https://github.com/andrewjfreyer/monitor/pull/195

**Comment by Odianosen25** [comment]
Many thanks @gieljnssns,

Its been fixed.

Kind regards
