### ISSUE TITLE
RSSI tracking not reported to MQTT

### ISSUE THREAD

**Issue by ezraholm50** [andrewjfreyer/monitor#199]
Hey, thanks again for the great app.

I've ran the connect on each of my monitor devices:
```

root@raspberrypi:/home/pi/monitor# sudo systemctl stop monitor
root@raspberrypi:/home/pi/monitor# bash monitor.sh -c 18:65:90:81:DD:44

===================================================

              *** BETA/DEV BRANCH ***

===================================================
> starting monitor.sh (v. 0.2.186)...
> removing web request caches
> removing previous pairings to 18:65:90:81:DD:44
> creating connection to 18:65:90:81:DD:44...
> witihin 5 seconds, please set 18:65:90:81:DD:44 to discoverable...
> connection created to 18:65:90:81:DD:44
```

Now my MQTT topic looks like this:

![image](https://user-images.githubusercontent.com/13510720/58421796-39cf2200-8091-11e9-99f8-c8f2630de896.png)

Behaviour prefs:

```
# ---------------------------
#
# BEHAVIOR PREFERENCES
#
# ---------------------------

#MAX RETRY ATTEMPTS FOR ARRIVAL
PREF_ARRIVAL_SCAN_ATTEMPTS=1

#MAX RETRY ATTEMPTS FOR DEPART
PREF_DEPART_SCAN_ATTEMPTS=2

#SECONDS UNTIL A BEACON IS CONSIDERED EXPIRED
PREF_BEACON_EXPIRATION=180

#MINIMUM TIME BEWTEEN THE SAME TYPE OF SCAN (ARRIVE SCAN, DEPART SCAN)
PREF_MINIMUM_TIME_BETWEEN_SCANS=15

#ARRIVE TRIGGER FILTER(S)
PREF_PASS_FILTER_ADV_FLAGS_ARRIVE=".*"
PREF_PASS_FILTER_MANUFACTURER_ARRIVE="Apple"

#ARRIVE TRIGGER NEGATIVE FILTER(S)
PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE="NONE"
PREF_FAIL_FILTER_MANUFACTURER_ARRIVE="Google|Bose*|Nest*|Unknown"

# Advanced
PREF_INTERSCAN_DELAY="9"
PREF_COOPERATIVE_SCAN_THRESHOLD="60"
PREF_PERCENT_CONFIDENCE_REPORT_THRESHOLD="59"

PREF_MQTT_REPORT_SCAN_MESSAGES="true"

PREF_DEVICE_TRACKER_REPORT="true"

PREF_DEVICE_TRACKER_HOME_STRING='home'
PREF_DEVICE_TRACKER_AWAY_STRING='not_home'
PREF_DEVICE_TRACKER_TOPIC_BRANCH='device_tracker'
```

Known static:

```
# ---------------------------
#
# STATIC MAC ADDRESS LIST
#
# 00:00:00:00:00:00 Alias #comment
# ---------------------------

18:65:90:81:DD:44 iphone
```

Do i need to add an option flag or something to monitor to have rssi to be persistent?

Please advise.

Kind regards.

**Comment by ezraholm50** [comment]
Ok after some restarts and tinkering i get one value of -99, not a valid reading as i understand 

![image](https://user-images.githubusercontent.com/13510720/58423622-d5fb2800-8095-11e9-8d1e-415e52936f80.png)

**Comment by andrewjfreyer** [comment]
How long are you waiting here? RSSI updates will only occur every few minutes.

**Comment by ezraholm50** [comment]
Infinite, just monitoring the state in my home assistant frontend, not showing up, ever... any clue?

**Comment by TheStigh** [comment]
@andrewjfreyer  is it possible to edit how often we want the RSSI to update?

**Comment by markbajaj** [comment]
Hi all. This is exactly the same thing I am experiencing on my 3 iPhones and 1 Apple watch

If I manually run 

```
sudo hcitool cc C0:D0:12:71:31:B9  && hcitool rssi C0:D0:12:71:31:B9
RSSI return value: 13
```

However the RSSI in the mqtt topic for the phone is always showing -99.

I have 2 RPI zeros running Raspbian Buster talking to an Ubuntu mqqt broker.

Thanks

mb

**Comment by augustjanse** [comment]
This issue seems to be the same as the one discussed in the comments of #209. Anyway, I have it too. Pretty much just followed the installation instructions, added static addresses, paired phones and ran. I had some problems inbetween, so I might do a re-install and see if it fixes things.

**Comment by augustjanse** [comment]
I wrote down a quick fix for this problem in #225.

**Comment by neverbethesky** [comment]
Also having this issues. On the latest Raspbian all fully updated, Pi Zero W.

**Comment by gmalbert** [comment]
@augustjanse I wish that worked, but still having the identical issue. So odd!
