### ISSUE TITLE
Reloading Device States

### ISSUE THREAD

**Issue by Odianosen25** [andrewjfreyer/monitor#200]
Please when using `/KNOWN DEVICE STATES`, can you add device `name` to the payload?

Just as it is, when the system finds the device, and outputs the entire data.

Thanks

**Comment by andrewjfreyer** [comment]
I'll add it to the list.

**Comment by Odianosen25** [comment]
Many thanks boss

**Comment by andrewjfreyer** [comment]
Sorry for the huge delay here, but 0.2.199 should add device name as expected.
