### ISSUE TITLE
running monitor.sh -d to clean up run with flag

### ISSUE THREAD

**Issue by ezraholm50** [andrewjfreyer/monitor#201]
Hey, 

Just to be sure, would the -d flag also clear the other flags monitor.sh is running with?
I need to disable -x and clear the messages.
Couldnt really find anything on this.

or would `bash monitor.sh -u` do it? withouth any flags?

Thanks

**Comment by andrewjfreyer** [comment]
> or would bash monitor.sh -u do it? withouth any flags?

This is correct.
