### ISSUE TITLE
Device is always Unknown

### ISSUE THREAD

**Issue by Nihvel** [andrewjfreyer/monitor#203]
Hi, I tried asking in the Community but no luck looking for an answer.

I have installed Monitor on a  VM inside ESXi (there's also pihole in that VM). The OS is Ubuntu 18.04.

I edited mqtt_preference to link it to Mqtt Broker in HA.
I can see the Log on the broker that something happens:
```
[INFO] found mqtt_user on local database
1560286763: New client connected from 10.0.1.103 as pihole3885 (c1, k60, u'mqtt_user').
1560286763: Client pihole3885 disconnected.
```

While, running `./monitor.sh` I can only get:
```
[CMD-INFO]   cycling bluetooth hardware on hci0. please wait a moment...
[CMD-MQTT]   monitor/pihole/juri_mi3 { ... confidence : 0 ... }
[CMD-NAME]   CD:2C:C9:B4:F4:E4 juri_mi3  Unknown
```

The file `known_static_addresses `'s got the MAC of my Mi Band 3.
Then, I used this sensor, always thanks to your documentation:
```
- platform: mqtt
  state_topic: ' monitor/pihole/juri_mi3'
  value_template: '{{ value_json.confidence }}'
  unit_of_measurement: '%'
  name: 'home'
```

And the DEV section of HA always shows:
`sensor.home  unknown`

I am not sure if there is something I miss. I followed the documentation and the only thing I can think of is the Bluetooth 2.0 dongle I use. But should not be a issue. 

Can I please ask you if you notice something wrong in the above configuration? I have ran/restarted monitor.sh plenty of times in the last 3 weeks and after the 4th time I started it, the Info/Error messages disappeared from the CLI. Errors were about the `bluez-hcidump` and `bluez-tools`. Once installed both, bluetooth was recognized by Ubuntu.
Thank you

**Comment by andrewjfreyer** [comment]
>Bluetooth 2.0 dongle

This is your problem. Monitor relies on bluetooth advertisements, which is a part of BTLE.
