### ISSUE TITLE
Confidence is zero when device is in range

### ISSUE THREAD

**Issue by coolguymatt** [andrewjfreyer/monitor#204]
Monitor will work for several hours, and then stop (sends zero confidence instead of 100 - device is very close to the Raspberry Pi).  I was using the master branch but switched to beta, and the behavior is the same.

When I check the verbose logs, I see the following (I X'ed out the MAC addresses - let me know if that is required for troubleshooting)
```
> log listener pid = 15363
> btle scan pid = 15364
> btle text pid = 15366
> btle listener pid = 15368
> mqtt listener pid = 15370
> packet listener pid = 15372
> beacon database time trigger pid = 15378
[+] 0.2.197 12-06-2019 06:12:08 pm [CMD-INFO]   **** started arrival scan [x3 ma                                                                                                             x rep] ****
[+] 0.2.197 12-06-2019 06:12:12 pm [CMD-SCAN]   (No. 1) XX:XX:XX:XX:XX:XX arriva                                                                                                             l?
[+] 0.2.197 12-06-2019 06:12:12 pm [CMD-RAND]   [passed filter] data: XX:XX:XX:XX:XX:XX pdu: ADV_IND rssi: -68 dBm flags: 0x1a man: Apple, Inc. delay: 0
[+] 0.2.197 12-06-2019 06:12:14 pm [CMD-RAND]   [passed filter] data: XX:XX:XX:XX:XX:XX pdu: ADV_SCAN_IND rssi: -54 dBm flags: none man: Google delay: 1
[+] 0.2.197 12-06-2019 06:12:15 pm [CMD-RAND]   [passed filter] data: XX:XX:XX:XX:XX:XX pdu: ADV_IND rssi: -72 dBm flags: 0x06 man: Tile, Inc. delay: 3
[+] 0.2.197 12-06-2019 06:12:16 pm [CMD-MQTT]   monitor/upstairs/matt
 {
    "id":"XX:XX:XX:XX:XX:XX",
    "confidence":"0",
    "name":"matt",
    "manufacturer":"Apple Inc",
    "type":"KNOWN_MAC",
    "retained":"false",
    "timestamp":"Wed Jun 12 2019 18:12:12 GMT+0100 (BST)",
    "version":"0.2.197"

```

**Comment by andrewjfreyer** [comment]
Are you using a dongle or built-in bluetooth?

**Comment by coolguymatt** [comment]
Built in

**Comment by andrewjfreyer** [comment]
Are you in a noisy bluetooth environment? Lots of other devices around you?

**Comment by coolguymatt** [comment]
I don’t think so? No neighbours, two phones, and six google home devices. Bluetooth is turned off on my laptops. Anything I can run to determine more analytically?

**Comment by TheStigh** [comment]
I run Monitor on a RPi 3b+ with built-in BT, and I do see that this happens to me too when I just sit and watch the logs, even if both phones - and a beacon - are stationary on the table.....

**Comment by coolguymatt** [comment]
I wiped my SD card and started fresh, and haven't had the issue since.

**Comment by uphillbattle** [comment]
I see similar behavior on my two RPiZeroWs using built-in BT and the latest monitor version (albeit, it's been like this since the first version I tested - 0.2.165, I think). I run monitor with default settings.

As a mitigating measure - I've set cron jobs to reboot the RPis every night at 3 am. The rebooting mostly keeps monitor running without problems, although sometimes, one - or both - will start reporting 0 confidence in the presence of monitored phones between reboots. 

I haven't got logs to show here and now, because I haven't seen the problem in a couple of weeks (yay!), but from previous encounters, I have the impression that it's got to do with monitor's communication with the BT module (something about hci0 - can't remember the exact report message). 

So - not a very helpful comment, this, I'm sorry - but a vote of support. :)

Anyways, rebooting every night generally keeps my monitor instances healthy, and I'm overall very happy with monitor. It's the best presence monitoring tool I've seen. Good job, @andrewjfreyer!

**Comment by gadric** [comment]
I have the same problem with the newest version, 0.2.200. 

I am using monitor as device_tracker and rssi measuring with built-in BT. 

I am in a pretty noisy bluetooth environment. I have blacklisted tons of MAC addresses as I want only to track 2 phones. 

But it happens after a couple of hours (max. 4 hours) that Monitor stops recognizing the devices. RSSI goes up to 99 and tracker report not_home. Confidence level drops to zero. Reset of hci0 does not help. I must restart the raspi zero to make monitor work again. 

I am running monitor in default mode. The phones I want to track are listed in known_static_address. They are both connected via -c option. 

behavior_preferences is default, but I added the device_tracker settings for home assistant.

**Comment by davidhitchins** [comment]
I was so pleased to come across MONITOR as it exactly fills the bill for my home monitoring needs.
I installed it on a Raspberry pi 3b+ as well as a RPi ZeroW according the the instructions given.
But unfortunately I'm now stuck on a problem I can't see to resolve: two different iPhones
whose private MAC addresses have been put into the known_static_addresses file always show a confidence
level of zero even though they are both right next to the two RPI "nodes". 

Below is an example of the log with the MAC addresses obfuscated. Any idea what I should try next please?

It should be noted that if I try the following (using the correct private address for one of the phones of course)

sudo bash monitor.sh -c FF:FF:FF:FF:FF:FF

I get this even though the phone says it is in discoverable mode.


> starting monitor.sh (v. 0.2.200)...
> removing web request caches
> removing previous pairings to FF:FF:FF:FF:FF:FF
> creating connection to FF:FF:FF:FF:FF:FF...
> witihin 5 seconds, please set FF:FF:FF:FF:FF:FF to discoverable...
> error: connection to FF:FF:FF:FF:FF:FF failed

LOG RESULTS (deleted second phone but result exactly the same)
....
....
> preference: regex filter for flags to accept = .*
> preference: regex filter for flags to reject = NONE
> preference: regex filter for manufacturers to accept = .*
> preference: regex filter for manufacturers to reject = NONE
> preference: maximum sequential arrive scan attempts = 1
> preference: maximum sequential depart scan attempts = 2
> preference: selected HCI device = hci0
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
mkfifo: cannot create fifo 'packet_pipe': File exists
> FF:FF:FF:FF:FF:FF confidence topic: monitor/gyyydget1/davidsphone (has not previously connected to hci0)
> log listener pid = 16313
> btle scan pid = 16314
> btle text pid = 16316
> btle listener pid = 16317
> mqtt listener pid = 16318
> packet listener pid = 16321
> beacon database time trigger pid = 16323
[+] 0.2.200 20-02-2021 08:37:23 am [CMD-INFO]   **** started arrival scan [x1 max rep] ****
[+] 0.2.200 20-02-2021 08:37:23 am [CMD-SCAN]   (No. 1) FF:FF:FF:FF:FF:FF arrival?
[+] 0.2.200 20-02-2021 08:37:28 am [CMD-MQTT]   monitor/gyyydget1/davidsphone
 {
    "id":"FF:FF:FF:FF:FF:FF",
    "confidence":"0",
    "name":"davidsphone",
    "manufacturer":"Unknown",
    "type":"KNOWN_MAC",
    "retained":"false",
    "timestamp":"Sat Feb 20 2021 08:37:28 GMT+1100 (AEDT)",
    "version":"0.2.200"

**Comment by uphillbattle** [comment]
Is your RPi connected to the network via WiFi? I believe there is an issue with Bluetooth on RPi 3B+ when using WiFi. On one of my RPis 3B+s, where I needed Bluetooth, I had to disable WiFi and run an Ethernet cable instead.

**Comment by davidhitchins** [comment]
Definitely no luck with the Pi ZeroW as well. I don't think the WIFI is an issue.

**Comment by davidhitchins** [comment]
HAVE I SOLVED THIS WEIRD PROBLEM? Possibly. @andrewjfreyer , do you have any comments on the following? I had assumed that the private address given on on my iphone in settings was correct. In the logs quoted in the previous post above this was FF:FF:FF:FF:FF:FF (not really; this is obfuscated) which I put into the file known_static_addresses . 
But I managed to make a htitool scan work and it returned another MAC address, not the one above shown on the phone. I assumed this address - let's call it EE:EE:EE:EE;EE:EE for now - was just a fake temporary MAC address broadcast by my phone to mislead bad actors. But after rebooting the phone and turning things on and off this second address did not change. Maybe it is the REAL fixed private MAC ADDRESS? Or is it on some lease and will change in a few days? Anyway, now MONITOR returns the 100% confidence level I was expecting and it all works ...for now. We will see I guess!

**Comment by davidhitchins** [comment]
Well I will leave these posts up here as an object lesson. Something I read caused me to think that the private MAC address
shown on the iPhone was the same as the one for Bluetooth. It's the WIFI one I now realise. You have to use hcitool scan command to get the Bluetooth address and this only works if you cycle the bluetooth off then on again.
