### ISSUE TITLE
Monitor doesn’t start on boot

### ISSUE THREAD

**Issue by vamichael** [andrewjfreyer/monitor#205]
When I look at my MQTT logs, I get messages when monitor.sh starts.  The README.MD says monitor starts when the Pi reboots, but I’m not getting any messages when that happens.  From the instructions in the README, I don’t see anything that would make monitor.sh start upon booting, unless that code actually did something to register it to run on startup.

I’m running code on the master branch.

**Comment by vamichael** [comment]
If you run

> sudo nano /etc/rc.local

And add near the end of file, before `exit 0`

    cd /home/pi/monitor
    sudo bash /home/pi/monitor/monitor.sh &

    exit 0

That will start the script.  I don’t know if this is how it should be done....

**Comment by bigbigblue** [comment]
Are you sure it is not starting? In an ssh session, enter the command

service monitor status

this will tell you if monitor is running and will display any messages issued by the monitor service. I have an issue with no mqtt messages being issued, but it usually occurs after it has been running for a while and is accompanied by the message: 

bash[487]: ./support/mqtt: line 134: printf: write error: Broken pipe

suggesting a broken connection to the mqtt broker, however if that happens the monitor script should (I believe) attempt to reconnect. This also only happens on 1 of the 4 instances of monitor I have running.
Could this be your problem too?

**Comment by vamichael** [comment]
I get this

 ```
monitor.service - Monitor Service
   Loaded: loaded (/etc/systemd/system/monitor.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
```

**Comment by vamichael** [comment]
I went ahead and did:

> sudo systemctl enable monitor

and mucked around with `sumo service monitor restart` and it started working.  I changed the root password, so perhaps that might have mucked with things.
