### ISSUE TITLE
MQTT messages not showing up unless mqtt_version is blank

### ISSUE THREAD

**Issue by vamichael** [andrewjfreyer/monitor#207]
What is the function of mqtt_version?  I set it to "eclipsemosquitto" figuring it was just for logging purposes, but unless I leave it blank I won't get any mqtt messages.

**Comment by rourke** [comment]
I know this is pretty late, but for anyone wondering this I think I have the answer. If you run `mosquitto_pub --help` you'll see this:

```
 -V : specify the version of the MQTT protocol to use when connecting.
      Can be mqttv5, mqttv311 or mqttv31. Defaults to mqttv311.
```

I assume only these variables are accepted. Not sure why you want to provide this.
