### ISSUE TITLE
Add mqtt message how long monitor running

### ISSUE THREAD

**Issue by starostin** [andrewjfreyer/monitor#208]
Hi, thanks a lot for this project. It is working very cool. But I want to track how long my monitor already running. I can see this info when run 
```
sudo systemctl status monitor
```

But it would be great to have this info in some mqtt message (I want to add this like a sensor in HA)
Thanks in advance!

**Comment by TheStigh** [comment]
There is a message sent from Monitor with (example): location/office/status which show either offline or online. You could then start a timer in HA from the first time you receive online. Have in mind that you will need to also detect an offline before restarting the timer as Monitor keep sending status messages repeatidly (stutus online).

Just a workaround suggestion :)

**Comment by andrewjfreyer** [comment]
I agree with @TheStigh, I think I'll not incorporate this just to prevent feature creep.
