### ISSUE TITLE
Add trigger for RSSI scanning

### ISSUE THREAD

**Issue by Odianosen25** [andrewjfreyer/monitor#209]
Hello Andrew,

Thanks for this project again. I do use the RSSI for rudimentary area around the house determinations if users, and it’s not bad.

Please I know the RSSI scan starts after a certain predefined internal. This makes sometimes when users move around the house, slow to detect.

I use motion sensors around the house for lights, so thought this same sensors could be used to trigger RSSI scans, so the system could quickly determine where users are. This way one could even reduce the time interval of the internal scan periods.

For now I use arrival scan for RSSI tracking when occupants move around the house. This allows me to put all monitor systems as trigger only, and it helps to update after motion is not detected. Seems to work great.

I am not certain if it’s a bad idea to be using the arrival scan for it, but so far so good been nice. If you think otherwise, please I am asking if a trigger topic can be added like arrival/depart scan, which will just trigger that the system runs RSSI only. 

Thanks and kind regards again

**Comment by TheStigh** [comment]
@Odianosen25 How do you use the RSSI scanning? From the documentation I thought you could only follow one single predefined MAC ?

**Comment by Odianosen25** [comment]
Hello @TheStigh,

Well I paired my devices to each node, and it sends the RSSI readings when I run arrive scans. I got 2 nodes and 3 users and it works great.

It sends the RSSI for each device from both locations and I simply store them.

Regards

**Comment by TheStigh** [comment]
> 
> 
> Hello @TheStigh,
> 
> Well I paired my devices to each node, and it sends the RSSI readings when I run arrive scans. I got 2 nodes and 3 users and it works great.
> 
> It sends the RSSI for each device from both locations and I simply store them.
> 
> Regards

So if you have 5 different locations running Monitor (i.e. office, bedeoom, livingroom, bathroom, garange) you have paired the phone to each of these hardware locations? With pairing - normal pairing as pairing a headset to the phone?

What switch do you then use on Monitor ?
What about devices **not** paired?

**Comment by Odianosen25** [comment]
@TheStigh ,

> So if you have 5 different locations running Monitor (i.e. office, bedeoom, livingroom, bathroom, garange) you have paired the phone to each of these hardware locations? With pairing - normal pairing as pairing a headset to the phone?

Yes you need to pair each device to each location to get the RSSI. There is no way unfortunately as I know, to do it automatically.

> What switch do you then use on Monitor, and how do you run it with multiple mac addresses?
I use `sudo bash monitor.sh -c <mac address>` to pair each device, and yes you have to run it for multiple mac addresses

> What about devices not paired?
Those not paired will not get updated RSSI, and will always report `-99`. Though they will be reported if available or not.

Regards

**Comment by TheStigh** [comment]
> Yes you need to pair each device to each location to get the RSSI. There is no way unfortunately as I know, to do it automatically.
> 

Ok, I've tested by running 'sudo bash monitor.sh -c <mac address>' (my Samsung Tab A). It successfully paired. I've rebooted the RPi and in the reply (logs on MQTT server) I can't see any RSSI data for it (but I do get confidence 100). Do I need to run monitor.sh with a different switch now if I want to see the RSSI data?

**Comment by Odianosen25** [comment]
Hello @TheStigh,

> Ok, I've tested by stopping monitor, running 'sudo bash monitor.sh -c ' (my Samsung Tab A). It successfully paired. I've rebooted the RPi and in the reply (logs on MQTT server) I can't see any RSSI data for it (but I do get confidence 100).

As far as I know, once you pair it, it should report RSSI data. Try being within the same room you have monitor running, And see if any difference within like 5 mins, or if impatient, run arrival scan **only**. Not rebooting the RPi, but only arrival scan.

>I actually get some '/location/kontor/MAC ADDR/rssi' but it is -99, and on all devices with confidence 0.
Devices with confidence 100 I don't get the /MAC ADDR/rssi' at all... Not on the Samsung Tab A either (which is paired).

That's a weird one as far as I know, as you should be getting it. Not sure what's playing there.

>Do I need to run monitor.sh with a different switch now if I want to see the RSSI data?

Well you shouldn't need to, but I run my nodes using `-a` switch. Not sure it helps, but no harm in trying :)

>PS; all devices with confidence 100 are present in my 'known_static_addresses'

Yeah that's how it roles. 

On another note, I have my setup and AppDaemon app on git [here](https://github.com/Odianosen25/Monitor-App). Maybe you will find some answers from what I did, if I am not helping enough now. 

Regards

**Comment by andrewjfreyer** [comment]
Per the FAQ & documentation, this feature exists. You can post a message to `monitor/scan/rssi`
