### ISSUE TITLE
status topic only ever shows offline (correctly), never states online

### ISSUE THREAD

**Issue by Phileep** [andrewjfreyer/monitor#21]
Hi,

Great application.

I am using 0.1.616 (and have noticed this also in earlier versions)

I expected the status topic to publish an online message once connected to the mqtt broker - which I could use to detect health of the connection between monitor and my server. I am not sure if this is by design.

The LWT is working as I get offline status when monitor is stopped ... but I would prefer to not have to assume the status as online and rather read a confirmation in status that the system is online.

Any clarification would be appreciated. 

In any case, if not a bug I propose this as a feature request!

edit: looking at the mqtt module around line 33 it does appear to try and set status. I only see the LWT message set later in the routine. I would assume the LWT should be set in the same publish action anyway (ie post this, if I am gone, post LWT)

edit 2: I would also like to sugest that the status is always posted with retain flag true irrespective of the other topics retain flag. Then, anytime you subscribe from your master system (like homeassistant), the status of the monitor link to mqtt is available.

I would also suggest the environment post should be retained irrespective of other topic retain setting. Agaain, it allows a client that connects to mqtt after a post to gather information about status.

Regards
Phil

**Comment by hmmbob** [comment]
#22 
Should fix the online issue
