### ISSUE TITLE
Losing contact with the MQTT Broker 

### ISSUE THREAD

**Issue by bigbigblue** [andrewjfreyer/monitor#210]
I have 4 instances of the monitor script running, as follows:
**1.** Raspberry Pi3 b+ running Raspbian Stretch - everything works fine
**2.** Raspberry Pi3 b+ running HASSOS / Homeassistant - everything works fine
**3.** Raspberry Pi ZeroW - Running Raspbain Stretch Lite. This works fine until the MQTT broker goes offline. Once the broker goes offline, this instance does not seem to be able to reconnect with the broker.  The (redacted) result of the command 'sudo service monitor status' is shown below:
***************************************** Log Start *************************************
● monitor.service - Monitor Service
   Loaded: loaded (/etc/systemd/system/monitor.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-06-18 17:42:50 BST; 21h ago
 Main PID: 325 (bash)
   CGroup: /system.slice/monitor.service
           ├─ 325 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─ 535 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─ 536 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─ 539 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─ 540 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─ 543 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─ 544 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─ 620 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─ 623 /usr/bin/mosquitto_sub -I Garage -V mqttv311 -v -F %t|%p -q 2 -L mqtt://192.168.123.199 1883 monitor/# --will-topic monitor/Garage/status --will-payload offline
           ├─6444 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─6446 timeout --signal SIGINT 90 stdbuf -oL -eL btmon
           ├─6447 btmon
           ├─6499 sleep 20
           ├─6509 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─6510 timeout --signal SIGINT 60 hcitool -i hci0 lescan
           ├─6511 hcitool -i hci0 lescan
           ├─6551 /bin/bash /home/pi/monitor/monitor.sh -S -r -a -b &
           ├─6553 timeout --signal SIGINT 120 stdbuf -oL -eL hcidump -i hci0 --raw
           └─6554 hcidump -i hci0 --raw

Jun 18 17:42:51 MonitorGarage bash[325]: > removing web request caches
Jun 18 17:42:51 MonitorGarage bash[325]: > logging is disabled, although startup messages will still be shown
Jun 18 17:42:51 MonitorGarage bash[325]: > warning: periodic scan mode may cause interference with 2.4GHz networks if run on a Raspberry Pi
Jun 18 17:42:53 MonitorGarage bash[325]: > warning: for security purposes, please consider changing 'username' in: mqtt_preferences
Jun 18 17:42:53 MonitorGarage bash[325]: > warning: for security purposes, please consider changing 'password' in: mqtt_preferences
Jun 18 17:42:53 MonitorGarage bash[325]: > warning: operating in anonymous and unprotected mode for mqtt broker at 192.168.123.199
Jun 18 17:42:59 MonitorGarage bash[325]: > xx:xx:xx:xx:xx:xx confidence topic: monitor/Garage/xxxxxxxx (has not previously connected to hci0)
Jun 18 17:42:59 MonitorGarage bash[325]: > xx:xx:xx:xx:xx:xx confidence topic: monitor/Garage/xxxxxxxx (has not previously connected to hci0)
Jun 18 17:42:59 MonitorGarage bash[325]: > xx:xx:xx:xx:xx:xx confidence topic: monitor/Garage/xxxxxxxx (has not previously connected to hci0)
Jun 18 17:43:00 MonitorGarage bash[325]: > xx:xx:xx:xx:xx:xx: confidence topic: monitor/Garage/xxxxxxxx (has not previously connected to hci0)
****************************************** Log End  *************************************
issuing the command 'sudo service monitor --full-restart' results in the Last Will message being issued and everything working as normal.

4. Raspberry Pi 2 V1.1 with USB bluetooth adapter. This instance works for several hours and then issues the message: 
bash[393]: ./support/mqtt: line 134: printf: write error: Broken pipe
which suggests it has lost contact with the MQTT broker. Once again issuing a full-restart kicks it back into life.

I could of course use cron to issue the --full-restart commands at regular intervals, but I am not sure if these errors are caused by a bug with monitor and therefore I thought I would report my problems. Any suggestions as to how to fix will be most gratefully received.
Thanks

**Comment by bigbigblue** [comment]
Some further information. I took the SD card out of the Pi ZeroW which has now started failing to provide updates to the MQTT broker after the first 20 minute or so of a boot-up and put it into a RPi3 B+ which has, without any modification to anything on the SD Card, been working perfectly for 6 or so hours. 
I don't know the significance of this, as I lack the skills to do any further debugging, so providing this info for anyone more knowledgeable than me that cares to look into it.
Cheers!

**Comment by andrewjfreyer** [comment]
Thanks for the report!
