### ISSUE TITLE
Very slow detection in departures and arrivals

### ISSUE THREAD

**Issue by tmchow** [andrewjfreyer/monitor#212]
I'm trying to understand how to use this properly.  I have BT MAC addresses added to the `known_static_addresses` file and when monitor service starts, I can see in the logs and MQTT that it's finding those devices and listing their aliases.

However, if i leave the room area and go quite far, I'm seeing it take multiple minutes (sometimes up to 2-3 mnins) for confidence interval values to be in logs of 90 then 45 then 0.

I then tried decreasing the `PREF_BEACON_EXPIRATION` setting from `180` down to `30` but this didn't help.

Once I do see confidence down to zero (e.g. I just shut BT off, then wait the 2-3 mins for it to say confidence=0), then flip BT back on, it can then take multiple minutes again for it to notice the arrival and set a confidence of 100.

what would be causing detecting to be so slow?

**Comment by MikeTheCleric** [comment]
Hi, I've got the same problem with my configuration. When i try to turn off Bluetooth it takes some minutes to set my status to away. I tried to change some parameters in behavior_preferences but nothing changed.
And when the status is correct and I turn on the Bluetooth, it takes 3-4 minutes to return at "home" state.
There's a parameter that i missed?

Thanks in advice for any help.

**Comment by andrewjfreyer** [comment]
Simulating a depart by turning off bluetooth will always be slow because you have to wait for monitor to notice that some random bluetooth device (which *was* associated with your phone) has stopped advertising. That's why most users use `-td` to trigger depart scans with more control.

**Comment by tongaimaramba** [comment]
Hi there related to this question, I'm having issues with slow detection on arrival. Would appreciate some advice how to debug. I have an iPhone which is detected in under 5 seconds, great. And a Pixel 3 which takes 3 minutes to be detected. Both are listed as known devices. Any advice where to look?

**Comment by rccoleman** [comment]
Have you reviewed the logs using `journalctl -u monitor -r` from here?  Try some of the debugging options?

https://github.com/andrewjfreyer/monitor/blob/master/support/README.md
