### ISSUE TITLE
What is "PREF_PASS_FILTER_ADV_FLAGS_ARRIVE" used for?

### ISSUE THREAD

**Issue by tmchow** [andrewjfreyer/monitor#213]
The documentation isn't clear on what `PREF_PASS_FILTER_ADV_FLAGS_ARRIVE` is used for. The docs says "See above" but I’m still not clear on its usage.

**Comment by andrewjfreyer** [comment]
"flags" are a piece of a btle advertisement that give information about the advertisement itself. Some differently-flagged advertisements are sent at different frequencies or at different times, so filtering by flag narrows down more precisely what types of advertisements can be used to trigger an arrive scan.
