### ISSUE TITLE
Monitor 'use cases' questions

### ISSUE THREAD

**Issue by TheStigh** [andrewjfreyer/monitor#215]
Hi @andrewjfreyer and all the other skilled ppl here 👍 

First I must say this looks as the perfect solution for what I want to achieve, and from the readme I see you've done a he** of a job creating this nice script!

I got this up and running on my RPi 3b+ (currently 6 pcs of Zero W on the way by DHL) and got MQTT installed, configured and finally up and running... puuuh...

I'm currently in a steep learning curve regarding both MQTT and Monitor at the same time and also trying to understand the readme correctly. Still, I have some questions which are unclear to me.

1) 
I want to detect **any** MAC address passing a Monitor station to know if and whom was in that particular room. It should detect both mac's from'known_static_addresses' and unknown/guests. Can I do that, and what switch do I need to run Monitor with?

2)
Can I run the script with multiple switches? If yes, how spcifically do I update the script to boot up and run with these switches?

3)
For presence of the family arriving and departing, what switch is best for this? And, can this be combined with question 1 ?

In advance, thanks for taking the time to answer my questions :)

**Comment by andrewjfreyer** [comment]
>I want to detect any MAC address passing a Monitor station to know if and whom was in that particular room. It should detect both mac's from'known_static_addresses' and unknown/guests. Can I do that, and what switch do I need to run Monitor with?

For security/privacy reasons this isn't really possible. Otherwise advertisers would be all over it tracking you through shopping malls and whatnot. Plus, unless you have a huge house with 100' separation between your monitor nodes, you will not receive useful "presence" data. 

>Can I run the script with multiple switches? If yes, how spcifically do I update the script to boot up and run with these switches?

What do you mean by "switch"?
