### ISSUE TITLE
Failed to track TrackR

### ISSUE THREAD

**Issue by CerielRoland** [andrewjfreyer/monitor#216]
Hi there,

I installed the monitor service according to the manual.
If i do a manual search with hci tool I can see the TrackR.
But if I enter the device in known_devices no results are found.

`pi@pi-dsmr:~/monitor $ sudo hcitool  lescan
LE Scan ...
4D:05:DD:22:FD:F4 (unknown)
4D:05:DD:22:FD:F4 (unknown)
58:DD:BE:39:A6:87 (unknown)
58:DD:BE:39:A6:87 (unknown)
FA:72:2D:6D:49:BE tkr
FA:72:2D:6D:49:BE (unknown)
`

`# ---------------------------
FA:72:2D:6D:49:BE tkr
`

`{
  "id": "FA:72:2D:6D:49:BE",
  "confidence": "0",
  "name": "tkr",
  "manufacturer": "Unknown",
  "type": "KNOWN_MAC",
  "retained": "false",
  "timestamp": "Thu Jun 27 2019 09:58:35 GMT+0100 (BST)",
  "version": "0.2.197"
}`

**Comment by andrewjfreyer** [comment]
Is that device a beacon?
