### ISSUE TITLE
BLE blinds no longer work reliably

### ISSUE THREAD

**Issue by CrispinP** [andrewjfreyer/monitor#218]
Hi,

This is not a monitor problem per say but it's started since I started using monitor. Hoping you can help.

I use SOMA blinds (https://uk.somasmarthome.com/) which use BLE to communicate. I use another python script on a different RPi to talk to the blinds. (https://github.com/SkyJohn/Homebridge-SOMA-Smart-Shades)

Within monitor I have added the two mac addresses of the blind controllers to the blacklist file.

How could this interfere with the web blinds python script? could monitor be holding the connection to the device, even though it's in the blacklist? If so, is there a way to shorten this period?
I've got the polling for monitor at 10 minutes. The blinds open and close once a day so clashes are unlikely but do seem to happen.

Thanks for an awesome app!

**Comment by andrewjfreyer** [comment]
What command line settings are you using? You mention a 10 minute interval (-r?), have you tried using mqtt triggers for arrive/depart? 

How close are the two pis together? 

FWIW, blacklisting the blinds probably won’t have any effect.

**Comment by CrispinP** [comment]
Sorry, a dumb question - how do I see the current commandline? I can see -u sets it but can't see a "view" option.

htop shows this though. Normal?
![image](https://user-images.githubusercontent.com/27884877/60919865-b2c7b900-a28e-11e9-9074-b9c76ac0a8e0.png)

re "10 minute interval" - I am referring to this:
`# ---------------------------
#
# BEHAVIOR PREFERENCES
#
# ---------------------------

#MAX RETRY ATTEMPTS FOR ARRIVAL
PREF_ARRIVAL_SCAN_ATTEMPTS=2

#MAX RETRY ATTEMPTS FOR DEPART
PREF_DEPART_SCAN_ATTEMPTS=2

#SECONDS UNTIL A BEACON IS CONSIDERED EXPIRED
PREF_BEACON_EXPIRATION=30

#MINIMUM TIME BEWTEEN THE SAME TYPE OF SCAN (ARRIVE SCAN, DEPART SCAN)
PREF_MINIMUM_TIME_BETWEEN_SCANS=30

#ARRIVE TRIGGER FILTER(S)
PREF_PASS_FILTER_ADV_FLAGS_ARRIVE=".*"
PREF_PASS_FILTER_MANUFACTURER_ARRIVE=".*"

#ARRIVE TRIGGER NEGATIVE FILTER(S)
PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE="NONE"
PREF_FAIL_FILTER_MANUFACTURER_ARRIVE="NONE"
`
No idea why I said 10 minutes..... 😊 

re proximity - they're close to each other - maybe a foot or so. I can try move them apart and see.

Not sure what you mean by the mqtt triggers for depart and arrival. I've got it publishing to mqtt when someone arrives or leaves. Is this what you mean?

![image](https://user-images.githubusercontent.com/27884877/60920391-f7a01f80-a28f-11e9-96bd-e0824a6975a4.png)

The two black listed items are what the blinds controller is trying to talk to.
I've just had an instance of it not working. Seemingly no error from the blinds python (which does not mean it did not error 😄 )

Thanks for the help

**Comment by CrispinP** [comment]
Just thinking - 
I've changed the code slightly of the blinds python. For each call that gets made to it I do the following:
`
def	reset_bt():
	# restart bluetooth
	pd = subprocess.Popen(["/bin/hciconfig", ble_adapter, "down"])
	pd.wait()
	pu = subprocess.Popen(["/bin/hciconfig", ble_adapter, "up"])
	pu.wait()	

`
Could it be that the reset of the ble adaptor creates an arrival scan which monitor then talks to. In that period the adaptor is busy talking to monitor and thus fails accept the call from my python?

**Comment by andrewjfreyer** [comment]
> Could it be that the reset of the ble adaptor creates an arrival scan which monitor then talks to. In that period the adaptor is busy talking to monitor and thus fails accept the call from my python?

Yes. per the faq, monitor's behavior will definitely be impacted (and will impact) other services useing the same bluetooth hardware.
