### ISSUE TITLE
Specify Location when scanning

### ISSUE THREAD

**Issue by Odianosen25** [andrewjfreyer/monitor#220]
Hello,

It will be nice, if `location` could be added to the scan topic.

So like for example instead of just simply `monitor/scan/arrive` or `monitor/scan/depart` as topic, and `""`as payload. It will also accept location as payload, which will only scan if the location is the same.

So basically all nodes respond to `""` and `<its location>` .e.g. `Living Room`. This way nodes can be made to scan specific locations and not triggering all of them at once.

Regards

**Comment by andrewjfreyer** [comment]
You can set a different path for each monitor node, such as `monitor/1`
