### ISSUE TITLE
Only works for a short time after reboot

### ISSUE THREAD

**Issue by unclemonkey77** [andrewjfreyer/monitor#221]
When I first boot/reboot the Pi it accurately reports the confidence % to HA.  If I make a change in the first few minutes (cycle BT on my phone or turn my phone off completely) it might be registered and reported, but anything beyond a minute or two is not registered/logged or reported to HA.  I've noticed this a couple of times, but not often.

[+] 0.2.197 10-07-2019 07:12:02 pm [CMD-MQTT]   warning: network is down. enqueuing command to try again after a delay

It just appears to lock up.  I've wiped and started over and have the same results.

**Comment by onebyside** [comment]
Beta for the win.

**Comment by unclemonkey77** [comment]
> Beta for the win.

Did you have the same issue and get it to work with the beta?  Looks like the beta is older than the master at this point...

**Comment by onebyside** [comment]
I used the beta from the beginning. There is a memory leak as Andrew has stated and  most are restarting the script every 24 hours.
________________________________

**Comment by andrewjfreyer** [comment]
The memory leak have been addressed as of your comment @onebyside - are you still experiencing issues? 

The biggest memory issues were present only for a small handful of users that had non-raspi hardware. Closing for now, given the age of the issue, unless more information can be provided.
