### ISSUE TITLE
Raspberry Pi 4 compatibility

### ISSUE THREAD

**Issue by jmbinette** [andrewjfreyer/monitor#224]
Hi,

This is more a question than an issue : Just received the latest Raspberry Pi 4.

Any improvement or features that we could benefit from bluetooth 5.0?
Is it compatible ?

Thanks

**Comment by Frits1980** [comment]
I wouldn't know why it shouldn't work. The only relative change would be the range of BT5... But if you would create a triangular positioning with rpi zero W's i wouldn't use the rpi4 with that. I would use a rpi with the same BT adapter. And BLE was introduced in BT4 so for the low energy you don't have to do it.

But I would ask you to test if it works if you have a rpi4 at your disposal. So everybody knows if it works or not. Thanks in advance for that, if you would be so kind. :)

**Comment by Shred99** [comment]
Since the OP has turned into a tumbleweed, I'll answer the question.

I've installed Monitor on a Raspberry Pi 4 that I'm using for testing.  It seems to be running well.  The only difference that I'm seeing (and it needs further investigation) is that the Bluetooth range doesn't seem to be as good as the range that I get from my older Raspberry Pi 3 boards.

**Comment by andrewjfreyer** [comment]
@shred99 haha, sorry y’all. Had a kid a few months ago. I’ll get back on track soon.

**Comment by jmbinette** [comment]
Congrats !!

**Comment by Frits1980** [comment]
Congratulations!

**Comment by Shred99** [comment]
Congratulations, Andrew.  I wasn't referring to you, but to the fact that jmbinette hadn't come back to let us know if monitor had worked on their Raspberry Pi 4.

**Comment by andrewjfreyer** [comment]
It should work on the pi 4 just fine, but I doubt we could leverage bluetooth 5 very effectively without major surgery to the app.
