### ISSUE TITLE
previously_connected_devices not filled correctly

### ISSUE THREAD

**Issue by augustjanse** [andrewjfreyer/monitor#225]
**Steps to reproduce**
Install from scratch (`2019-07-10-raspbian-buster-lite.zip`), follow instructions including filling out `mqtt_preferences`, `known_static_addresses` and pairing with `bash monitor.sh -c`. On first run, the script complained that packages `bluez-hcidump` and `bc` were missing, so I installed them.

**Results**

The script runs, but RSSI is only reported for unconnected devices. This is issue #199.

**Source of the problem**
```
previously_connected_devices=$(echo "quit" | bluetoothctl | grep -Eio "Device ([0-9A-F]{2}:){5}[0-9A-F]{2}" | sed 's/Device //gi')
```

[This line](https://github.com/andrewjfreyer/monitor/blob/e22f7a9d859b20f399c4e85d1fe441776af51ed7/monitor.sh#L161) doesn't set the variable:

```
pi@raspberrypi:~ $ echo "quit" | bluetoothctl
[bluetooth]# quit
```

I guess the behavior of `bluetoothctl` was changed?

**Dirty fix**
I just set the variable to a string containing my previously connected device. The script now works as intended. Not sure how to properly fix this problem.

**Comment by andrewjfreyer** [comment]
I’ll investigate. Thanks for the report.

**Comment by neverbethesky** [comment]
> **Dirty fix**
> I just set the variable to a string containing my previously connected device. The script now works as intended. Not sure how to properly fix this problem.

Does your quick and dirty fix apply to monitor.sh that has multiple connected devices for RSSI scanning?

**Comment by augustjanse** [comment]
Didn't try, but IIRC it just scans the string for the wanted MAC, so it should.

**Comment by cameronkelley28** [comment]
Until Andrew is able to review my PR, try changing "quit" to "paired-devices" on line 161.

Would also be good to get some feedback if this resolves the issue for everyone.

[Commit for reference](https://github.com/andrewjfreyer/monitor/pull/253/commits/4c024f32dce8339b0c0420304a7a024df6483b9c)

**Comment by augustjanse** [comment]
I unfortunately won't be able to test this, but nice!

**Comment by gmalbert** [comment]
@augustjanse I made your change, but I'm still only seeing the RSSI on unknown devices.

**Comment by augustjanse** [comment]
@gmalbert I wouldn't know why, sorry. Maybe you should try @cameronkelley28's solution instead.

**Comment by gmalbert** [comment]
@cameronkelley28 unfortunately, this didn't work for me. Thanks for the suggestion, though!

**Comment by cameronkelley28** [comment]
> @cameronkelley28 unfortunately, this didn't work for me. Thanks for the suggestion, though!

What version of bluetoothctl are you running on your pi?
`bluetoothctl - v`

**Comment by gmalbert** [comment]
@cameronkelley28 5.50.

**Comment by cameronkelley28** [comment]
Strange. You've already paired the phone/device to the pi?
