### ISSUE TITLE
Sending an ECHO request on MQTT causes an infinite loop with more than 1 instance

### ISSUE THREAD

**Issue by shbatm** [andrewjfreyer/monitor#226]
If you send an mqtt message to `monitor/echo` and you have more than one monitor node listening, this creates an infinite loop because they all respond to each other's `/echo/ok` message.

**Comment by gieljnssns** [comment]
https://github.com/andrewjfreyer/monitor/issues/198

**Comment by shbatm** [comment]
Closing since this is a duplicate. Thanks, @gieljnssns.
