### ISSUE TITLE
100% CPU usage on Raspberry PI Zero W

### ISSUE THREAD

**Issue by pittbull** [andrewjfreyer/monitor#229]
Hi.

I was able to switch out one of my older mini computers with a new RPI ZW, but I am finding that it is constantly sitting at 100% cpu. Agreed it's a single core 1Ghz, but will monitor eat up all that cpu?

I would've been fine with this but as it is now it delays detection so much that it becomes unusable.

Any advice?

**Comment by pittbull** [comment]
Update:

I've reinstalled with both Buster and Stretch and I have the same problem: Constantly running at 100% cpu, resulting in very slow detection and even multiple detection of the same device.

I have tried '-tda', waited for monitor to settle down and the issue a message to initiate either arrival or departure scan. The first message seem to go unnoticed and when I issue the second depart message it triggers after approx 5 seconds - but then it does two scans. 

I am not able to decode what goes on here, but if somebody has the PiZW I would love to hear your feedback.

**Comment by pittbull** [comment]
Update:

I've installed both Buster and Sketch and the results are the same: delayed scanning and what seems to be multiple detection of the same device. The results seem to differ between restart of the service which leads me to think that my results are due to cpu running at 100%.

Anybody else having issues with the ZW?

**Comment by pittbull** [comment]
Ask and you shall find out yourself: Copied the behavior_preference from my primary scanner and for some reason this triggered a run away cpu. Resetting to the default file normalized the cpu usage.

**Comment by Frits1980** [comment]
Good to hear you solved it. But now I'm curious what the difference in those files were. 🙂

**Comment by pittbull** [comment]
Agreed. I will retry and compare using the old file and report back.

**Comment by pittbull** [comment]
It seem to be related to manipulating the PREF_MINIMUM_TIME_BETWEEN_SCANS which defaults to 15. Reducing this number below 10 seem to spike the cpu and slow down the response.
