### ISSUE TITLE
Little usage help and missing mqtt messages of known devices

### ISSUE THREAD

**Issue by codegrau** [andrewjfreyer/monitor#23]
Hey Andrew, 

I really appreciate your work here. I switched from presence to monitor but right now I don't get it how this is supposed to work. 

I have a lot of different kinds of bluetooth devices (laptops, headsets, ...) but for me it'd be enough to "track" 4 phones. I started from scratch with monitor and just copied the content of known_static_address over to monitor. 

    de:ad:be:ef:fe:ed codegrau 

right after installing and starting monitor service on my raspberries there are like hundreds of mqtt messages on each from unknown bluetooth devices (some of them are my laptops & stuff). 

Maybe you could help me out here, how to use monitor.sh the right way. Do I have to add all these unknown devices to each and every raspberry in my flat? do i have to expect hundreds of mqtt messages for each visitor of my neighbors? Which parameters of monitor.sh are best for simply checking these four phones?

And BTW - I don't even get messages from my devices in known_static_addresses via mqtt... is that how it meant to be?

**Comment by andrewjfreyer** [comment]
No need to add all these unknown devices. The only way you should be seeing *any* mqtt messages is if you have enabled beacon tracking via -b and -g. Even then, "hundreds" must surely be an exaggeration (or a big bug that I haven't discovered yet), as mqtt messages are only posted when a device is seen for the first time, or when a beacon device has exhibited an RSSI change beyond the threshold in your preferences. 

What command line arguments did you supply to the script? If you are just tracking phones, I would recommend using no command line options.

**Comment by codegrau** [comment]
Hi Andrew and thanks for your fast response. It's not hundreds of devices but every few seconds like a dozen MQTT messages. I reinstalled and resetted monitor with:

    sudo bash monitor.sh -d
    sudo bash monitor.sh -f -u (-> openhab MQTT)
    sudo systemctl restart monitor.service 

and still see 6 to 10 devices (GENERIC_BEACONs) every ~30s with slowly dropping confidences from 100 down and rssi between -55 and -100.

Actually I don't have a clue what I'm doing wrong (I do have bluetooth equipment, laptops/macs with bluetooth but I really just don't need that much BT information via MQTT.

**Comment by hmmbob** [comment]
I actually see the same with two devices in my house - I can imagine that
living in a flat would get more messages.

The devices are always the same (same mqtt topic) but may differ in rssi
per mqtt message. They always register as GENERIC BEACON.

Hope this helps.

**Comment by andrewjfreyer** [comment]
Confirmed a stupid bug on my part. Please update to 0.1.620. Using default settings should not show public beacons.

**Comment by hmmbob** [comment]
Works as expected now!
