### ISSUE TITLE
Is possible to make something similar with ESP32 as a BLE sensor?

### ISSUE THREAD

**Issue by carmolim** [andrewjfreyer/monitor#231]
Hello, I loved the project, but I don't have any Pi Zero now, and I was wondering if could be possible to achieve something similar but using multiple ESP32 in my house.

Thanks.

**Comment by andrewjfreyer** [comment]
Not without a port of bash and all the projects dependencies to ESP. I do have a ton of Happy Bubbles around the house, and I’ve been looking into modding the firmware. That’s be a separate project though.
