### ISSUE TITLE
Mqtt is connecting and disconnecting all the time 

### ISSUE THREAD

**Issue by ezraholm50** [andrewjfreyer/monitor#234]
So i'm seeing this in my logs, in a matter of `bash monitor.sh start` and switching to my log on my mqtt server so that would be 3 seconds at best. Could we have it to stay connected to the server?

```
1566327127: New client connected from 192.168.x.x as kitchenble24950 (p2, c1, k60, u'xxx').
1566327127: Client kitchenble24950 disconnected.
1566327128: New connection from 192.168.x.x on port 1883.
1566327128: New client connected from 192.168.x.x as kitchenble24972 (p2, c1, k60, u'xxx').
1566327129: New connection from 192.168.x.x on port 1883.
1566327129: New client connected from 192.168.x.x as kitchenble25007 (p2, c1, k60, u'xxx').
1566327129: Client kitchenble25007 disconnected.
1566327129: New connection from 192.168.x.x on port 1883.
1566327129: New client connected from 192.168.x.x as kitchenble25021 (p2, c1, k60, u'xxxx').
1566327130: Client kitchenble25021 disconnected.
```

**Comment by LintHart** [comment]
I'm seeing the same thing. This is also my first attempt at MQTT so I could be doing something wrong. @ezraholm50 did you get anywhere?

**Comment by ezraholm50** [comment]
Switch to core 2.6 with your esp devices. Fot Tasmota use thehackbox, google it.

**Comment by ezraholm50** [comment]
No, still a present issue.

**Comment by Breakerz** [comment]
The script don't maintain a connection. It's a simple "mosquitto_pub" shell command, so i think each message have to create a new connection.

**Comment by andrewjfreyer** [comment]
@Breakerz is correct. This behavior is normal.
