### ISSUE TITLE
Home Assistant sensor code for RSSI: What is the correct value template

### ISSUE THREAD

**Issue by kaosmagix** [andrewjfreyer/monitor#235]
I configured the RSSI monitor part of Monitor and paired with the Rpi. It shows as if it is monitoring correctly in the output. However I fail to get the Home Assistant sensor to work. Probably because the value template is wrong (I tried several things but just don't know what it should be). Could you help me with the correct value template? This is the current (not working) version I have: 

```
platform: mqtt
state_topic: 'monitor/monitor1/<mac>/rssi'
value_template: '{{ value_json.rssi }}'
unit_of_measurement: 'rssi'
name:  monitor_monitor1_iphone_cristian_rssi
```

Thanks in advance.

**Comment by Breakerz** [comment]
the message of rssi is not in json fomat, just try this :
```
platform: mqtt
state_topic: 'monitor/monitor1/<mac>/rssi'
unit_of_measurement: 'dv'
name:  monitor_monitor1_iphone_cristian_rssi
```

**Comment by gmalbert** [comment]
@kaosmagix how did you "configure the RSSI monitor part"? This section of the readme was unclear to me. Are you just using a -c and connecting to a single bluetooth mac address or something else?

**Comment by andrewjfreyer** [comment]
>Are you just using a -c and connecting to a single bluetooth mac address ~~or something else~~?

First part. Create a connection to your phone that you want to RSSI track once, from the command line. Then spin up monitor as usual and RSSI messages will report.
