### ISSUE TITLE
Broker refusing connection

### ISSUE THREAD

**Issue by calvinmaniac12** [andrewjfreyer/monitor#240]
Trying to get this set up with Cloud MQTT and keep getting the following error: "warning: mqtt broker refused connection - check username, password, and host address" 

I have started the whole process from scratch twice, have the correct username and password, and still cannot have any luck. Suggestions appreciated.

**Comment by calvinmaniac12** [comment]
Spent all day on this...started from scratch again step by step and get following error: "warning: mqtt broker refused connection - check username, password, and host address"

Here is my mqtt_preferences (stars in place of sensitive information).

# ---------------------------
#
# MOSQUITTO PREFERENCES
#
# ---------------------------

# IP ADDRESS OR HOSTNAME OF MQTT BROKER
mqtt_address=***.cloudmqtt.com

# MQTT BROKER USERNAME
mqtt_user=***

# MQTT BROKER PASSWORD
mqtt_password=***

# MQTT PUBLISH TOPIC ROOT 
mqtt_topicpath=monitor

# PUBLISHER IDENTITY 
mqtt_publisher_identity=''

# MQTT PORT 
mqtt_port='*****'

# MQTT CERTIFICATE FILE
mqtt_certificate_path=''

#MQTT VERSION (EXAMPLE: 'mqttv311')
mqtt_version=''

**Comment by mochoandre** [comment]
Did you solve this? I am having the same problem with local mosquito mqtt broker

**Comment by andrewjfreyer** [comment]
Have you been able to successfully communicate with cloud mqtt using the command line?

**Comment by leviathan0001** [comment]
I found myself in the same situation. In my case I had to put brackets in:
mqtt_address='********'
as my password includes special signs. It would not work without it
