### ISSUE TITLE
monitor.sh on HASSIO ?

### ISSUE THREAD

**Issue by done7k** [andrewjfreyer/monitor#249]
I understand due to restriction running any .sh on HASSIO, the RPI with HASSIO can not run the monitor and be MQTT broker at the same time. I mean, there is no way to run this solution where there is only one RPI with HASSIO running. right?

**Comment by michaelblight** [comment]
I got this working, although I have since moved my hassio to a NUC. Have a look at issue #90 which shows what I did.

**Comment by ivanovd** [comment]
I also got it to work by installing HASSIO in a Docker container with the official install script for Raspberry Pi 3.
