### ISSUE TITLE
Correcting HCI error

### ISSUE THREAD

**Issue by hmmbob** [andrewjfreyer/monitor#25]
When running the script from the command line, I often see messages like these:

> 0.1.629 09:39:01 pm [ERROR]     Correcting HCI error: Disable scan failed: Input/output error
> 0.1.629 09:39:11 pm [ERROR]     Correcting HCI error: Invalid device: Network is down

What do they mean? What to do?

**Comment by andrewjfreyer** [comment]
Nothing to do. That’s a note that your Bluetooth hardware is being reset because of an error.

**Comment by robwolff3** [comment]
I also see my log riddled with these
`0.1.667 03:53:50 pm [ERROR]     Correcting HCI error: Disable scan failed: Input/output error
0.1.667 03:54:11 pm [ERROR]     Correcting HCI error: Invalid device: Network is down (x2)
0.1.667 03:54:26 pm [ERROR]     Correcting HCI error: Disable scan failed: Input/output error
0.1.667 03:54:47 pm [ERROR]     Correcting HCI error: Invalid device: Network is down (x2)`

**Comment by andrewjfreyer** [comment]
If you are seeing these errors, it is likely because you have decreased a threshold or time interval too low; your bluetooth hardware is not able to complete its tasks. Consider returning to default options.

**Comment by robwolff3** [comment]
I have not changed any behavior_preferences yet. Are you speaking to any other defaults?

I have two nodes, both standard raspberrypi's. One runs HomeAssistant also and the other runs some other software. The Correcting HCI error's have occurred on both, seem to be at random so far.

> rob@hapi:~/monitor $ cat behavior_preferences
> # ---------------------------
> #
> # BEHAVIOR PREFERENCES
> #
> # ---------------------------
> 
> #DELAY BETWEEN SCANS OF DEVICES
> PREF_INTERSCAN_DELAY=3
> 
> #DETERMINE HOW OFTEN TO CHECK FOR A DEPARTED DEVICE OR AN ARRIVED DEVICE
> PREF_CLOCK_INTERVAL=15
> 
> #DEPART SCAN INTERVAL
> PREF_DEPART_SCAN_INTERVAL=90
> 
> #ARRIVE SCAN INTERVAL
> PREF_ARRIVE_SCAN_INTERVAL=45
> 
> #MAX RETRY ATTEMPTS FOR ARRIVAL
> PREF_ARRIVAL_SCAN_ATTEMPTS=2
> 
> #MAX RETRY ATTEMPTS FOR DEPART
> PREF_DEPART_SCAN_ATTEMPTS=4
> 
> #DETERMINE NOW OFTEN TO REFRESH DATABASES TO REMOVE EXPIRED DEVICES
> PREF_DATABASE_REFRESH_INTERVAL=35
> 
> #PERIOD AFTER WHICH A RANDOM BTLE ADVERTISEMENT IS CONSIDERED EXPIRED
> PREF_RANDOM_DEVICE_EXPIRATION_INTERVAL=45
> 
> #AMOUNT AN RSSI MUST CHANGE (ABSOLUTE VALUE) TO REPORT BEACON AGAIN
> PREF_RSSI_CHANGE_THRESHOLD=10
> 
> #BLUETOOTH ENVIRONMENTAL REPORT FREQUENCY
> PREF_ENVIRONMENTAL_REPORT_INTERVAL=300
> 
> #SECONDS UNTIL A BEACON IS CONSIDERED EXPIRED
> PREF_BEACON_EXPIRATION=145
> 
> #SECONDS AFTER WHICH A DEPARTURE SCAN IS TRIGGERED
> PREF_PERIODIC_FORCED_DEPARTURE_SCAN_INTERVAL=240
> 
> #PREFERRED HCI DEVICE
> PREF_HCI_DEVICE='hci0'
> 
> #COOPERATIVE DEPARTURE SCAN TRIGGER THRESHOLD
> PREF_COOPERATIVE_SCAN_THRESHOLD=25
> 
> #MINIMUM TIME BEWTEEN THE SAME TYPE OF SCAN (ARRIVE SCAN, DEPART SCAN)
> PREF_MINIMUM_TIME_BETWEEN_SCANS=15
> 
> #SHOULD REPORT START/END OF KNOWN DEVICE SCANS
> PREF_MQTT_REPORT_SCAN_MESSAGES=false

**Comment by andrewjfreyer** [comment]
Is either pi running any other bluetooth software at all?

**Comment by robwolff3** [comment]
I dont believe so. I was not using bluetooth for anything prior to monitor. I was going to remove presence just to be safe from conflicts.

**Comment by Unthred** [comment]
I too am getting such errors on a fresh install with nothing else running and using the default behaviours
still seems to be working though

**Comment by kuifje123** [comment]
I also have the same errors, approx. each 35 seconds.
I am also using the default preferences.

**Comment by nudded** [comment]
same errors on clean install on pi zero W

**Comment by isabellaalstrom** [comment]
Also getting these on a clean install on rpi zero. Monitor stops working after them until restart. I "solved" it with running a cronjob to restart periodically.

**Comment by kuifje123** [comment]
At my Raspberry PI these errors went away when I did not use Wifi anymore, but instead used fixed ethernet.

**Comment by jimbroze** [comment]
> 
> 
> At my Raspberry PI these errors went away when I did not use Wifi anymore, but instead used fixed ethernet.

I have the same issue but have Wifi disabled

**Comment by andrewjfreyer** [comment]
Are you running beta or master?

**Comment by jimbroze** [comment]
I'm running master

**Comment by andrewjfreyer** [comment]
I'd switch to beta for more stability for the short term. These errors are normal for many installs but they are substantially reduced in the beta branch. I hope to merge the beta with master in the next month.
