### ISSUE TITLE
Noob question: How to run monitor.sh in background

### ISSUE THREAD

**Issue by vikdb** [andrewjfreyer/monitor#252]
So i followed the whole tutorial and i got everything to work, but from the moment i close my ssh session it stops working.. 

So i must run it in the background of my pi zero?

Sry for the beginner question!!

**Comment by gieljnssns** [comment]
```sudo systemctl start monitor```
or reboot your raspberry pi

**Comment by vikdb** [comment]
Let me test it this evening!

Is this common knowledge? Because i dont see any reference in the install guide
