### ISSUE TITLE
iPhone 6s confidence unavailable

### ISSUE THREAD

**Issue by jarekpelczynski** [andrewjfreyer/monitor#259]
I have the Monitor installed on Raspberry Pi 3B+ and I have an issue with iPhone 6s - Confidence is unavailable, but another iPhone (Xs) has Confidence correctly displayed. 

Is it an issue with Bluetooth 4.2?

**Comment by gieljnssns** [comment]
Have you paired your iPhone with some bluetooth device?

**Comment by jarekpelczynski** [comment]
hmmm this iPhone 6s it isn't

**Comment by gieljnssns** [comment]
Many phones will only broadcast once they have already connected to at least one other Bluetooth device. Connect to a speaker, a car, a headset, or monitor.sh -c [address] and try again.

**Comment by jarekpelczynski** [comment]
I will try. Thanks for the clarification.

**Comment by gieljnssns** [comment]
@jarekpelczynski 
Did you get it working?

**Comment by andrewjfreyer** [comment]
@gieljnssns advice is correct here, the phone needs to pair with a bluetooth device before it will respond to name requests.
