### ISSUE TITLE
Having some trouble getting Mosquitto to load

### ISSUE THREAD

**Issue by DolfLund** [andrewjfreyer/monitor#261]
`pi@raspberrypi:/etc/apt/sources.list.d $ sudo apt-get install -f libmosquitto-dev mosquitto mosquitto-clients libmosquitto1
Reading package lists... Done
Building dependency tree
Reading state information... Done
libmosquitto-dev is already the newest version (1.6.7-0mosquitto1~stretch1).
libmosquitto1 is already the newest version (1.6.7-0mosquitto1~stretch1).
mosquitto is already the newest version (1.6.7-0mosquitto1~stretch1).
mosquitto-clients is already the newest version (1.6.7-0mosquitto1~stretch1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
N: Ignoring file 'mosquitto-stretch.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
Do you want to continue? [Y/n] y
Setting up mosquitto (1.6.7-0mosquitto1~stretch1) ...
Job for mosquitto.service failed because a fatal signal was delivered to the control process.
See "systemctl status mosquitto.service" and "journalctl -xe" for details.
invoke-rc.d: initscript mosquitto, action "start" failed.
● mosquitto.service - Mosquitto MQTT v3.1/v3.1.1 Broker
   Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Tue 2019-11-19 05:40:20 GMT; 163ms ago
     Docs: man:mosquitto.conf(5)
           man:mosquitto(8)
  Process: 3377 ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf (code=killed, signal=SEGV)
 Main PID: 3377 (code=killed, signal=SEGV)

Nov 19 05:40:20 raspberrypi systemd[1]: mosquitto.service: Service RestartSec=100ms expired, scheduling restart.
Nov 19 05:40:20 raspberrypi systemd[1]: mosquitto.service: Scheduled restart job, restart counter is at 1.
Nov 19 05:40:20 raspberrypi systemd[1]: Stopped Mosquitto MQTT v3.1/v3.1.1 Broker.
dpkg: error processing package mosquitto (--configure):
 installed mosquitto package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 mosquitto
E: Sub-process /usr/bin/dpkg returned an error code (1)

So I've tried the last step in setting up Mosquitto on a Raspian lite (not Jessie) install (PiZero)

Not sure how to get past this step.  Thanks for any assistance

**Comment by onebyside** [comment]
I never had the problem but you'll find info concerning that problem in the comments. I believe there are probs with 1.6.7, you may have to downgrade some of the mosquitto components.

https://community.home-assistant.io/t/monitor-reliable-multi-user-distributed-bluetooth-occupancy-presence-detection/68505

**Comment by bsmeding** [comment]
same problem on new PI Zero with Rasbian 

try to remove the installed packages and reinstall with mosquitto version 1.6.4-0mosquitto1~stretch1

`
sudo apt remove libmosquitto1 libmosquitto-dev mosquitto-clients mosquitto

sudo apt autoremove

sudo apt install libmosquitto1 libmosquitto-dev mosquitto-clients mosquitto=1.6.4-0mosquitto1~stretch1
`

also we aware that /etc/mosquitto/mosquitto.conf exist (can be empty file for defaults)

**Comment by DolfLund** [comment]
@bsmeding your guidance was spot on, thank you for the instructions.  I am entirely past that hurdle and can now get monitor.sh to load.
