### ISSUE TITLE
Can Monitor scan for and identify by UUID?

### ISSUE THREAD

**Issue by DolfLund** [andrewjfreyer/monitor#262]
I am attempting to track cars as they park in my garage (detached 2 car structure).  I chose a Gimbal Series 22 beacon that is iBeacon compatible for tracking as it has long battery life and good signal.  Unfortunately the MAC address is not static even in iBeacon mode, even though the UUID is.  (ID + major and minor).  Is it possible to give monitor the UUID instead of MAC? I think that these devices are meant for identification in the reverse of my plan (identifying a location to a scanner, as opposed to identifying a visitor) - I'm wondering if this means it isn't the right device for use in my plan.  Also I'm not certain if Monitor is even seeing it from the output I'm getting from watching Monitor.sh

Thanks for any thoughts

**Comment by andrewjfreyer** [comment]
Yes, for iBeacons `monitor` reports the UUID in addition to the current mac address. Use the `-b` flag to report beacon advertisements.
