### ISSUE TITLE
Unable to install Mosquitto On buster

### ISSUE THREAD

**Issue by ttsk8r** [andrewjfreyer/monitor#263]
`pi@raspberrypi:/etc/apt/sources.list.d $ sudo apt-get install -f libmosquitto-dev mosquitto mosquitto-clients libmosquitto1
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libev4 libuv1 libwebsockets8
Suggested packages:
  apparmor
The following NEW packages will be installed:
  libev4 libmosquitto-dev libmosquitto1 libuv1 libwebsockets8 mosquitto
  mosquitto-clients
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 613 kB of archives.
After this operation, 1,331 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://raspbian.mirrors.lucidnetworks.net/raspbian buster/main armhf libev4 armhf 1:4.25-1 [34.5 kB]
Get:2 http://raspbian.mirrors.lucidnetworks.net/raspbian buster/main armhf libuv1 armhf 1.24.1-1 [96.7 kB]
Get:3 http://raspbian.mirrors.lucidnetworks.net/raspbian buster/main armhf libwebsockets8 armhf 2.0.3-3 [85.6 kB]
Get:4 https://repo.mosquitto.org/debian stretch/main armhf libmosquitto1 armhf 1.6.7-0mosquitto1~stretch1 [71.0 kB]
Get:5 https://repo.mosquitto.org/debian stretch/main armhf libmosquitto-dev armhf 1.6.7-0mosquitto1~stretch1 [62.3 kB]
Get:6 https://repo.mosquitto.org/debian stretch/main armhf mosquitto armhf 1.6.7-0mosquitto1~stretch1 [174 kB]
Get:7 https://repo.mosquitto.org/debian stretch/main armhf mosquitto-clients armhf 1.6.7-0mosquitto1~stretch1 [89.0 kB]
Fetched 613 kB in 2s (269 kB/s)
Selecting previously unselected package libev4:armhf.
(Reading database ... 39966 files and directories currently installed.)
Preparing to unpack .../0-libev4_1%3a4.25-1_armhf.deb ...
Unpacking libev4:armhf (1:4.25-1) ...
Selecting previously unselected package libmosquitto1:armhf.
Preparing to unpack .../1-libmosquitto1_1.6.7-0mosquitto1~stretch1_armhf.deb ...
Unpacking libmosquitto1:armhf (1.6.7-0mosquitto1~stretch1) ...
Selecting previously unselected package libmosquitto-dev:armhf.
Preparing to unpack .../2-libmosquitto-dev_1.6.7-0mosquitto1~stretch1_armhf.deb ...
Unpacking libmosquitto-dev:armhf (1.6.7-0mosquitto1~stretch1) ...
Selecting previously unselected package libuv1:armhf.
Preparing to unpack .../3-libuv1_1.24.1-1_armhf.deb ...
Unpacking libuv1:armhf (1.24.1-1) ...
Selecting previously unselected package libwebsockets8:armhf.
Preparing to unpack .../4-libwebsockets8_2.0.3-3_armhf.deb ...
Unpacking libwebsockets8:armhf (2.0.3-3) ...
Selecting previously unselected package mosquitto.
Preparing to unpack .../5-mosquitto_1.6.7-0mosquitto1~stretch1_armhf.deb ...
Unpacking mosquitto (1.6.7-0mosquitto1~stretch1) ...
Selecting previously unselected package mosquitto-clients.
Preparing to unpack .../6-mosquitto-clients_1.6.7-0mosquitto1~stretch1_armhf.deb ...
Unpacking mosquitto-clients (1.6.7-0mosquitto1~stretch1) ...
Setting up libmosquitto1:armhf (1.6.7-0mosquitto1~stretch1) ...
Setting up libev4:armhf (1:4.25-1) ...
Setting up mosquitto-clients (1.6.7-0mosquitto1~stretch1) ...
Setting up libuv1:armhf (1.24.1-1) ...
Setting up libmosquitto-dev:armhf (1.6.7-0mosquitto1~stretch1) ...
Setting up libwebsockets8:armhf (2.0.3-3) ...
Setting up mosquitto (1.6.7-0mosquitto1~stretch1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/mosquitto.service → /lib/systemd/system/mosquitto.service.
Job for mosquitto.service failed because a fatal signal was delivered to the control process.
See "systemctl status mosquitto.service" and "journalctl -xe" for details.
invoke-rc.d: initscript mosquitto, action "start" failed.
● mosquitto.service - Mosquitto MQTT v3.1/v3.1.1 Broker
   Loaded: loaded (/lib/systemd/system/mosquitto.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Wed 2019-11-27 05:41:57 GMT; 139ms ago
     Docs: man:mosquitto.conf(5)
           man:mosquitto(8)
  Process: 1018 ExecStart=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf (code=killed, signal=SEGV)
 Main PID: 1018 (code=killed, signal=SEGV)

Nov 27 05:41:57 raspberrypi systemd[1]: mosquitto.service: Service RestartSec=100ms expired, scheduling restart.
Nov 27 05:41:57 raspberrypi systemd[1]: mosquitto.service: Scheduled restart job, restart counter is at 1.
Nov 27 05:41:57 raspberrypi systemd[1]: Stopped Mosquitto MQTT v3.1/v3.1.1 Broker.
dpkg: error processing package mosquitto (--configure):
 installed mosquitto package post-installation script subprocess returned error exit status 1
Processing triggers for systemd (241-7~deb10u2+rpi1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+rpi1) ...
Errors were encountered while processing:
 mosquitto
E: Sub-process /usr/bin/dpkg returned an error code (1)
pi@raspberrypi:/etc/apt/sources.list.d $
`

**Comment by Breakerz** [comment]
Dont use the mosquitto repo.

´´´cd /etc/apt/sources.list.d/
sudo rm mosquitto-stretch.list
sudo apt update
´´´
and try to reinstall the mosquitto package.

The version of mosquitto comming with buster seem to be fuctionnal with this script.

**Comment by MrGMan133** [comment]
That didn't work, I have the same error on a raspberry pi zero w v1.1.

**Comment by ivanovd** [comment]
Use the buster list, not the stretch one. That worked for me.
