### ISSUE TITLE
CPU load - varies depending on type of usb dongle

### ISSUE THREAD

**Issue by krambriw** [andrewjfreyer/monitor#270]
Hello Andrew,
You monitor solution works really great for me in general I must say. I have 3 RPi3's with external usb BLE dongles running monitor ver 0.2.197. I am controlling scans via commands and all of them are able to detect my iPhone leaving/entering very well

In two of them I have ASUS dongles and in the third a Trust dongle. The CPU load in those with ASUS varies around 5-10% but in the one with Trust it is 35-80%

Swopping dongles and the CPU load moves to respective RPi as well

Turning off monitor and the CPU load drops down to almost 0%, the same in all RPi's

Is there any particular reason for this? Could it be the Trust dongle miss some required service?

Kind regards, Walter

**ASUS:**
hci0:   Type: BR/EDR  Bus: USB
        BD Address: 5C:F3:70:91:AE:52  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING
        RX bytes:184032 acl:0 sco:0 events:5241 errors:0
        TX bytes:10644 acl:0 sco:0 commands:864 errors:0
        Features: 0xbf 0xfe 0xcf 0xfe 0xdb 0xff 0x7b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH SNIFF
        Link mode: SLAVE ACCEPT
        Name: 'wkattic'
        Class: 0x000000
        Service Classes: Unspecified
        Device Class: Miscellaneous,
        HCI Version: 4.0 (0x6)  Revision: 0x1000
        LMP Version: 4.0 (0x6)  Subversion: 0x220e
        Manufacturer: Broadcom Corporation (15)

**Trust:**
hci0:   Type: Primary  Bus: USB
        BD Address: 00:1A:7D:DA:71:06  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING
        RX bytes:163549716 acl:0 sco:0 events:4681163 errors:0
        TX bytes:24385 acl:0 sco:0 commands:1892 errors:0
        Features: 0xff 0xff 0x8f 0xfe 0xdb 0xff 0x5b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH HOLD SNIFF PARK
        Link mode: SLAVE ACCEPT
        Name: 'raspberrypi'
        Class: 0x480000
        Service Classes: Capturing, Telephony
        Device Class: Miscellaneous,
        HCI Version: 4.0 (0x6)  Revision: 0x22bb
        LMP Version: 4.0 (0x6)  Subversion: 0x22bb
        Manufacturer: Cambridge Silicon Radio (10)

**Comment by andrewjfreyer** [comment]
Yes, this is a known issue and outside of the control of `monitor` unfortunately. The root cause is that some USB dongles do not automatically filter duplicate advertisements and, as a result, `monitor` gets quickly overwhelmed with a completely full queue.
