### ISSUE TITLE
Problem with RSSI report on Rpi3B+ and Raspbian Buster

### ISSUE THREAD

**Issue by guffman** [andrewjfreyer/monitor#271]
Can't get a RSSI report from a paired iPhone on Rpi3B+ and stock Raspbian Buster. Same config works fine on Rpi3B+ running stock Raspbian Stretch. Any ideas?

**Comment by gadric** [comment]
#253 This helped me to fix my rssi problem.

**Comment by andrewjfreyer** [comment]
The PR has been incorporated. Thanks!
