### ISSUE TITLE
Not getting updates of devices

### ISSUE THREAD

**Issue by codeclinic** [andrewjfreyer/monitor#272]
If I run `sudo bash monitor.sh` I get output that shows that my device detected with a confidence of 100. However if I then disable Bluetooth or move the device out of range, I don't see any updates to show that the device is no longer detected. I'm expecting monitor to report the device with a confidence of 0 but that isn't happening.

Similarly if I run the script with the device out of range I get confidence 0, but if I move the device within range I don't get any further output to give any sort of confidence let alone one showing above 0.

My expectation is that there should be some output (commandline & MQTT) to indicate this change in presence, whether that be 0 > 100 or vice versa. I have to keep firing off `sudo bash monitor.sh` to get any updates. Essentialy the script only seems to be checking for known devices immediately upon starting the script even with the monitor service running in the background.

Heres an example from my log file:

Jan 01 14:36:56 Garage-Pi bash[21627]: [+] 0.2.197 01-01-2020 02:36:56 pm [CMD-RSSI]        PUBL FA:B4:6A:C8:E9:xx RSSI: -94 dBm (initial reading | 106 dBm)
Jan 01 14:30:41 Garage-Pi bash[21627]: [+] 0.2.197 01-01-2020 02:30:41 pm [CMD-RSSI]        PUBL 88:11:96:57:5A:xx RSSI: -92 dBm (initial reading | 108 dBm)
Jan 01 14:29:28 Garage-Pi bash[21627]: [+] 0.2.197 01-01-2020 02:29:28 pm [CMD-NAME]        48:59:A4:94:56:xx xxxxxx-yyyyy-mobile  zte corporation
Jan 01 14:29:27 Garage-Pi bash[21627]: [+] 0.2.197 01-01-2020 02:29:27 pm [CMD-MQTT]        monitor/garage-pixxxxxx-yyyyy_mobile { ... confidence : 0 ... }
Jan 01 14:28:59 Garage-Pi bash[21627]: > 48:59:A4:94:56:xx confidence topic: monitor/garage-pi/xxxxxx-yyyyy-mobile (has not previously connected to hci0)
Jan 01 14:28:55 Garage-Pi bash[21627]: > warning: variable mqtt_port does not appear in mqtt_preferences. using default port 1883.
Jan 01 14:28:55 Garage-Pi bash[21627]: > removing web request caches
Jan 01 14:28:55 Garage-Pi bash[21627]: > starting monitor.sh (v. 0.2.197)...
Jan 01 14:28:54 Garage-Pi bash[21627]: ===================================================
Jan 01 14:28:54 Garage-Pi bash[21627]:               *** BETA/DEV BRANCH ***
Jan 01 14:28:54 Garage-Pi bash[21627]: ===================================================
Jan 01 14:28:54 Garage-Pi systemd[1]: Started Monitor Service.

Presumably, I'm missing something so any pointers would be appreciated.

Note: I tried this with the latest release and the beta branch without any perceived difference.

**Comment by codeclinic** [comment]
I think I've resolved this after reading everything in the readme file including the Home assistant section. It's not actually that clear for new users as to how to set this up.

**Comment by gmalbert** [comment]
I have similar questions. What in the readme file helped it make sense to you?

**Comment by codeclinic** [comment]
Essentially reading part of the readme and faq sections. Honestly it's still not entirely clear but I at least now understand that a known device doesn't get detected as having left range unless you setup some triggger to do a depart scan.

**Comment by gmalbert** [comment]
@codeclinic oh! I didn't read that correctly in the documentation either. Requiring the departure/arrival scan makes sense. Thank you!

**Comment by codeclinic** [comment]
Personally, I don't think the readme is too newb friendly, and I'm still figuring things out myself, So, I'm by no means sure that I have this set-up properly yet. But I'll try and help improve the readme/instruction if I can once I've got my own setup running properly.
