### ISSUE TITLE
How do I run at boot with flag?

### ISSUE THREAD

**Issue by codeclinic** [andrewjfreyer/monitor#273]
I notice in your Home Assistant section of the readme you mention launching monitor with the -b argument. How do I go about have monitor run automatically at boot with this or any other argument?

Thanks.

**Comment by andrewjfreyer** [comment]
You can update the systemctl script by setting all of your preferred arguments and adding the `-u` flag.

**Comment by codeclinic** [comment]
Thanks, I'll have a look at that.
