### ISSUE TITLE
Hardware recommendations?

### ISSUE THREAD

**Issue by alderete** [andrewjfreyer/monitor#275]
It would be really nice to have some more details about recommended hardware, and how to set it up physically in your home. A little guidance would go a long way. Questions I have include:

 - Recommended hardware (Raspberry Pi W is fine)
 - Recommended physical protection (mountable case)
 - Recommended placement
 - Recommended power methods

Note that what I'm after is, here's an easy, clean-looking solution, here's a super-low power solution, here's the most hidden solution.

What I'd _really_ like would be the smallest possible self-contained box/module that can be plugged directly into an outlet in a convenient location.

My goal really is, what's something simple and nice, clean-looking, that a person new to Home Assistant, and DIY RPi, can easily grasp and know they're doing it right.

(Note: I'm a tech writer. If you wanted a partner in writing something up, and can provide the basic details, I'm happy to put in work here. A more than fair trade for the technical details, for me!)

**Comment by andrewjfreyer** [comment]
> What I'd really like would be the smallest possible self-contained box/module that can be plugged directly into an outlet in a convenient location.

That's likely a raspberry pi zero w. Certainly something like `monitor` could be ported to ESP or similar, but from a consumer level the pi is probably the cheapest and most turnkey solution.
