### ISSUE TITLE
Check per room

### ISSUE THREAD

**Issue by skycryer** [andrewjfreyer/monitor#279]
Is it possible to use monitor on different Rasperry in every room to check by signal strength in wich room the device is? I have seen in sudo /bin/bash monitor.sh it show also a db value, I think that is a signal strength, correct? Can we get that info into Home Assistant for example to get room presence with this value?

**Comment by andrewjfreyer** [comment]
Yes, you can set up one monitor node per room. 

Yes, you can set up RSSI detection for each room. 

No, room presence will not be reliable. Lots of folks (including me) have tried and failed to use bluetooth RSSI as a proxy for distance to or from a given node. The error in that measurement is simply too high to be useful. My best success was using a *long* rolling average of RSSI values, and even then the best I got was +- 10m. That's not quite enough to distinguish between rooms, and it's certainly not quick; the rolling average I used was 3 minutes (I think). 

Some sophisticated trained ML model *might* be able to get better detection, but in my opinion, bluetooth signal strength is simply not granular enough to reliably serve as a proxy for distance or proximity.
