### ISSUE TITLE
How are options set

### ISSUE THREAD

**Issue by borpin** [andrewjfreyer/monitor#28]
Just installed Monitor on a DietPi Image (if you have not tried it you should) - it looks really good.

However, how do I set options for the running service?  I can see that there is a preferences file (needs a bit more explanation of each preference IMHO) and I have set the heartbeat preference via that file (note this preference is not in the template file as it is a recent addition I suspect).

Is this the right way to do it?  Running the bash script from the command line with an option, just seems to run monitor interactively.

**Comment by spelliott7** [comment]
I just installed and had the same question as 'borpin'.  I'll follow this thread for that. 

For the record this is pretty damn slick, I've been looking for this functionality for a while. Strapping beacons to everything wasn't realistic for me, and there wasn't any one program that just addressed the phone BLE like this.  Thank you Andrew for sharing.

**Comment by andrewjfreyer** [comment]
Added a 'getting started' section to the Readme. Let me know if this helps. I'll be adding more detail to this section as time goes on.
