### ISSUE TITLE
Installation / Setup Clarification

### ISSUE THREAD

**Issue by mdframe** [andrewjfreyer/monitor#283]
I am prepping to install the Pi Zero into my Home Assistant network per the instructions here.  I have not performed the installation at this time so I apologize if this is clearly identified during the process.  I am trying to understand how the Pi Zero and my Home Assistant become connected.    I believe the mqtt_preferences file will be pointing to my mosquito instance on Home Assistant but I wanted to make sure I understood this prior to performing the install. 

Thank you and your patience is appreciated for this noobie implementation!

Matt

**Comment by andrewjfreyer** [comment]
> I believe the mqtt_preferences file will be pointing to my mosquito instance on Home Assistant but I wanted to make sure I understood this prior to performing the install.

Yup. That's it.
