### ISSUE TITLE
Implementing a 1 user identify  (example: toilet, bathroom, etc)

### ISSUE THREAD

**Issue by roelbroersma** [andrewjfreyer/monitor#284]
Hello,

I am using KNX and part of the KNX community.  However, I've done quite some things with ESP's, Arduino's and PI's.

I (and I hear the request from a few other people) are looking for the following use case:

- You enter the Toilet.
- A normal Infrared presence detector switches on the light and sends out a 'request' to the Bluetooth Gateway (Pi with monitor script),   it answers with  "1" mac-address and an RSSI.  The answer is the BEST RSSI of all.   (maybe it even does a request with a certain minimum RSSI level).
- We now know who entered the Toilet and so we know which Playlist (shuffle) to Start on the SONOS speakers :)

Other use case:  A user enters the bathroom.  The woman always wants the floor heating on, mirror heating on,  and the toilet seat at 37 degrees Celcius.     The man doesn't care but always wants to have a welcome with a random AC/DC song ;)

In the above cases,  all people (man, woman and 3 children) are at the house and in reach of the Bluetooth Gateway.

I am looking at the best way to implement this.  Maybe a fork of the monitor script in which I do a small modification or  an extra option in the existing script.. ?

Kind regards,
Roel Broersma

**Comment by andrewjfreyer** [comment]
Per many other comments here and on the HA forum, RSSI is simply not reliable enough for something like this. Perhaps you could achieve 70% accuracy based on triggering RSSI scanning with a presence sensor, but you won't approach 100% - especially if your bathroom is a normal size. This before we consider whether everyone carrys their phone with them when the plan to shower.

**Comment by roelbroersma** [comment]
I don't need 100% RSSI Accurracy.   I just need to know WHO is in (i.e.) the Kitchen.   Is it the man or the woman ?    offcourse when both are in the kitchen, that's another story..
So when the woman is in the Kitchen, her RSSI is always higher than then man who is in the Living room,   isn't it ?  (assume the Pi+monitor script is in the Kitchen)

As soon as someone enters the kitchen, I want to Start a Scan. It will report back the one with the best RSSI.    The MAC address from the man and the MAC address from the woman will be in the known_addresses list.
For the rest I will never start a scan.  Not after a specific time,  not when entering the house or leaving the house.   The difference is that I don't use it as a presence detection in the whole house,  but as a specific presence detection in a room.

**Comment by roelbroersma** [comment]
I looked at the script,  because I thought there might be a simple way to achieve this:

After I initiate a scan, I just want to report back 1 MQTT message instead of 5 or 6.  And that 1 MQT message should be the one with the Best RSSI.

So I thought:  Before sending the MQTT message, I'll just SORT the Array on best RSSI and report only the first row of the array.   However, I see in the script that it send directly to the pipe...  not to an array which I can sort...    Would it be an idea to capture the MQTT results in an array too?   So then we can sort it.. and send only 1 out.. ?   (reset the array after each scan)

**Comment by roelbroersma** [comment]
I understand from the issues here that RSSI is not reliable,  but I don't see any   dBm/rssi/distance algorithm/formula in the script.  When only the rssi is reported and nothing is done with that value,  that value in itself is not reliable for distance,  it depends per vendor, per dbm, etc...   However,  that's another issue.      My issue is about reporting only 1 device with the best RSSI  after we request it. (so it scans when we request it)

**Comment by andrewjfreyer** [comment]
If the value itself is not reliable, there's not much purpose in trying to leverage it as a proxy for anything. There is simply too much variability to trust any one measurement. RSSI measurements can vary by 100% without the end user changing position at all.  That's the problem. If you can't reliably tell the difference between 5ft and 50ft, room presence is not an option.

The best option, which isn't particularly attractive, is to have a large number of nodes all feeding data into a single analysis system that takes long running averages and attempts to predict a general physical location based on sets of data. Single nodes returning RSSI values are not good enough for anything meaningful.

If you want to request rssi, I'm sure you've seen that `monitor` already includes an mqtt instruction for that purpose. It's up to you to filter out which `monitor` node has the smallest RSSI. It'd be trivial in homeassistant (my home data aggregator of choice).
