### ISSUE TITLE
Service Execution Verification

### ISSUE THREAD

**Issue by mdframe** [andrewjfreyer/monitor#285]
Should I see this many instances executing of the monitor.sh service?   Just making sure I didn't cause an issue with running the install several times to get all packages loaded on the Pi.  I am seeing very slow response with my beacons so just validating the setup.

![monitor_status](https://user-images.githubusercontent.com/39965710/72669136-593e0500-39fc-11ea-8b48-8050fa02ab73.JPG)

Thx

**Comment by andrewjfreyer** [comment]
It appears that you do have at least one duplicated instance. The script tries to intelligently kill processes when it spins up, but in some cases that doesn't work. The easiest thing to do is to restart your pi or to run a killall command.

**Comment by mdframe** [comment]
This is immediately after restarting... still a high number?  I have issues logging in right after startup and CPU is staying at 100%.  This is a brand new device and just installed monitor which is all this device is performing.  Thoughts to correct?

![monitor_reboot](https://user-images.githubusercontent.com/39965710/72672763-6aebd080-3a2d-11ea-8373-e92114d832fd.JPG)

**Comment by mdframe** [comment]
I turned off the ipv6 interface and the CPU and system is much more responsive now.  Not sure why this would have caused issues however it definitely resolved my login and ssh session performance issues.
