### ISSUE TITLE
MQTT bash error

### ISSUE THREAD

**Issue by jmbinette** [andrewjfreyer/monitor#286]
Hi,

In my journalctl logs i get the following error :

>  bash[537]: [63B blob data]
 bash[537]: [63B blob data]
 bash[537]: ./support/mqtt: line 134: printf: `w': invalid format character

The line is : 
#PRINT THE INSTRUCTION BACK TO THE MAIN THREAD
printf "MQTT$instruction\n" > main_pipe

Any ideas ?

**Comment by andrewjfreyer** [comment]
Looks like it might be a special character in an MQTT command. I probably need to add some input sanitation steps.
