### ISSUE TITLE
Monitor/scan/depart does not kick off depart scan

### ISSUE THREAD

**Issue by gmalbert** [andrewjfreyer/monitor#287]
I have sent a blank message to monitor/scan/depart, but a new departure scan does not occur. By way of further explanation, I'm using MQTT.fx software to view the MQTT messages coming through the broker (looking at #). I also have PREF_MQTT_REPORT_SCAN_MESSAGES set to true.

I have changed my mqtt_topicpath to "basementMonitor", so I have also tried sending a message to basementMonitor/scan/depart to see if the scan was based off of the topic path or that I needed to use monitor/scan/depart. Neither one works.

My expectation is that posting a blank message to the proper topic would initiate a departure scan for my known devices, but I don't get any new mqtt messages after triggering the departure scan.

Am I looking at this correctly? Happy to provide additional info if you need it.

**Comment by andrewjfreyer** [comment]
Can you post your MQTT preferences file redacting passwords and usernames?

**Comment by gmalbert** [comment]
```
# ---------------------------
#
# MOSQUITTO PREFERENCES
#
# ---------------------------

# IP ADDRESS OR HOSTNAME OF MQTT BROKER
mqtt_address=192.168.1.38

# MQTT BROKER USERNAME
mqtt_user=

# MQTT BROKER PASSWORD
mqtt_password=

# MQTT PUBLISH TOPIC ROOT
mqtt_topicpath=basementMonitor

# PUBLISHER IDENTITY
mqtt_publisher_identity='basement'

# MQTT PORT
mqtt_port='1883'

# MQTT CERTIFICATE FILE
mqtt_certificate_path=''

#MQTT VERSION (EXAMPLE: 'mqttv311')
mqtt_version=''

```

**Comment by SaturnusDJ** [comment]
Could it be that the scan type commands stop working after setting a custom mqtt_topicpath and/or mqtt_publisher_identity?

Other than that the mayor change I did was switch from HA integrated MQTT broker to Mosquitto. But this seems fine for all other MQTT stuff including monitor device_tracker reports, thus I suspect the above bug.

**Comment by andrewjfreyer** [comment]
Per your settings, you should be sending scan requests to: 

```
/basementMonitor/scan/depart
```

**Comment by SaturnusDJ** [comment]
That way works here, thanks.

**Comment by william57m** [comment]
Question related to that, I'm able to restart monitor with `monitor/scan/restart` but when I send `monitor/scan/depart` or ``monitor/scan/arrive` I'm not sure it works correctly, am I supposed to see a log in the logs?
