### ISSUE TITLE
Mac address bug strangeness

### ISSUE THREAD

**Issue by borpin** [andrewjfreyer/monitor#29]
Fresh install (first time user).

Added the following to the behavior_preferences
```
PREF_PUBLIC_MODE=true
PREF_BEACON_MODE=true
PREF_HEARTBEAT=true
```
Known mac addresses (slightly modified)
```
48:80:df:98:f1:f2 Brian #comment
c0:ee:fb:6c:0e:f2 OnePlusX
```

On restart, the first mac address, that was reporting every 240 seconds, did not report for ages (might be a setting issue).

The second mac address is reported as below on MQTT topic `monitor/ha-monitor/3c0:ee:fb:6c:0e:f2`
```
{
	"id": "3c0:ee:fb:6c:0e:f2",
	"retained": "false",
	"version": "0.1.661",
	"confidence": "0",
	"name": "Undiscoverable Device Name",
	"timestamp": "Tue Sep 25 2018 22:32:07 GMT+0100 (BST)",
	"manufacturer": "Unknown",
	"type": "KNOWN_MAC",
	"rssi": ""
}
```

Note the topic and mac address start with *3c0*

On starting interactively;
```
> preference: delay between scans = 3
> preference: periodic arrive/depart check interval = 15
> preference: periodic arrive interval = 45
> preference: periodic depart interval = 90
> preference: database refresh interval = 35
> preference: max arrival scan attempts = 2
> preference: max depart scan attempts = 4
> preference: random advertisement expiration = 45
> preference: beacon rssi change required for reporting = 10
> preference: bluetooth environmental report frequency = 300
> preference: forced departure check interval = 240
> preference: interval until beacon is considered expired = 145
> preference: trigger a departure scan at other nodes below [x] confidence = 25
> preference: preferred HCI device = hci0
> preference: minimum time between the same type of scan = 15
> preference: mqtt scan start/end reporting = false
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
> known device: 48:80:df:98:f1:f2 will publish to: monitor/ha-monitor/48:80:df:98:f1:f2
> known device: c0:ee:fb:6c:0e:f2 will publish to: monitor/ha-monitor/c0:ee:fb:6c:0e:f2
```

Final thought - I swapped these 2 mac addresses round in the `known_static_addresses` file - no difference.

**Comment by borpin** [comment]
So found the issue - it is a Regexp problem - should be `a-f` not `A-Z`.

https://github.com/andrewjfreyer/monitor/blob/3161adf884d024ae5b4f2a5d5b14fc3381d06e44/monitor.sh#L431

https://github.com/andrewjfreyer/monitor/blob/3161adf884d024ae5b4f2a5d5b14fc3381d06e44/monitor.sh#L292

**Comment by andrewjfreyer** [comment]
Ack - that's a stupid bug on my part.

` if [[ "$known_addr_stated" =~ .*[0-9A-Z]{3}.* ]]; then `

updated to 

`if [[ "$known_addr_stated" =~ .*[0-9A-Fa-f]{3}.* ]]; then `

This should fix this dumb issue.
