### ISSUE TITLE
Script Version Not Updating (Within Hass.io Add-On)

### ISSUE THREAD

**Issue by sbowater** [andrewjfreyer/monitor#291]
First of all -- love the project (albeit a little tricky to setup and understand first time through)!  This has definitely proven to be the most reliable presence detection I have attempted.

As a starting point I set up a couple of RPi Zero W nodes as fresh installs following your excellent instructions.  They are running v0.2.200.  (As a quick aside, they do occasionally get bogged down processing traffic which I am still trying to understand).

For an additional node I installed the Hass.io Add-on version published by @Limych (https://github.com/Limych/hassio-addons).  Since my RPi running HASS is connected to my network via ethernet, I figured the BT radio would be an available resource that wouldn't interfere with normal network operations since I'm not using wifi on that node.

The issue I'm seeing is that the monitor.sh version on that Hass.io node is v0.2.197.  Per @Limych, the monitor script should update itself automatically on start up.  I see the following line in the log every time I restart the add-on:

> updated monitor (v. Unknown) -> (v. 0.2.197)...

I know that there is a later version which is on my other nodes but don't know how to pull it through in this environment.

Please advise.

**Comment by Limych** [comment]
Hmm, maybe it's my fault. I've investigate it...

**Comment by sbowater** [comment]
@Limych : I don't know if this will help... when I run in -V verbose logging mode and send MQTT message "monitor/scan/update" I get the following in the log...

<pre><code>
[-] 0.2.197 25-01-2020 02:16:28 PM [CMD-INST]	[pass mqtt] update requested 
From https://github.com/andrewjfreyer/monitor
   e22f7a9..ef7fc0c  master     -> origin/master
 * [new tag]         0.2        -> 0.2
Already on 'master'
M	monitor.sh
M	support/argv
M	support/init
Your branch is behind 'origin/master' by 1898 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
error: Your local changes to the following files would be overwritten by merge:
	monitor.sh
Please commit your changes or stash them before you merge.
Aborting
Updating e22f7a9..ef7fc0c
/usr/local/bin/monitor: line 1244: systemctl: command not found
Exited.
</code></pre>

**Comment by Limych** [comment]
Yes, it was a bug in the addon. Fixed, but temporarily only in the edge version of the repository:
https://github.com/Limych/hassio-addons-edge
