### ISSUE TITLE
hostname in broker: system just freeze

### ISSUE THREAD

**Issue by tramanah** [andrewjfreyer/monitor#294]
I am running owntracks application in my HA and works well. After adding the hostname in MQTT preference, the monitor.sh display just hang there.

`
===================================================

              *** BETA/DEV BRANCH ***

===================================================
> starting monitor.sh (v. 0.2.200)...
> warning: for security purposes, please consider changing 'username' in: mqtt_preferences
> warning: for security purposes, please consider changing 'password' in: mqtt_preferences
> warning: operating in anonymous and unprotected mode for mqtt broker at **xxxxxxxx**.dlinkddns.com
> 88:75:98:FB:E9:E8 confidence topic: DRRM/Dir_Room/s9_avi (has previously connected to hci0)
> 44:18:FD:B2:6F:3C confidence topic: DRRM/Dir_Room/i_avi (has not previously connected to hci0)
> E0:AA:96:07:D9:59 confidence topic: DRRM/Dir_Room/n8_rama (has previously connected to hci0)
> A8:87:B3:9D:D8:13 confidence topic: DRRM/Dir_Room/a10_dilan (has not previously connected to hci0)
> C4:93:D9:B3:B3:5F confidence topic: DRRM/Dir_Room/a7_james (has not previously connected to hci0)
> 34:8A:7B:02:F4:83 confidence topic: DRRM/Dir_Room/j7_james (has not previously connected to hci0)
> FD:51:A1:48:4C:AF confidence topic: DRRM/Dir_Room/instinct_apac (has not previously connected to hci0)

`

**Comment by andrewjfreyer** [comment]
So your remote mqtt broker doesn't require a username/password? Are you able to connect to the broker from the pi?
