### ISSUE TITLE
If I reboot hassio, after startup hassio doesn't recevice messages anymore

### ISSUE THREAD

**Issue by TheStigh** [andrewjfreyer/monitor#297]
Hi,

Do have 4 monitor's running on RPi Zero's.
All works good until I reboot my hassio, then messages aren't passed to hassio until I reboot all monitor's. 

Any smart way to resolve this?

**Comment by andrewjfreyer** [comment]
HA has been somewhat unreliable for remembering states for mqtt sensors, for whatever reason. Some users retain messages, some users lean on HA and hope for the best, I personally trigger a restart of monitor nodes  via MQTT when HA restarts.
