### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by michaelblight** [andrewjfreyer/monitor#30]
I followed the instructions to install on a Pi Zero W, and got the following error at step 3:

```
pi@raspberrypi:~ $ sudo apt-get install rpi-update/raspbian
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Release 'raspbian' for 'rpi-update' was not found
```

Is this just an issue with the instructions? I went on to run the rpi-update and it worked ok.

**Comment by rudders** [comment]
opps - my bad - PR submitted to resolve.

**Comment by andrewjfreyer** [comment]
Fixed.

**Comment by michaelblight** [comment]
Great. Just for the record, everything went smoothly after that, except one minor speed bump - I stupidly entered the wifi mac addresses in `known_static_addresses` instead of the bluetooth ones, so got no messages. If you're updating the doco some time it might be helpful to highlight this for other thick people.
