### ISSUE TITLE
not quite sure how to get started

### ISSUE THREAD

**Issue by johntdyer** [andrewjfreyer/monitor#300]
Sp I've got this installed on my pi zero but Ia m not 100% sure how best to get started after the basic setup.  My end goal is to know if my iPhone XS is home or not.  I am really just not sure how I am expected to get its MAC address.  I also am unsure how this tool is supposed to handle the supposed mac rotation introduced a few years back ....

**Comment by andrewjfreyer** [comment]
Mac address is available in settings. Settings > General > About 

You're looking for bluetooth mac. 

The bluetooth mac does not rotate - the feature you're referring to related to beaconing from the phone. 

Note that you'll likely have to connect to at least one bluetooth device (per the FAQ) before your phone is recognized by `monitor`

**Comment by johntdyer** [comment]
So how often should I expect to see my bluetooth mac address in the logs when running it ?
