### ISSUE TITLE
Use monitor together with "person" integration + device_tracker

### ISSUE THREAD

**Issue by jcastro** [andrewjfreyer/monitor#302]
Hello,
I've been using monitor for close to a year now and it's by far the most stable and accurate way to detect presence in my home. None of the other systems are even close.

I was now reading more about the new person integration on Home Assistant (I know, it's not that new haha). I've setup my persons and used both device_tracker entities monitor generates for me, one being the Apple Watch and the other my iPhone. 

However, and here it comes the problem... It looks like person shows as Away as soon as one of those device_trackers are away. Sometimes this will happen if I put my phone in Airplane, but I'm still at home so my Apple watch is detected. Because monitor is so reliable I want to either setup person so it shows away only if all trackers are away or setup monitor in a way that provides this information? 

Do you have any ideas how I could make this work? Thanks so much!

**Comment by jcastro** [comment]
So I'm exploring an idea. I've added a new device on known_devices file called _rebecasee_. Now I have an entity called _device_track.rebecasee_ and used this automation found here https://github.com/andrewjfreyer/monitor/issues/138 to use device_tracker.see to update that entity when the _sensor.rebeca_occupancy_confidence_ (which is a mix of both the watch and the iphone).

However the automation doesn't seem to be updating the device_tracker.rebecasee entity

**Comment by jcastro** [comment]
Okay turns out that there's some changes on Home Assistant and that code from issue #138 doesn't work anymore. You now have to use only the last part of the entity id for the dev_id

**Comment by sbowater** [comment]
From what I recall from when I first implemented this I don't think I edited the known_devices file directly -- entries were added automatically with the correct syntax the first time I called the device_tracker.see service.

**Comment by jcastro** [comment]
@sbowater ah no, I added it manually because I wanted a new device_tracker entity to do the testing. Mostly one that won't change states influenced by other platform.

**Comment by sbowater** [comment]
I understand -- I created a "custom" device tracker just like you're describing.  The first time I executed this action:

` action:
    service: device_tracker.see
    data:
      dev_id: steve_monitor
      location_name: home
      source_type: bluetooth
`
it created the entry in known_devices for me.  This is unrelated to any other device tracking or person entries that I have set up in HA.  I then link this single device_tracker entity to my person entity to determine location/presence in the person module.

**Comment by jcastro** [comment]
@sbowater ah got it!. Btw I've tried restarting HA and now my new device_tracker entity I created doesn't keep the last state, so it always defaults to Away. Do you know if there's a way to fix this?

**Comment by sbowater** [comment]
> I've tried restarting HA and now my new device_tracker entity I created doesn't keep the last state, so it always defaults to Away. Do you know if there's a way to fix this?

I have this same issue and would also be interested in knowing if there's a way to get last state to persist.  I worked around this by creating an automation triggered when HA starts to test the monitor confidence level and set the device_tracker state.  The problem with this is that the state bounces from Home to Away and then Home again whenever there's a restart.

**Comment by jcastro** [comment]
@sbowater ah yeah. I wonder why it works fine with the device_tracker entities monitor creates through MQTT but not with this one we're creating myself. Maybe a way to merge several devices into one entity directly from monitor could be a solution?

**Comment by jcastro** [comment]
Okay so after all my testing I had to revert back and not use person for automations. They way it works it's not useful when you have such an accurate system like the one monitor provides. My only hope I guess it's that @andrewjfreyer can add some kind of merge device_tracker device (basically create a person devices tracker together) that then I can use on HA's person feature. As @sbowater said the state will jump from home to not_home and home again and that will trigger a lot of automations

Unless... there's another way to this?

**Comment by sbowater** [comment]
One potential solution would be to define an input boolean, e.g. input_boolean.hass_restart that you turn on just before a restart.  This state should persist through the restart and then you can use it in your automations to test whether a restart has just occurred and not trigger the actions.   After some settle period, an automation can turn the hass_restart boolean off.  Just a thought and may not be worth the effort.
