### ISSUE TITLE
Confidence always 0

### ISSUE THREAD

**Issue by papasen** [andrewjfreyer/monitor#306]
Trying to get this setup with Home Assistant. From the monitor side (Raspberry Pi 4) it seems to always report a confidence of 0. Even though my phone has Bluetooth turned on and is within a few meters of the RPi. Any idea’s?

`
[+] 0.2.200 08-03-2020 08:43:34 PM [CMD-INFO]	**** started arrival scan [x1 max rep] ****
[+] 0.2.200 08-03-2020 08:43:35 PM [CMD-SCAN]	(No. 1) xx:xx:xx:xx:xx:xx arrival?
[+] 0.2.200 08-03-2020 08:43:40 PM [CMD-MQTT]	monitor/pimon1/alias
 {
    "id":"xx:xx:xx:xx:xx:xx",
    "confidence":"0",
    "name":"alias ",
    "manufacturer":"SAMSUNG ELECTROMECHANICSTHAILAND",
    "type":"KNOWN_MAC",
    "retained":"false",
    "timestamp":"Sun Mar 08 2020 20:43:40 GMT+0100 (CET)",
    "version":"0.2.200"
 }
`

**Comment by papasen** [comment]
Anything I can try??

**Comment by gieljnssns** [comment]
Is your phone in pairing mode?

**Comment by papasen** [comment]
Hi Giel, thanks for your reply. No the phone is not in pairing mode. Should it be or should it not be?

**Comment by gieljnssns** [comment]
In pairing mode it should always work. 
You also should pair your phone to a Bluetooth accessory that you are not always connected to, like a car or bt speaker.

**Comment by papasen** [comment]
Thanks, but I didn't understand your answer completely. I have my phone paired to many devices like my car, headphones and speakers. But the pairing "mode" is not always active. Are you saying I should pair my phone with the RPi first (one time thing) before monitor detects it? (if so thanks for the pointer, this is not clear from the documentation at all).

**Comment by papasen** [comment]
As an update I have managed to pair my phone with the RPi (through bluetoothctl) but after starting up monitor again the confidence is still 0.

`"confidence":"0",`

**Comment by papasen** [comment]
Any thoughts anyone? My phone is now paired with the RPi, but confidence is still always 0.

**Comment by gieljnssns** [comment]
Sorry, I may not have been clear, your phone should not be paired with your raspberry pi. But when your phone is in pairing mode it should always work.
At least if you have entered the correct mac address ...
Which flags do you use to start monitor, which are your behavior_preferences?
Have you added your mac address to known_static_addresses or known_beacon_addresses? 
What output do you get when you do this ```hcitool name [mac address]``` ?

**Comment by papasen** [comment]
Apologies for the late reply. I had given up on getting this working, but now I have seen your response lets give it another try.

I'm starting monitor with "sudo bash monitor.sh -u -V", behavior_preferences (I believe I left these at their defaults:

`# ---------------------------
#								
# BEHAVIOR PREFERENCES
#								
# ---------------------------

#MAX RETRY ATTEMPTS FOR ARRIVAL
PREF_ARRIVAL_SCAN_ATTEMPTS=1

#MAX RETRY ATTEMPTS FOR DEPART
PREF_DEPART_SCAN_ATTEMPTS=2

#SECONDS UNTIL A BEACON IS CONSIDERED EXPIRED
PREF_BEACON_EXPIRATION=240

#MINIMUM TIME BEWTEEN THE SAME TYPE OF SCAN (ARRIVE SCAN, DEPART SCAN)
PREF_MINIMUM_TIME_BETWEEN_SCANS=15

#ARRIVE TRIGGER FILTER(S)
PREF_PASS_FILTER_ADV_FLAGS_ARRIVE=".*"
PREF_PASS_FILTER_MANUFACTURER_ARRIVE=".*"

#ARRIVE TRIGGER NEGATIVE FILTER(S)
PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE="NONE" 
PREF_FAIL_FILTER_MANUFACTURER_ARRIVE="NONE"`

Yes I have added the MAC address of my (Samsung Galaxy) S10 to known_static_addresses.

hcitool name [mac address] returns nothing.

Thanks for your support again.

**Comment by papasen** [comment]
I re-checked everything and noticed the MAC address I used was for the WiFi radio and not Bluetooth 🤦‍♂  I will configure everything back again (I had removed all related configuration as couldn't make it work) and give it another shot with the right MAC addresses this time.
Thanks, your questions made me discover my mistake.
