### ISSUE TITLE
Upper and lower case letters in mac address

### ISSUE THREAD

**Issue by borpin** [andrewjfreyer/monitor#31]
Following on from the bug #29, I note that I am seeing mac addresses in both upper and lower case being transmitted as mqtt topics.

Is the matching of the mac addresses case sensitive? 

I think #29 would only work for a mac address in lowercase so the regexp should be [0-9A-Fa-f]{3} unless the case of the whole string is changed somewhere.

**Comment by andrewjfreyer** [comment]
Yes, that is how #29 was closed. Matching is case insensitive.
