### ISSUE TITLE
Bluetooth connection problem

### ISSUE THREAD

**Issue by ipatalas** [andrewjfreyer/monitor#315]
Hi,

I have been trying to make the script work for a couple hours already and still failing:
![image](https://user-images.githubusercontent.com/2623329/80925640-c13d0f00-8d91-11ea-8a66-977b37c663fd.png)

Interesting part is that after running `monitor.sh` BT device always goes down and I have to bring it back every time.

I have also tried using `-c` switch to connect to my phone first. Connection is created (my phone sees it as well as paired device) but then the same:
![image](https://user-images.githubusercontent.com/2623329/80925661-fa757f00-8d91-11ea-8c2e-0ef1e8a40f8f.png)

This is all on Intel NUC machine which supports BT 5.0. Interestingly when I run the same on my **Pi 3** everything works just fine with the same phone and I didn't have to do any magic for that. It just worked since first run.

I've also seen that:
<details>
<summary><b>I keep seeing that my Bluetooth hardware is "cycling" in the logs - what does that mean?</b></summary>
<i>If more than one program or executable try to use the Bluetooth hardware at the same time, your Bluetooth hardware will report an error. To correct this error, the hardware needs to be taken offline, then brought back.</i>
</details>
I don't remember how many times I had to restart the device itself (down -> up) and bluetooth daemon as well.

Anything more I can do to troubleshoot that?

**Comment by franco-101** [comment]
From what i can tell this software has only been built to run reliably on a Pi Zero. As different model Bluetooth chips such as the one in your NUC work slightly differently and might not be able to handle being placed in constant monitoring mode.
I have tested on both a RPi 4 Model B - 4GB edition and also a Pi Zero W and have also seen different results.  
The software has been designed to function with Pi Zero, it might work on other hardware platforms but this would need testing.

**Comment by ipatalas** [comment]
Oh. That would make a lot of sense. How did I miss that information? Perhaps it should be put in bold :wink:
Anyway, thanks for the info. Need to find another tool for NUC.
