### ISSUE TITLE
Periodic scan mode always enabled

### ISSUE THREAD

**Issue by william57m** [andrewjfreyer/monitor#316]
Hi @andrewjfreyer,
Thanks for this great work.

It's not a real issue but when I'm running the monitor service it looks like the periodic scan mode is enabled, but when I checked the service definition, I saw that the script is ran without any arguments.
```bash
ExecStart=/bin/bash /home/pi/monitor/monitor.sh  &
```

Is it the expected behaviour? It seems like the departure scan and arrival scan are periodically called.

My use case is that I only trigger the departure scan when I leave (door closed + present at home) and trigger the arrival (when door open + not present at home), which works fine, but because of the periodic scan, sometime during the day my phone seems not detected, which is problematic.

Is there a way to disable the periodic scan? I only wants the script to react to my MQTT commands for departure/arrival scan.

**Comment by franco-101** [comment]
Hello William,

What you are after is written in the read me...

"The script will also trigger an ARRIVE scan in response to an mqtt message posted to the topic of monitor/scan/arrive. Advertisement-triggered scanning can be disabled by using the trigger argument if -ta, which causes monitor to only trigger ARRIVAL scans in response to mqtt messages.

If monitor has not heard from a particular anonymous address in a long time, monitor triggers a DEPART scan. The script will also trigger a DEPART scan in response to an mqtt message posted to the topic of monitor/scan/depart. Expiration-triggered scanning can be disabled by using the trigger argument if -td, which causes monitor to only trigger DEPART scans in response to mqtt messages."

I just had a question that you might be able to answer, is it that you send the MQTT message "monitor/scan/depart" from your MQTT broker and this then causes the pi to scan for departed devices?

**Comment by william57m** [comment]
Hi @franco-101, thanks for the answer, indeed I missed that 😅

`-tad` is exactly what I'm looking for. 

Yes I'm sending MQTT messages from my broker to trigger DEPART and ARRIVAL, but it looks like there was periodical scan happening during the day.
