### ISSUE TITLE
MQTT updates not firing

### ISSUE THREAD

**Issue by georgeinva2004** [andrewjfreyer/monitor#317]
Very nice piece of work!!!!  But, I am having an issue that hopefully someone can help with.
I have two Raspberry Pi's:  A Pi 3B and a Pi Zero.  The Pi 3B seems to be working well.  It sends MQTT updates as it "sees" bluetooth devices.  However, the Pi Zero with the same config files only sends the MQTT status message (saying it's online) at startup.  It never updates the status (like the 3B) nor does it send any updates as bluetooth devices become visible.  The log file confirms that the Pi Zero is seeing bluetooth activity, just no MQTT messages to my broker.

I'm running the latest version of Raspbian and monitor.  Any ideas?

Log below.

`> starting monitor.sh (v. 0.2.200)...
> warning: verbose logging is enabled. this setting is only for informational and debugging purposes
> warning: for security purposes, please consider changing 'username' in: mqtt_preferences
> warning: for security purposes, please consider changing 'password' in: mqtt_preferences
> warning: operating in anonymous and unprotected mode for mqtt broker at 192.168.1.183
> preference: minimum time between the same type of scan = 15
> preference: regex filter for flags to accept = .*
> preference: regex filter for flags to reject = NONE
> preference: regex filter for manufacturers to accept = .*
> preference: regex filter for manufacturers to reject = NONE
> preference: maximum sequential arrive scan attempts = 1
> preference: maximum sequential depart scan attempts = 2
> preference: selected HCI device = hci0
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
> log listener pid = 31295
> btle scan pid = 31296
> btle text pid = 31298
> btle listener pid = 31300
> mqtt listener pid = 31302
> packet listener pid = 31305
> beacon database time trigger pid = 31310
[-] 0.2.200 22-05-2020 03:20:09 PM [CMD-RAND]   [passed filter] data: 56:03:A6:CE:FD:0B pdu: ADV_IND rssi: -74 dBm flags: 0x1a man: Apple, Inc. delay: 3
[-] 0.2.200 22-05-2020 03:20:10 PM [CMD-RAND]   [passed filter] data: 6B:E4:1B:34:7F:B3 pdu: ADV_IND rssi: -67 dBm flags: 0x1a man: Apple, Inc. delay: 4
[-] 0.2.200 22-05-2020 03:21:13 PM [CMD-RSSI]   PUBL 74:40:BB:19:AD:D6 RSSI: -70 dBm (initial reading | 130 dBm)
[-] 0.2.200 22-05-2020 03:21:15 PM [CMD-RSSI]   PUBL 60:6D:C7:7D:9B:40 RSSI: -74 dBm (initial reading | 126 dBm)
[-] 0.2.200 22-05-2020 03:21:16 PM [CMD-RAND]   [passed filter] data: 0C:BA:D2:D4:12:CC pdu: ADV_NONCONN_IND rssi: -71 dBm flags: none man: Microsoft delay: 3
[-] 0.2.200 22-05-2020 03:21:17 PM [CMD-RSSI]   PUBL 90:CD:B6:5A:F7:38 RSSI: -76 dBm (slow movement approach | 22 dBm)
[-] 0.2.200 22-05-2020 03:21:18 PM [CMD-RAND]   [passed filter] data: 62:4B:89:D4:CC:6D pdu: ADV_IND rssi: -71 dBm flags: 0x1a man: Apple, Inc. delay: 3
[-] 0.2.200 22-05-2020 03:21:24 PM [CMD-RAND]   [passed filter] data: 71:04:E2:54:34:EB pdu: ADV_NONCONN_IND rssi: -71 dBm flags: none man: Microsoft delay: 5
[-] 0.2.200 22-05-2020 03:22:16 PM [CMD-RAND]   [passed filter] data: 72:2C:67:01:C4:00 pdu: ADV_IND rssi: -62 dBm flags: 0x1a man: Apple, Inc. delay: 0
[-] 0.2.200 22-05-2020 03:22:18 PM [CMD-RAND]   [passed filter] data: 2C:FC:2E:E0:62:C4 pdu: ADV_NONCONN_IND rssi: -75 dBm flags: none man: Microsoft delay: 2
[-] 0.2.200 22-05-2020 03:22:23 PM [CMD-RSSI]   PUBL 74:40:BB:19:AD:D6 RSSI: -79 dBm (slow movement depart | 22 dBm)
[-] 0.2.200 22-05-2020 03:23:14 PM [DEL-RAND]   RAND 56:03:A6:CE:FD:0B expired after 185 seconds
[-] 0.2.200 22-05-2020 03:23:22 PM [CMD-RSSI]   PUBL 74:40:BB:19:AD:D6 RSSI: -57 dBm (slow movement approach | 22 dBm)
[-] 0.2.200 22-05-2020 03:23:23 PM [CMD-RSSI]   PUBL 74:40:BB:19:AD:D6 RSSI: -79 dBm (slow movement depart | 22 dBm)
[-] 0.2.200 22-05-2020 03:23:24 PM [CMD-RAND]   [passed filter] data: 38:92:79:31:B0:98 pdu: ADV_NONCONN_IND rssi: -69 dBm flags: none man: Microsoft delay: 2
[-] 0.2.200 22-05-2020 03:23:31 PM [CMD-RAND]   [passed filter] data: 3A:F1:8B:6E:F2:F9 pdu: ADV_NONCONN_IND rssi: -74 dBm flags: none man: Microsoft delay: 4
[-] 0.2.200 22-05-2020 03:23:59 PM [CMD-RAND]   [passed filter] data: 19:91:44:94:DB:2C pdu: ADV_NONCONN_IND rssi: -75 dBm flags: none man: Microsoft delay: 0
[-] 0.2.200 22-05-2020 03:24:55 PM [CMD-RAND]   [passed filter] data: 1A:7E:69:91:E4:DF pdu: ADV_NONCONN_IND rssi: UKN dBm flags: none man: Microsoft delay: 0
[-] 0.2.200 22-05-2020 03:25:24 PM [DEL-RAND]   RAND 2C:FC:2E:E0:62:C4 expired after 187 seconds
[-] 0.2.200 22-05-2020 03:25:24 PM [DEL-RAND]   RAND 72:2C:67:01:C4:00 expired after 189 seconds
[-] 0.2.200 22-05-2020 03:25:37 PM [CMD-RAND]   [passed filter] data: 14:71:59:85:98:2A pdu: ADV_NONCONN_IND rssi: -64 dBm flags: none man: Microsoft delay: 2
[-] 0.2.200 22-05-2020 03:26:46 PM [CMD-RAND]   [passed filter] data: 7C:21:EE:7A:33:19 pdu: ADV_NONCONN_IND rssi: -75 dBm flags: none man: Microsoft delay: 4
[-] 0.2.200 22-05-2020 03:26:47 PM [DEL-RAND]   RAND 3A:F1:8B:6E:F2:F9 expired after 197 seconds
[-] 0.2.200 22-05-2020 03:27:04 PM [DEL-RAND]   RAND 19:91:44:94:DB:2C expired after 185 seconds
[-] 0.2.200 22-05-2020 03:27:04 PM [DEL-RAND]   RAND 38:92:79:31:B0:98 expired after 151 seconds
[-] 0.2.200 22-05-2020 03:27:49 PM [CMD-RAND]   [passed filter] data: 06:A1:53:11:17:55 pdu: ADV_NONCONN_IND rssi: -75 dBm flags: none man: Microsoft delay: 3
[-] 0.2.200 22-05-2020 03:27:51 PM [CMD-RAND]   [passed filter] data: 72:2C:67:01:C4:00 pdu: ADV_IND rssi: -75 dBm flags: 0x1a man: Apple, Inc. delay: 3
[-] 0.2.200 22-05-2020 03:28:04 PM [DEL-RAND]   RAND 1A:7E:69:91:E4:DF expired after 189 seconds
[-] 0.2.200 22-05-2020 03:28:39 PM [DEL-RAND]   RAND 14:71:59:85:98:2A expired after 183 seconds
[-] 0.2.200 22-05-2020 03:28:39 PM [DEL-RAND]   RAND 71:04:E2:54:34:EB expired after 188 seconds
[-] 0.2.200 22-05-2020 03:29:00 PM [CMD-RAND]   [passed filter] data: 5A:76:99:EA:61:20 pdu: ADV_IND rssi: -69 dBm flags: 0x1a man: Apple, Inc. delay: 3`

**Comment by georgeinva2004** [comment]
I figured it out.  You need to use the -b as a startup parameter.

**Comment by franco-101** [comment]
@georgeinva2004 where do you set this parameter, in the service exec path?

**Comment by georgeinva2004** [comment]
I'm not a linux person, so I hope I did this right

Shutdown the service - sudo systemctl stop monitor
 sudo bash monitor.sh -b -u
restarted the service - sudo systemctl restart monitor

I assume the -b switch is thrown for the  service.
