### ISSUE TITLE
Installed monitor but not getting anything in Hassio sensors

### ISSUE THREAD

**Issue by RedSnowDonkey** [andrewjfreyer/monitor#323]
Hi - I'm a new installer (and relatively new Hassio user) and I'm having some trouble.

I've followed the instructions (now twice), set up my 'mqtt_preferences' (and it seems to connect to my hassio, according to the logs - not that I know what I'm looking at that much):

```
# IP ADDRESS OR HOSTNAME OF MQTT BROKER
mqtt_address=192.168.0.18

# MQTT BROKER USERNAME
mqtt_user=<my MQTT user id>

# MQTT BROKER PASSWORD
mqtt_password=<my MQTT user password>

# MQTT PUBLISH TOPIC ROOT
mqtt_topicpath=monitor

# PUBLISHER IDENTITY
mqtt_publisher_identity='zero1'

# MQTT PORT
mqtt_port='1883'

# MQTT CERTIFICATE FILE
mqtt_certificate_path=''

#MQTT VERSION (EXAMPLE: 'mqttv311')
mqtt_version=''
```

I've set up 'known_static_addresses' with my and the wife's phones (albeit others seem to list this file as another name?):

```
# ---------------------------
#
# STATIC MAC ADDRESS LIST
#
# 00:00:00:00:00:00 Alias #comment
# ---------------------------

14:D1:69:12:60:83 Deans Honor
54:09:55:85:ac:d0 Gils Vodafone
```

...and updated configuration.yaml with the following:

```
sensor:
 - platform: mqtt
   state_topic: 'monitor/zero1/14:D1:69:12:60:83'
   value_template: '{{ value_json.confidence }}'
   unit_of_measurement: '%'
   name: 'Deans Honor'
 - platform: mqtt
   state_topic: 'monitor/zero1/54:09:55:85:ac:d0'
   value_template: '{{ value_json.confidence }}'
   unit_of_measurement: '%'
   name: 'Gils Vodafone'
```

Putting in "sudo bash monitor.sh" gives me a load of lines, starting with:

```
> starting monitor.sh (v. 0.2.200)...
> removing web request caches
> 14:D1:69:12:60:83 confidence topic: monitor/zero1/deans_honor (has not previou                                     sly connected to hci0)
> 54:09:55:85:AC:D0 confidence topic: monitor/zero1/gils_vodafone (has not previ                                     ously connected to hci0)
[-] 0.2.200 04-06-2020 07:33:06 pm [CMD-MQTT]   monitor/zero1/deans_honor { ...                                      confidence : 0 ... }
[-] 0.2.200 04-06-2020 07:33:06 pm [CMD-NAME]   14:D1:69:12:60:83 Deans Honor  H                                     UAWEI TECHNOLOGIES COLTD
[-] 0.2.200 04-06-2020 07:33:16 pm [CMD-MQTT]   monitor/zero1/gils_vodafone { ..                                     . confidence : 0 ... }
[-] 0.2.200 04-06-2020 07:33:16 pm [CMD-NAME]   54:09:55:85:AC:D0 Gils Vodafone                                       zte corporation
[-] 0.2.200 04-06-2020 07:34:06 pm [CMD-RSSI]   PUBL 60:6D:C7:1F:4D:94 RSSI: -48 dBm (initial reading | 152 dBm)
[-] 0.2.200 04-06-2020 07:35:57 pm [DEL-RAND]   RAND 41:1A:72:56:1B:81 expired after 110 seconds
[-] 0.2.200 04-06-2020 07:36:09 pm [CMD-NAME]   14:D1:69:12:60:83 Deans Honor  HUAWEI TECHNOLOGIES COLTD
[-] 0.2.200 04-06-2020 07:36:09 pm [CMD-NAME]   54:09:55:85:AC:D0 Gils Vodafone  zte corporation
[-] 0.2.200 04-06-2020 07:36:17 pm [DEL-RAND]   RAND E0:2A:0A:58:E8:F2 expired after 186 seconds
[-] 0.2.200 04-06-2020 07:36:37 pm [DEL-RAND]   RAND 36:EB:58:56:65:45 expired after 153 seconds
```

...and so on, but the entities I've set up in the conf file don't seem to be connecting, as their state comes up as "unknown".

I know that they're the right bluetooth addresses, as I've tracked them with the bluetooth on the RPI3 I'm using previously (but then deleted them from the known_devices file).

Any ideas whats up, please?

**Comment by Hagland** [comment]
You've named your known static addresses, try changing your state topics to `monitor/zero1/deans_honor` and `monitor/zero1/gils_vodafone` in configuration.yaml.

If that doesn't work, try using [MQTT Explorer](http://mqtt-explorer.com/) to see if the updates are actually being posted. I've had an issue before where monitor wouldn't post the messages before I set `mqtt_version`.

**Comment by RedSnowDonkey** [comment]
Strangely, it's monitor that isn't finding the devices, rather than MQTT not engaging, when I start it up. HASSIO isn't receiving any updates for the two devices from my rpi zero, as monitor isn't finding them (even when I scan on the phone, connect another device, restart, etc.), but it is receiving a connection...

**Comment by Hagland** [comment]
From `[-] 0.2.200 04-06-2020 07:36:09 pm [CMD-NAME]   14:D1:69:12:60:83 Deans Honor  HUAWEI TECHNOLOGIES COLTD` in the monitor.sh output it does seem like monitor finds them. Could you try to retain the messages with `sudo monitor.sh -x` and post a screenshot from MQTT Explorer? 

I'm willing to bet that HASSIO isn't receiving updates as `monitor/zero1/14:D1:69:12:60:83` doesn't exist. When you add a line as `14:D1:69:12:60:83 Deans Honor` in `known_static_addresses` it will post to `monitor/zero1/deans_honor` rather than `monitor/zero1/14:D1:69:12:60:83`.

That's what it does for me at least:
![image](https://user-images.githubusercontent.com/1595775/84075506-90757880-a9d4-11ea-9e04-867417f687f8.png)

**Comment by RedSnowDonkey** [comment]
Thanks... but the output on the rpi zero is showing a confidence of zero for "deans honor".  Doesn't that mean it's not finding it via bluetooth?

I haven't progressed to the MQTT bit again (as I reverted to a previous backup and I'm currently trying to get my head around MQTT explorer!).
