### ISSUE TITLE
Confidence 0

### ISSUE THREAD

**Issue by pgruetter** [andrewjfreyer/monitor#338]
Hi and first, thanks for the great project!

I've setup successfully with my phone but now I'm struggling to add two BTLE [key tags](https://www.aliexpress.com/item/4000730514769.html). 

Using hcitool the key tags were found correctly as TrackerPA.

I have three lines in known_static_addresses:
```
10:8E:E0:B3:AB:37 my_phone  # My phone
C1:B4:70:74:58:56 my_key    # My key
C1:B4:70:74:55:3E wife_key  # Wife key
```

Here's a sample output when starting monitor:
```
pi@pizero:~/monitor $ sudo bash monitor.sh 
> starting monitor.sh (v. 0.2.200)...
> removing web request caches
> 10:8E:E0:B3:AB:37 confidence topic: monitor/pizero/my_phone (has not previously connected to hci0)
> C1:B4:70:74:58:56 confidence topic: monitor/pizero/my_key (has not previously connected to hci0)
> C1:B4:70:74:55:3E confidence topic: monitor/pizero/wife_key (has not previously connected to hci0)
[-] 0.2.200 13-08-2020 09:58:16  [CMD-MQTT]     monitor/pizero/my_phone { ... confidence : 100 ... } 
[-] 0.2.200 13-08-2020 09:58:20  [CMD-NAME]     10:8E:E0:B3:AB:37 Galaxy S9  Samsung Electronics CoLtd
[-] 0.2.200 13-08-2020 09:58:25  [CMD-MQTT]     monitor/pizero/my_key { ... confidence : 0 ... } 
[-] 0.2.200 13-08-2020 09:58:26  [CMD-NAME]     C1:B4:70:74:58:56 TrackerPA  Unknown
[-] 0.2.200 13-08-2020 09:58:34  [CMD-MQTT]     monitor/pizero/wife_key { ... confidence : 0 ... } 
[-] 0.2.200 13-08-2020 09:58:35  [CMD-NAME]     C1:B4:70:74:55:3E TrackerPA  Unknown
[-] 0.2.200 13-08-2020 09:59:09  [CMD-INFO]     cycling bluetooth hardware on hci0. please wait a moment...
[-] 0.2.200 13-08-2020 09:59:38  [CMD-NAME]     C1:B4:70:74:58:56 TrackerPA  Unknown
[-] 0.2.200 13-08-2020 09:59:39  [CMD-NAME]     C1:B4:70:74:55:3E TrackerPA  Unknown
[-] 0.2.200 13-08-2020 10:00:15  [CMD-RSSI]     PUBL 0C:F3:EE:A2:42:97 RSSI: -96 dBm (initial reading | 104 dBm) 
[-] 0.2.200 13-08-2020 10:00:24  [CMD-RSSI]     PUBL 24:FC:E5:65:1E:3F RSSI: -88 dBm (slow movement depart | 28 dBm) 
[-] 0.2.200 13-08-2020 10:01:19  [DEL-RAND]     RAND 6E:4D:09:87:9C:2B expired after 182 seconds 
[-] 0.2.200 13-08-2020 10:01:30  [CMD-RSSI]     PUBL 24:FC:E5:65:1E:3F RSSI: -67 dBm (slow movement approach | 21 dBm) 
[-] 0.2.200 13-08-2020 10:01:50  [CMD-RSSI]     PUBL 0C:F3:EE:A2:42:97 RSSI: -95 dBm (initial reading | 105 dBm) 
[-] 0.2.200 13-08-2020 10:02:49  [DEL-RAND]     RAND 3A:3C:CC:4A:D8:97 expired after 197 seconds 
[-] 0.2.200 13-08-2020 10:03:03  [CMD-RSSI]     PUBL 0C:F3:EE:A2:47:D4 RSSI: -100 dBm (initial reading | 100 dBm) 
[-] 0.2.200 13-08-2020 10:03:57  [CMD-NAME]     C1:B4:70:74:58:56 TrackerPA  Unknown
[-] 0.2.200 13-08-2020 10:03:58  [CMD-NAME]     C1:B4:70:74:55:3E TrackerPA  Unknown
```

So if I interpret correctly:
The Galaxy S9 was found and reported with confidence 100. 
Both key tag also respond to NAME requests (CMD-NAME) but are never set to a confidence level higher than 0. 

Any idea what the problem might be?

Thanks

**Comment by greg-nyc** [comment]
Do you have the tracker's mac address in `known_beacon_addresses`?

**Comment by pgruetter** [comment]
> Do you have the key tags' mac addresses in `known_beacon_addresses`?

No, only in known_static_addresses. I tried moving one of the mac addresses to known_beacon_addressed but that didn't change the outcome.
Which file is correct?

**Comment by greg-nyc** [comment]
> Which file is correct?

I have a few Tiles for tracking keys. I put the MAC addresses for the Tiles in `known_beacon_addresses`. For all other Bluetooth devices, I list their addresses in 'known_static_addresses'. This has worked well for us. 

Are you sure the beacons' MAC addresses are correct? Looking at the log, `0C:F3:EE:A2:42:97` and `0C:F3:EE:A2:47:D4` trace back to a bluetooth beacon manufacturer, while the two you identified don't trace back to anything.

Once you get your beacons working, I'd suggest watching a few cycles. Our Tiles advertise their MAC addresses only every so often, so we dialed in the timeout on `PREF_BEACON_EXPIRATION` to work for us.

**Comment by pgruetter** [comment]
I'm pretty sure the MAC addresses are correct. How do you normally search for MAC addresses? 
I've used `hcitool lescan`, but now also tried again using `bluetoothctl`. Both display the same ones. 
The trackers also have a button so I can switch them off and verify that they are not found anymore in bluetoothctl. 

```
[bluetooth]# scan on
Discovery started
[NEW] Device C1:B4:70:74:55:3E TrackerPA
[NEW] Device C1:B4:70:74:58:56 TrackerPA
[CHG] Device C1:B4:70:74:55:3E RSSI: -68
[CHG] Device C1:B4:70:74:55:3E Name: TrackerPA     
[CHG] Device C1:B4:70:74:55:3E Alias: TrackerPA     
[CHG] Device C1:B4:70:74:58:56 RSSI: -68
[CHG] Device C1:B4:70:74:58:56 Name: TrackerPA     
[CHG] Device C1:B4:70:74:58:56 Alias: TrackerPA     
```
Put the two addresses in `known_beacon_addresses` now but still no change:
```
pi@pizero:~/monitor $ sudo bash monitor.sh 
> starting monitor.sh (v. 0.2.200)...
> removing web request caches
> 10:8E:E0:B3:AB:37 confidence topic: monitor/pizero/my_phone (has not previously connected to hci0)
> known beacon: C1:B4:70:74:58:56 publishes to: monitor/pizero/my_key
> known beacon: C1:B4:70:74:55:3E publishes to: monitor/pizero/wife_key
[-] 0.2.200 15-08-2020 05:22:58  [CMD-MQTT]     monitor/pizero/my_phone { ... confidence : 0 ... } 
[-] 0.2.200 15-08-2020 05:23:04  [CMD-NAME]     10:8E:E0:B3:AB:37 my_phone  Samsung Electronics CoLtd
[-] 0.2.200 15-08-2020 05:23:57  [CMD-RSSI]     PUBL 24:FC:E5:65:1E:3F RSSI: -88 dBm (initial reading | 112 dBm) 
[-] 0.2.200 15-08-2020 05:25:11  [CMD-MQTT]     monitor/pizero/my_phone { ... confidence : 100 ... } 
[-] 0.2.200 15-08-2020 05:25:12  [CMD-NAME]     10:8E:E0:B3:AB:37 Galaxy S9  Samsung Electronics CoLtd
```
The two trackers are never displayed.

**Comment by greg-nyc** [comment]
A few more thoughts. What flags are you using after `sudo bash monitor.sh`? Make sure you've enabled -b for beacons.

If that doesn't work, could you run monitor with `-V` flag for a few minutes with the beacons on and paste the log here?

**Comment by pgruetter** [comment]
> What flags are you using after `sudo bash monitor.sh`? Make sure you've enabled -b for beacons.

Oh, I haven't used any flags at all! Now it looks different, the tags are reported with a confidence of 100%, thanks a lot for the tip.
Now, how do I activate that flag for the service? Do I edit the file /etc/systemd/sytem/monitor.service by hand?

**Comment by greg-nyc** [comment]
Great to hear the beacons are now working as expected.

To see all of the options, try `sudo bash monitor.sh -h`. I've pasted the options below:
```
	monitor -h 	show usage information
	monitor -R 	redact private information from logs
	monitor -S 	silent operation (no logging)
	monitor -c addr	create connection to bluetooth device
	monitor -C 	clean retained messages from MQTT broker

	monitor -V	print verbose/debug logging messages
	monitor -v	print version number
	monitor -d	restore to default behavior_preferences
	monitor -u	update 'monitor.service' to current command line settings
			(excluding -u,-V, -F, and -d flags)

	monitor -r	repeatedly scan for arrival & departure of known devices
	monitor -s  report all mqtt messages to a single topic with 
				$mqtt_topicpath/$mqtt_publisher_identity  (defined in MQTT preferences file)

	monitor -f	format MQTT topics with only letters and numbers
	monitor -a	report all known device scan results, not just changes
	monitor -x	retain mqtt status messages
	monitor -b	report bluetooth beacon advertisements (e.g., generic beacons, ibeacons, and so on)
	monitor -t[adr]	scan for known devices only on mqtt trigger messages:
				a $mqtt_topicpath/scan/ARRIVE (defined in MQTT preferences file)
				d $mqtt_topicpath/scan/DEPART (defined in MQTT preferences file)
				r send ARRIVE or DEPART messages to trigger other devices to scan 
	monitor -D [dir]	use alternative directory for configuration files
```
You can try out flags by adding them to the end of `sudo bash monitor.sh`. For example, I run my Monitor with `sudo bash monitor.sh -x -b -tad` because I want messages to be retained, I have beacons and I only want scans to be run on triggers (e.g., door opening).

Once you've found the flags you like, add `-u` and Monitor will now run with all of the flags you've selected. No need to edit the service file by hand.

**Comment by pgruetter** [comment]
Wonderful, the more I see, the more I like :+1: Having a flag updating the service automatically: very nice :-)
Thanks for the support, I'll close this issue as my initial question is solved. Still need to tinker with the detailed settings I guess. At the moment, I think the keys are disappearing and reappearing all the time. I assume that's what you mentioned with the beacons only advertising the MAC address every so often so I'll try by increasing `PREF_BEACON_EXPIRATION`.
