### ISSUE TITLE
Change wifi access point

### ISSUE THREAD

**Issue by roybosch** [andrewjfreyer/monitor#341]
Hi,

Is it possible to change the wifi access point on the BLE scanner? 

I've been searching for the config file on the SD card, but then I noticed this sentence:

> On the first startup, insert SD card and power on Raspberry Pi Zero W. On first boot, the newly-created wpa_supplicant.conf file and ssh will be moved to appropriate directories. Find the IP address of the Pi via your router.

Is there any other way to do this?

Thanks in advance!

Roy

**Comment by franco-101** [comment]
You should be able to use raspi-config
