### ISSUE TITLE
Excessive MQTT connections

### ISSUE THREAD

**Issue by Nihvel** [andrewjfreyer/monitor#343]
This portion of log, from `mosquitto broker` addon on Home Assistant, was recorded in a couple of minutes only (literally 2).
It seem like `monitor` doesn't just connect once and waits quietly, rather it keeps opening connections with the MQTT Broker.

```
1601919904: New connection from 10.0.2.11 on port 1883.
[INFO] found mqtt_user on local database
1601919904: New client connected from 10.0.2.11 as livingroom31149 (p2, c1, k60, u'mqtt_user').
1601919904: Client livingroom31149 disconnected.
1601919904: New connection from 10.0.2.11 on port 1883.
1601919904: New client connected from 10.0.2.11 as livingroom31151 (p2, c1, k60, u'mqtt_user').
1601919904: Client livingroom31151 disconnected.
1601919904: New connection from 10.0.2.11 on port 1883.
1601919904: New client connected from 10.0.2.11 as livingroom31153 (p2, c1, k60, u'mqtt_user').
1601919904: Client livingroom31153 disconnected.
1601919947: New connection from 10.0.2.11 on port 1883.
1601919947: New client connected from 10.0.2.11 as livingroom8229 (p2, c1, k60, u'mqtt_user').
1601919947: Client livingroom8229 disconnected.
1601919947: New connection from 10.0.2.11 on port 1883.
1601919947: New client connected from 10.0.2.11 as livingroom8231 (p2, c1, k60, u'mqtt_user').
1601919947: Client livingroom8231 disconnected.
1601919947: New connection from 10.0.2.11 on port 1883.
1601919947: New client connected from 10.0.2.11 as livingroom8233 (p2, c1, k60, u'mqtt_user').
1601919947: Client livingroom8233 disconnected.
1601919953: New connection from 10.0.2.11 on port 1883.
1601919953: New client connected from 10.0.2.11 as livingroom8740 (p2, c1, k60, u'mqtt_user').
1601919953: Client livingroom8740 disconnected.
1601919953: New connection from 10.0.2.11 on port 1883.
1601919953: New client connected from 10.0.2.11 as livingroom8742 (p2, c1, k60, u'mqtt_user').
1601919953: Client livingroom8742 disconnected.
1601919953: New connection from 10.0.2.11 on port 1883.
1601919953: New client connected from 10.0.2.11 as livingroom8744 (p2, c1, k60, u'mqtt_user').
1601919953: Client livingroom8744 disconnected.
``` 

Lately, the MQTT Broker started to print:
```
1601674634: New connection from 10.0.2.11 on port 1883.
1601674634: New client connected from 10.0.2.11 as livingroom9694 (p2, c1, k60, u'mqtt_user').
1601674634: Outgoing messages are being dropped for client livingroom9694.
```
And when this happens, the whole MQTT network is down. It takes roughly 10 minutes for the `New client connected` message to reappear, which again, spams hundreds of rows of logs of `monitor` connections.

Do you think that `monitor` should be adjusted so that it only connects once to the MQTT Broker and waits patiently for `-tadr` mqtt messages?

Thanks

**Comment by SaturnusDJ** [comment]
You can find some issues where is explained that this is normal behaviour.
https://github.com/andrewjfreyer/monitor/issues?q=New+client+connected

Maybe you live in an environment where many BT devices pass along?

**Comment by Nihvel** [comment]
@SaturnusDJ I didn't think of looking at the previous (closed) issues - now I'm sorry I opened this one that it seems it can't be addresses :/
For replying to your question, there are many bluetooth around the apartment and many are similar devices (Samsung, Huawei..).

The issue I meant is a little bit different.

If `monitor.service` is set up as `monitor.sh -x -b -tad &` it really shouldn't perform any scan on its own. Therefore, I shouldn't see such messages regarding MQTT connection, because the scan only starts when a message to the ARRIVE/DEPART monitor topics are sent.
It is true that for the message to be received, Monitor must be connected to MQTT Broker constantly. And that's hard to achieve, currently.
Maybe due to the BASH limitation or the way `monitor` was written, IDK. 

I have seen other issues opened because of this, with the label `wontfix`. So I really don't expect a fix. But in the long run this could become an abandoned project and that's a pity since it's among the most reliable tools around

**Comment by andrewjfreyer** [comment]
Still normal behavior. Not optimal behavior, but normal.

**Comment by MattL0** [comment]
this prevent me from using that tool too. On jeedom ble ( BLEA plugin) are filtered. So it can be done here too.

**Comment by Nihvel** [comment]
@MattL0 I probably have to change project...
Recently Monitor failed again, but this time it is not recovering and it's already one week I'm trying to debug. As soon as the Raspberry or the VM is booted, the whole MQTT network crashes. All I can do is poweroff the system and almost instantly the whole MQTT network (the Broker) recovers.
