### ISSUE TITLE
How many devices can be feasibly detected

### ISSUE THREAD

**Issue by viljamip** [andrewjfreyer/monitor#347]
Hello,
not actually an issue as such but I was wondering how many devices I could feasibly detect with this system. I'm not particularly concerned with this specific implementation but the limitations of this method in general.

Let's say I would want to be able to detect 100 devices with as small delay as possible. The default parameter for the scanning interval for this solution is 3 seconds. Let's say I find an awesome BL HW that is capable of scanning every second. What if I put for example 10 BL scanners next to each other, each scanning a subset of the 100 device list. This would then theoretically mean that the detection takes 5 seconds on average and max 10 seconds.

Does anyone have an idea would this much traffic pollute the BL environment so much that no communication would work?

**Comment by andrewjfreyer** [comment]
This is a procedural script running in an infinite loop designed for low-power hardware, so realistically for this script, the limit for reasonable performance is less than 10 devices. 

That said, the concept of tracking by name requests in response to adv frames is solid, (at present) future proof, and could easily be implemented in higher order languages to track an arbitrary number of devices.
