### ISSUE TITLE
Can a single Mosquitto MQTT be run on a separate host?

### ISSUE THREAD

**Issue by jwilleke** [andrewjfreyer/monitor#376]
I was thinking I could run monitor on multiple PIs spread around a property and have them all send data to a single Mosquitto MQTT.

Would this work and if so, how do I configure monitor to use the remote host?

thanks!
-jim

**Comment by nickh66** [comment]
Hi Jim,
All you need to do is edit the /monitor/mqtt_preferences file and change the mqtt_address, mqtt_user & mqtt_passwords values as needed.  I do this for pointing my separate monitor notes to my central mqtt broken running on my home-assistant server.  Just make sure the mqtt_publisher_identity value is unique for your nodes.
Cheers
Nick

**Comment by jwilleke** [comment]
Thanks!
