### ISSUE TITLE
Not seeing MQTT Pub messages

### ISSUE THREAD

**Issue by hazyitsm** [andrewjfreyer/monitor#380]
I've setup Monitor on a PI Zero W, and I'm not getting any response in Home Assistant (Running HassOS as VM on Unraid). I have several Ring security devices communicating via MQTT on HA, and they are working as expected, using the Ring Devices add-on.

I checked in MQTT Explorer, and there are no monitor topics listed (other than $SYS). I also see that I don't have any CMD-RAND lines in my monitor.sh output. Should I?

I'm hoping I missed something very basic.

Here's the output I get running monitor.sh with no flags:

`pi@raspberrypi:~/monitor $ sudo bash monitor.sh
> starting monitor.sh (v. 0.2.200)...
> 48:01:C5:6B:FC:38 confidence topic: monitor/rpiz_monitor2/dan_phone (has not previously connected to hci0)
> 9C:5A:44:B8:54:FD confidence topic: monitor/rpiz_monitor2/dan_watch (has not previously connected to hci0)
[-] 0.2.200 12-02-2021 04:46:04 pm [CMD-NAME]   48:01:C5:6B:FC:38 OnePlus 7T  OnePlus Technology Shenzhen Co Ltd
[-] 0.2.200 12-02-2021 04:49:20 pm [DEL-RAND]   RAND 1A:8E:69:00:C5:3A expired after 185 seconds 
[-] 0.2.200 12-02-2021 04:49:38 pm [DEL-RAND]   RAND 8E:E8:A3:0F:C7:99 expired after 193 seconds 
[-] 0.2.200 12-02-2021 04:49:48 pm [CMD-RSSI]   PUBL 00:1F:FF:5A:31:04 RSSI: -87 dBm (initial reading | 113 dBm) 
[-] 0.2.200 12-02-2021 04:49:58 pm [DEL-RAND]   RAND 80:85:46:19:72:D5 expired after 183 seconds 
[-] 0.2.200 12-02-2021 04:50:13 pm [DEL-RAND]   RAND 5B:AF:93:49:08:82 expired after 184 seconds 
[-] 0.2.200 12-02-2021 04:50:18 pm [DEL-RAND]   RAND 3B:85:F3:1A:CC:24 expired after 183 seconds 
[-] 0.2.200 12-02-2021 04:50:31 pm [CMD-MQTT]   monitor/rpiz_monitor2/dan_phone { ... confidence : 100 ... } 
[-] 0.2.200 12-02-2021 04:50:38 pm [DEL-RAND]   RAND 14:8F:4F:6C:3A:AC expired after 193 seconds 
[-] 0.2.200 12-02-2021 04:50:57 pm [CMD-MQTT]   monitor/rpiz_monitor2/dan_watch { ... confidence : 0 ... } 
[-] 0.2.200 12-02-2021 04:50:58 pm [DEL-RAND]   RAND 40:B3:4A:6D:B5:E5 expired after 165 seconds 
[-] 0.2.200 12-02-2021 04:50:58 pm [DEL-RAND]   RAND 21:99:D2:1E:6C:58 expired after 160 seconds 
[-] 0.2.200 12-02-2021 04:50:58 pm [DEL-RAND]   RAND 91:36:54:74:AC:DE expired after 193 seconds 
[-] 0.2.200 12-02-2021 04:51:28 pm [CMD-MQTT]   monitor/rpiz_monitor2/dan_watch { ... confidence : 0 ... } 
[-] 0.2.200 12-02-2021 04:51:38 pm [DEL-RAND]   RAND 86:F2:88:BF:E4:88 expired after 193 seconds 
[-] 0.2.200 12-02-2021 04:51:38 pm [DEL-RAND]   RAND F0:C7:75:FD:29:7E expired after 183 seconds 
[-] 0.2.200 12-02-2021 04:51:58 pm [DEL-RAND]   RAND 9D:E6:CC:58:67:3D expired after 193 seconds 
[-] 0.2.200 12-02-2021 04:51:58 pm [DEL-RAND]   RAND 40:AF:C3:F5:8C:BE expired after 183 seconds 
[-] 0.2.200 12-02-2021 04:51:58 pm [CMD-MQTT]   monitor/rpiz_monitor2/dan_watch { ... confidence : 0 ... } 
[-] 0.2.200 12-02-2021 04:52:18 pm [DEL-RAND]   RAND 3D:80:6B:08:82:17 expired after 193 seconds 
[-] 0.2.200 12-02-2021 04:52:24 pm [DEL-RAND]   RAND 5E:46:78:F4:F6:4B expired after 184 seconds 
[-] 0.2.200 12-02-2021 04:52:24 pm [DEL-RAND]   RAND 20:EF:B2:5F:93:FC expired after 185 seconds `

It looks like my phone is communicating with the RPi Zero, but nothing is being published via MQTT, as far as I can tell.

Here's my mqtt_preferences:

```
# IP ADDRESS OR HOSTNAME OF MQTT BROKER
mqtt_address='HassOS IP'

# MQTT BROKER USERNAME
mqtt_user='mqtt username'

# MQTT BROKER PASSWORD
mqtt_password='mqtt password'

# MQTT PUBLISH TOPIC ROOT 
mqtt_topicpath=monitor

# PUBLISHER IDENTITY 
mqtt_publisher_identity='rpiz_monitor2'

# MQTT PORT 
mqtt_port='1883'

# MQTT CERTIFICATE FILE
mqtt_certificate_path=''

#MQTT VERSION (EXAMPLE: 'mqttv311')
mqtt_version=''
```

And known_static_addresses ...

```
# ---------------------------
#
# STATIC MAC ADDRESS LIST
#
# 00:00:00:00:00:00 Alias #comment
# ---------------------------

48:01:c5:6b:fc:38 Dan_phone
9c:5a:44:b8:54:fd Dan_watch
```

I haven't changed anything in bahavior_preferences.

Any thoughts as to where I should look? Thanks!

**Comment by hazyitsm** [comment]
I'm trying again with the -V flag and will post results.

**Comment by hazyitsm** [comment]
This is what I get with verbose logging:
```
pi@raspberrypi:~/monitor $ sudo bash monitor.sh -V
> starting monitor.sh (v. 0.2.200)...
> removing web request caches
> warning: verbose logging is enabled. this setting is only for informational and debugging purposes
> preference: minimum time between the same type of scan = 15
> preference: regex filter for flags to accept = .*
> preference: regex filter for flags to reject = NONE
> preference: regex filter for manufacturers to accept = .*
> preference: regex filter for manufacturers to reject = NONE
> preference: maximum sequential arrive scan attempts = 1
> preference: maximum sequential depart scan attempts = 2
> preference: selected HCI device = hci0
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
> 48:01:C5:6B:FC:38 confidence topic: monitor/rpiz_monitor2/dan_phone (has not previously connected to hci0)
> log listener pid = 4618
> btle scan pid = 4619
> btle text pid = 4620
> btle listener pid = 4622
> mqtt listener pid = 4624
> packet listener pid = 4627
> beacon database time trigger pid = 4634
[+] 0.2.200 12-02-2021 06:04:47 pm [CMD-RAND]   [passed filter] data: 7A:B2:35:2E:C9:6D pdu: ADV_SCAN_IND rssi: -69 dBm flags: none man: Google delay: 0
[+] 0.2.200 12-02-2021 06:04:48 pm [CMD-INFO]   **** started arrival scan [x1 max rep] **** 
[+] 0.2.200 12-02-2021 06:04:50 pm [CMD-RAND]   [passed filter] data: 48:FD:57:48:87:C3 pdu: ADV_NONCONN_IND rssi: -70 dBm flags: none man: Microsoft delay: 2
[+] 0.2.200 12-02-2021 06:04:51 pm [CMD-SCAN]   (No. 1) 48:01:C5:6B:FC:38 arrival? 
[+] 0.2.200 12-02-2021 06:04:51 pm [CMD-RAND]   [passed filter] data: 4F:62:DE:C3:2B:2E pdu: ADV_IND rssi: -67 dBm flags: 0x02 man: unknown delay: 4
[+] 0.2.200 12-02-2021 06:04:52 pm [CMD-RAND]   [passed filter] data: 74:04:5C:9F:D8:E8 pdu: ADV_SCAN_IND rssi: -68 dBm flags: none man: Google delay: 4
[+] 0.2.200 12-02-2021 06:04:52 pm [CMD-RAND]   [passed filter] data: 40:B3:4A:6D:B5:E5 pdu: ADV_SCAN_IND rssi: -61 dBm flags: none man: Google delay: 5
[+] 0.2.200 12-02-2021 06:04:54 pm [CMD-RAND]   [passed filter] data: 7F:63:AD:F3:08:70 pdu: SCAN_RSP rssi: -75 dBm flags: none man: Google delay: 6
[+] 0.2.200 12-02-2021 06:04:56 pm [CMD-RAND]   [passed filter] data: 69:FC:98:45:2C:AB pdu: ADV_IND rssi: -74 dBm flags: 0x02 man: unknown delay: 7
[+] 0.2.200 12-02-2021 06:04:58 pm [CMD-RAND]   [passed filter] data: CF:B4:B0:ED:C2:B7 pdu: ADV_NONCONN_IND rssi: -63 dBm flags: none man: unknown delay: 7
[+] 0.2.200 12-02-2021 06:05:01 pm [CMD-NAME]   48:01:C5:6B:FC:38 OnePlus 7T  OnePlus Technology Shenzhen Co Ltd
[+] 0.2.200 12-02-2021 06:05:03 pm [CMD-RAND]   [passed filter] data: 56:D3:E1:7E:85:C5 pdu: ADV_NONCONN_IND rssi: -70 dBm flags: none man: unknown delay: 4
[+] 0.2.200 12-02-2021 06:05:09 pm [CMD-RAND]   [passed filter] data: 4D:58:4C:C4:4A:6E pdu: ADV_NONCONN_IND rssi: -71 dBm flags: none man: Microsoft delay: 0
[+] 0.2.200 12-02-2021 06:05:16 pm [CMD-RAND]   [passed filter] data: 5A:22:B9:B5:E9:7E pdu: ADV_NONCONN_IND rssi: -71 dBm flags: none man: unknown delay: 5
[+] 0.2.200 12-02-2021 06:05:18 pm [CMD-RAND]   [passed filter] data: A8:29:42:55:01:E8 pdu: ADV_NONCONN_IND rssi: -72 dBm flags: none man: unknown delay: 1
[+] 0.2.200 12-02-2021 06:05:27 pm [CMD-RAND]   [passed filter] data: 4D:00:44:11:04:4B pdu: ADV_NONCONN_IND rssi: -75 dBm flags: none man: unknown delay: 1
[+] 0.2.200 12-02-2021 06:05:31 pm [CMD-RSSI]   PUBL B8:BC:5B:B1:10:C3 RSSI: -93 dBm (initial reading | 107 dBm) 
[+] 0.2.200 12-02-2021 06:05:32 pm [CMD-RSSI]   PUBL D0:6E:DE:8B:1D:87 RSSI: -93 dBm (initial reading | 107 dBm) 
[+] 0.2.200 12-02-2021 06:05:37 pm [CMD-RAND]   [passed filter] data: 44:DC:86:15:67:90 pdu: ADV_NONCONN_IND rssi: -68 dBm flags: none man: unknown delay: 0
[+] 0.2.200 12-02-2021 06:05:39 pm [CMD-RSSI]   PUBL 00:1F:FF:9E:96:DE RSSI: -88 dBm (initial reading | 112 dBm) 
[+] 0.2.200 12-02-2021 06:05:45 pm [CMD-RAND]   [passed filter] data: 6F:F0:FF:89:42:77 pdu: ADV_SCAN_IND rssi: -63 dBm flags: none man: Google delay: 2
[+] 0.2.200 12-02-2021 06:06:02 pm [CMD-RAND]   [passed filter] data: 05:62:D8:88:C8:DA pdu: ADV_NONCONN_IND rssi: -69 dBm flags: none man: unknown delay: 5
[+] 0.2.200 12-02-2021 06:06:27 pm [CMD-RAND]   [passed filter] data: 48:F3:15:BB:86:74 pdu: ADV_NONCONN_IND rssi: -63 dBm flags: none man: unknown delay: 0
[+] 0.2.200 12-02-2021 06:06:38 pm [CMD-RAND]   [passed filter] data: F2:47:34:E2:1E:56 pdu: ADV_NONCONN_IND rssi: -70 dBm flags: none man: unknown delay: 2
[+] 0.2.200 12-02-2021 06:06:47 pm [CMD-RAND]   [passed filter] data: 14:8C:C4:11:08:DE pdu: ADV_NONCONN_IND rssi: -69 dBm flags: none man: unknown delay: 1
[+] 0.2.200 12-02-2021 06:07:13 pm [CMD-RAND]   [passed filter] data: 9C:66:50:C1:C6:C9 pdu: ADV_NONCONN_IND rssi: -47 dBm flags: none man: unknown delay: 6
[+] 0.2.200 12-02-2021 06:07:24 pm [CMD-MQTT]   monitor/rpiz_monitor2/dan_phone { ... confidence : 100 ... } 
[+] 0.2.200 12-02-2021 06:07:30 pm [DEL-RAND]   RAND 48:FD:57:48:87:C3 expired after 209 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND 01:D0:3F:FC:25:3D expired after 244 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND 4D:58:4C:C4:4A:6E expired after 203 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND 53:87:6C:1A:88:96 expired after 184 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND 6F:F0:FF:89:42:77 expired after 200 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND 49:95:72:20:72:84 expired after 232 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND DB:2D:B9:B6:E0:E3 expired after 194 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND 7C:C5:03:B1:EC:0C expired after 254 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND 7F:63:AD:F3:08:70 expired after 201 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND 69:FC:98:45:2C:AB expired after 198 seconds 
[+] 0.2.200 12-02-2021 06:07:31 pm [DEL-RAND]   RAND 0B:BD:25:67:B5:1B expired after 196 seconds 
[+] 0.2.200 12-02-2021 06:07:34 pm [CMD-RSSI]   PUBL B8:BC:5B:B1:10:C3 RSSI: -94 dBm (initial reading | 106 dBm) 
[+] 0.2.200 12-02-2021 06:07:37 pm [CMD-RAND]   [passed filter] data: 76:9C:E7:5B:14:59 pdu: ADV_NONCONN_IND rssi: -66 dBm flags: none man: unknown delay: 0
[+] 0.2.200 12-02-2021 06:07:47 pm [CMD-RAND]   [passed filter] data: 37:6E:6C:AA:C5:99 pdu: ADV_NONCONN_IND rssi: -67 dBm flags: none man: unknown delay: 0
[+] 0.2.200 12-02-2021 06:07:55 pm [DEL-RAND]   RAND A0:76:73:2E:C6:2F expired after 198 seconds 
```

**Comment by nickh66** [comment]
Hi,
I don't know if this will help, but could it be that the MAC address comparison between your known_static list & the actual discovery is case sensitive?  Maybe it's worth making the MAC's in your known_static_addresses file all caps?
Cheers
Nick

**Comment by hazyitsm** [comment]
> Hi,
> I don't know if this will help, but could it be that the MAC address comparison between your known_static list & the actual discovery is case sensitive? Maybe it's worth making the MAC's in your known_static_addresses file all caps?
> Cheers
> Nick

Hi Nick, thanks for the reply. So I tried putting in all caps for the alpha parts of the BT mac addresses, and still no luck.

I'll continue trying some things today as time allows. Any other ideas of where to look?

**Comment by hazyitsm** [comment]
OK, I figured it out. The 2 RPi Zeroes are on a separate vLAN from the HA server. I updated firewall rules to allow MQTT traffic through, and HA is now seeing messages from the RPis.
