### ISSUE TITLE
Migrate from presence

### ISSUE THREAD

**Issue by xbmcnut** [andrewjfreyer/monitor#4]
Hi Andrew,

Great work, thank you. I've been using presence for some months on two Pi Zero's and it has been rock solid but lately the broker has been connecting and disconnecting both Pi's all the time. I've tried two different brokers, same deal.

```
1534132924: New connection from 10.0.1.52 on port 1883.
1534132924: New client connected from 10.0.1.52 as mosqpub|725-pi-presence (c1, k60, u'').
1534132924: Client mosqpub|725-pi-presence disconnected.
1534132927: New connection from 10.0.1.51 on port 1883.
1534132927: New client connected from 10.0.1.51 as mosqpub|29235-pi-presen (c1, k60, u'').
1534132927: Client mosqpub|29235-pi-presen disconnected.
```

I'm looking to change over to monitor to try that. What's the easiest way to uninstall presence dependencies and move over to monitor?

**Comment by andrewjfreyer** [comment]
To uninstall presence, simply delete the directory and remove the service with init.d or systemctl.
