### ISSUE TITLE
Can I use an existing MQTT server?

### ISSUE THREAD

**Issue by pastaholic** [andrewjfreyer/monitor#418]
Hi all,

Sorry for the rookie question.
I already have an MQTT server in my network.
I was wondering if I can use that instead of the one that's installed as per the [installation instructions](https://github.com/andrewjfreyer/monitor#configuration-and-setup).

If that is possible, do I need to make any changes to the [monitor setup](https://github.com/andrewjfreyer/monitor#setup-monitor), and what?

**Comment by skynet01** [comment]
It will work, I am using the server that's running on my HA without any issues without changing anything in the setup instructions (other then the IP of the server)

**Comment by YogoGit** [comment]
It's simple, just edit the file mqtt_preferences and use your MQTT server information there.
```
#
#
# MOSQUITTO PREFERENCES
#
# ---------------------------

# IP ADDRESS OR HOSTNAME OF MQTT BROKER
mqtt_address=mqtt.mydomain.org

# MQTT BROKER USERNAME
mqtt_user='myuser'

# MQTT BROKER PASSWORD
mqtt_password='supersecret'

# MQTT PUBLISH TOPIC ROOT 
mqtt_topicpath=monitor
```

**Comment by pastaholic** [comment]
Thank you for your replies.
