### ISSUE TITLE
on newer installs libwebsockets18 does not work right

### ISSUE THREAD

**Issue by turboc1208** [andrewjfreyer/monitor#423]
work around is the following after you have done the mosquitto installation and it has failed in configuration

# apt remove mosquitto libwebsockets18
# apt install mosquitto libwebsockets18=4.2.1-0mosquitto1~buster1

https://forums.raspberrypi.com/viewtopic.php?t=334388

**Comment by labasu-helpme-ronda** [comment]
Thank you very much.  Spent a lot of time struggling on this part!!
