### ISSUE TITLE
All scan reports are not being reported with "-a" flag

### ISSUE THREAD

**Issue by x99percent** [andrewjfreyer/monitor#46]
Not sure when this option stopped working, but it definitely worked in an older version.

I've been using the script with the "-r -a -m" options.

**Comment by andrewjfreyer** [comment]
I can't verify this bug, @x99percent. Can you post a log?

**Comment by x99percent** [comment]
Maybe I'm misunderstanding how the -a flag should work? It used to behave as the documentation suggests... reporting the status of devices with every scan, even with no change in the status.

Now, it doesn't repeat itself anymore... for example, once I leave and confidence goes to zero, the script will not send another "zero" until I leave again.

Here is a log from the Mosquitto side, from the start of the monitor script, run with "-r -a -x":

`1540234529: New client connected from 192.168.1.202 as mosqsub|19919-Beacon2 (c1, k60, u'mosquitto').
1540234529: Sending CONNACK to mosqsub|19919-Beacon2 (0, 0)
1540234529: Received SUBSCRIBE from mosqsub|19919-Beacon2
1540234529: mosqsub|19919-Beacon2 0 location/scan/#
1540234529: Sending SUBACK to mosqsub|19919-Beacon2
1540234536: New client connected from 192.168.1.202 as mosqpub|20430-Beacon2 (c1, k60, u'mosquitto').
1540234536: Sending CONNACK to mosqpub|20430-Beacon2 (0, 0)
1540234536: Received PUBLISH from mosqpub|20430-Beacon2 (d0, q0, r1, m0, 'location/Beacon2/XX:XX:XX:XX:XX:XX', ... (227 bytes))
1540234536: Sending PUBLISH to Node-RED (d0, q0, r0, m0, 'location/Beacon2/XX:XX:XX:XX:XX:XX', ... (227 bytes))
1540234536: Received DISCONNECT from mosqpub|20430-Beacon2
1540234536: Client mosqpub|20430-Beacon2 disconnected.
1540234545: New client connected from 192.168.1.202 as mosqpub|20495-Beacon2 (c1, k60, u'mosquitto').
1540234545: Sending CONNACK to mosqpub|20495-Beacon2 (0, 0)
1540234545: Received PUBLISH from mosqpub|20495-Beacon2 (d0, q0, r1, m0, 'location/Beacon2/YY:YY:YY:YY:YY:YY', ... (211 bytes))
1540234545: Sending PUBLISH to Node-RED (d0, q0, r0, m0, 'location/Beacon2/YY:YY:YY:YY:YY:YY', ... (211 bytes))
1540234545: Received DISCONNECT from mosqpub|20495-Beacon2
1540234545: Client mosqpub|20495-Beacon2 disconnected.
1540234589: Received PINGREQ from mosqsub|19919-Beacon2
1540234589: Sending PINGRESP to mosqsub|19919-Beacon2
1540234649: Received PINGREQ from mosqsub|19919-Beacon2
1540234649: Sending PINGRESP to mosqsub|19919-Beacon2
1540234710: Received PINGREQ from mosqsub|19919-Beacon2
1540234710: Sending PINGRESP to mosqsub|19919-Beacon2
1540234769: Received PINGREQ from mosqsub|19919-Beacon2
1540234769: Sending PINGRESP to mosqsub|19919-Beacon2
1540234830: Received PINGREQ from mosqsub|19919-Beacon2
1540234830: Sending PINGRESP to mosqsub|19919-Beacon2
1540234889: Received PINGREQ from mosqsub|19919-Beacon2
1540234889: Sending PINGRESP to mosqsub|19919-Beacon2
1540234949: Received PINGREQ from mosqsub|19919-Beacon2
1540234949: Sending PINGRESP to mosqsub|19919-Beacon2
1540234985: Sending PUBLISH to mosqsub|19919-Beacon2 (d0, q0, r0, m0, 'location/scan/ARRIVE', ... (1 bytes))
1540234985: Sending PUBLISH to mosqsub|19919-Beacon2 (d0, q0, r0, m0, 'location/scan/ARRIVE', ... (1 bytes))
1540235009: Received PINGREQ from mosqsub|19919-Beacon2
1540235009: Sending PINGRESP to mosqsub|19919-Beacon2
1540235069: Received PINGREQ from mosqsub|19919-Beacon2
1540235069: Sending PINGRESP to mosqsub|19919-Beacon2
`

(multiple scheduled scans and a triggered scan happened during the pings, but no device status was reported again)

**Comment by andrewjfreyer** [comment]
It’s difficult to tell with the script is doing based on what your MQTT broker receives. Can you send logs from monitor output?

**Comment by x99percent** [comment]
I was trying to avoid sending a log directly from monitor.sh because of ALL of the MAC addresses that I'd have to edit/obscure.

I've reset the preferences file with `-d`, and only have 2 addresses in the `known_static_addresses` file. Still, when the `-a` flag is used, the confidence levels for each device are not reported with every scan. Are you seeing different behavior on your end?

**Comment by x99percent** [comment]
More experimentation is showing me that confidence levels of zero are not being repeated. Positive values are reported every time, as they should be, when the `-a` flag is used (e.g., 100% gets reported/repeated with every scan).

**Comment by andrewjfreyer** [comment]
Thanks for the update. I'll see if I can address this in an update. Note the -R flag which redacts mac addresses from logs for specifically this reason.

**Comment by andrewjfreyer** [comment]
Following up on this. Are you still noticing this behavior in recent versions of the beta?

**Comment by x99percent** [comment]
Yes, with the latest beta (0.1.713) a confidence of 0% from known devices is still not being reported.

**Comment by andrewjfreyer** [comment]
Try 0.1.714 and let me know if you're seeing more reports.

**Comment by x99percent** [comment]
It's working! Thank you for checking back on this.
