### ISSUE TITLE
iBeacon timestamp is truncated in MQTT message

### ISSUE THREAD

**Issue by jshank** [andrewjfreyer/monitor#53]
Using iBeacon scanning flag '-b' the timestamp is being truncated `"timestamp":"Tue Oct "

`location/first_floor/FDA50693-A4E2-4FB1-AFCF-C6EB07647825-10-7 {"id":"FDA50693-A4E2-4FB1-AFCF-C6EB07647825-10-7", "retained":"false", "version":"0.1.675", "confidence":"100","name":"Undiscoverable Device Name","timestamp":"Tue Oct ","type":"APPLE_IBEACON","rssi":"-83","rssi":"-83","power":"-59"}`

**Comment by andrewjfreyer** [comment]
As published to the broker? Or as logged on the monitor raspberry?

**Comment by jshank** [comment]
As published to the broker. This was from mqtt_sub on another device.

**Comment by jshank** [comment]
Disregard, seems to be something with the way screen is truncating the message
