### ISSUE TITLE
Invalid connection from (client @=x.x.x.x:XXXX) : [MQTT-3.1.2-1] Incorrect protocol name: "MQIsdp"

### ISSUE THREAD

**Issue by WhistleMaster** [andrewjfreyer/monitor#58]
I’m trying to use monitor.sh but I have the following error using Home Assistant MQTT server:

Invalid connection from (client @=x.x.x.x:XXXX) : [MQTT-3.1.2-1] Incorrect protocol name: "MQIsdp"

I found out that mosquitto_pub has to use the following option -V mqttv311.

Would it be possible to have an option in the configuration file to add some parameters ?

**Comment by andrewjfreyer** [comment]
I upgraded the mqtt service as well,  it I’m not seeing this. I’ll add an option regardless. Thanks!

**Comment by WhistleMaster** [comment]
Thanks for the message ! I'm using the embedded MQTT broker of Home Assistant called hbmqtt (version 0.9.4)  and the latest version of Home Assistant (version 0.81.6). 

The Pi running Monitor has mosquitto_pub and mosquitto_sub version 1.5.3 running on libmosquitto 1.5.3.

**Comment by andrewjfreyer** [comment]
New option in beta 0.1.713 and greater. Let me know if this works for you!
