### ISSUE TITLE
status topic message is retained when it is "online", but not for "offline" (LWT)

### ISSUE THREAD

**Issue by airdrummingfool** [andrewjfreyer/monitor#60]
Hello,
First off, thank you for this awesome project!

Any time I connect to my MQTT broker and subscribe to the status topic, I see a retained message with   a body of `online`.  I can manually clear it (by sending an empty, retained message to the status topic), but any time I restart monitor.sh the retained message comes back. It's worth noting that *any* "online" status message that monitor sends is retained, not just the one it sends upon launch.

The issue that I run into with this is that even though the "online" message is retained, the  LWT "offline" message is *not*. Therefore if HA (or anything else) loses its state, when it reconnects to the MQTT broker it receives an "online" status message from monitor, even if monitor is offline. I think ideally the `online` and `offline` status messages would *both* be retained - that way the status topic always has the most up-to-date status and delivers it to any new MQTT subscribers. Short of that, I think both the online and the offline message should respect the `-X` argument, or at least neither should be retained. Basically, as long as they match (either both are retained or neither are) things should work as expected.

I've never used the `-X` option to instruct monitor to set any messages to retain (so it is perhaps inconsistent that I'd prefer the status messages to be retained). I'm currently running version `0.1.711`, but I've seen this in older versions as well.

Thanks!

**Comment by andrewjfreyer** [comment]
Yes this is the current expected behavior in the beta. I’ve been trying to find a good way to get around the broker limitations of hassio causing some users to see “unknown” as a status for a monitor node.

**Comment by airdrummingfool** [comment]
Okay, I can see why you'd want to retain the status topic message (or broadcast it often, as I have also seen on the beta branch recently) so that users always have an updated availability status for their HA sensors.

However, if you're going to have the `online` message retained, shouldn't you also have the `offline` message retained? Otherwise the `online` message sticks around after monitor goes offline.

**Comment by andrewjfreyer** [comment]
I've addressed this in the newest beta. Per your (implied :-) ) suggestion, I've removed the retain flag for online messages regardless of the retain flag preferences established by the settings. This will still send the online message regularly (at every new mqtt report) to get around the "unavailable" error exhibited by Home Assistant. 

Beta 0.1.712

**Comment by airdrummingfool** [comment]
Awesome, and works great. Thank you!
