### ISSUE TITLE
Beta on Alpine/Docker/Busybox

### ISSUE THREAD

**Issue by kabturek** [andrewjfreyer/monitor#62]
Hey,
just tried the beta channel on Docker and Alpine linux uses Busybox that has a different version of timeout - it has different params - is uses:
 -s SIGINT instead of --signal SIGINT
 -t TIMEOUT instead of TIMEOUT

Here is a fix for a similar issue: https://github.com/vishnubob/wait-for-it/pull/6/commits/8f52a814ef0cc70820b87fbf888273f3aa7f5a9b

Alternatively i can build the Docker image on top of a different/bigger image.

**Comment by kabturek** [comment]
i've did a little comparison and switching to an ubuntu images produces ~6 times bigger image

```
# docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
monitor.sh-ubuntu              latest              be4e5fdb35d4        36 seconds ago      220MB
kabturek/monitor.sh            beta                9ab3679d5a91        17 hours ago        38.4MB
```

Not sure if it matters tho cause its still only 220mb

**Comment by andrewjfreyer** [comment]
This is a bit out of scope for this repo, so Ill close this issue. Thanks for the report of this use case.
