### ISSUE TITLE
RSSI value empty for known device?

### ISSUE THREAD

**Issue by devax** [andrewjfreyer/monitor#64]
Hi all,
First, thank you very much @andrewjfreyer for this very interesting project! Very impressive bash application you've came up with here!
I have set it up on a Orange Pi 2+ with a bluetooth dongle connected to it. It seemed to work nicely but I realized that RSSI values are empty in MQTT status messages for known devices. Here is a sample MQTT message that gets published:
<code>
{"id":"4c:49:e3:57:12:34", "retained":"false", "version":"0.1.675", "confidence":"100","name":"MobileDevax","timestamp":"Tue Nov 20 2018 21:22:17 GMT+0100 (CET)","manufacturer":"Xiaomi Communications Co Ltd","type":"KNOWN_MAC","rssi":""}
</code>
I though it might be related to my setup, so I ordered a PI Zero W just for this purpose. It arrived today, but it shows the same behavior. 

Is this intended behavior?
I would like to get a signal strength value, because I'd like to determine if the device is insede a specific room. Connection will be established before the device is inside the room, so I thought I could use RSSI to determine how close the device is to the monitor.

Am I missing something?

**Comment by andrewjfreyer** [comment]
No, You’re not missing anything. RSSI is not supplied by known_devices, unfortunately.

**Comment by devax** [comment]
Thank you @andrewjfreyer  for your answer! This is a pitty, makes it probably not reasonable for me to use. I'm looking for a way to determine how close a known bluetooth device (smart phone) is to the receiver.
