### ISSUE TITLE
Latest beta problems 0.1.745

### ISSUE THREAD

**Issue by gieljnssns** [andrewjfreyer/monitor#66]
The MQTT topic isn't JSON formatted 
```
Error parsing value: 'value_json' is undefined (value: {"id":"xxxxxxxxxxxx", "retained":"true", "version":"0.1.745", "confidence":"0","name":"gPhone","timestamp":"Sat Nov 24 2018 20:19:33 GMT+0100 (CET)","manufacturer":"Unknown","type":"KNOWN_MAC","}, template: {{ value_json.confidence }})
```
```
*** PAYLOAD IS NOT VALID JSON DATA *** 

Unexpected end-of-input: was expecting closing '"' for name
 at [Source: java.io.StringReader@7751f82c; line: 1, column: 401]
```
```
pi@PiZero-Garage:~/monitor $ sudo bash monitor.sh -x -tad -m -a -u
====================== DEBUG ======================
Updated monitor.sh (v. 0.1.732) -> (v. 0.1.745)...
> removing web request caches
> retaining mqtt status reports
> trigger mode: scan only (both on arrive and depart) on trigger
> send heartbeat signal
> report all scan results mode enabled
> updating monitor.service
> preference: using default mqtt protocol version
> monitor.service updated with arguments: -x -tad -m -a
> preference: delay between scans = 3
> preference: database refresh interval = 35
> preference: max arrival scan attempts = 2
> preference: max depart scan attempts = 4
> preference: random advertisement expiration = 45
> preference: rssi threshold for triggering arrival = -70
> preference: interval until beacon is considered expired = 145
> preference: trigger a departure scan at other nodes when below [x] confidence = 25
> preference: preferred HCI device = hci0
> preference: minimum time between the same type of scan = 15
> preference: mqtt scan start/end reporting = true
> mqtt trigger: monitor/scan/ARRIVE
> mqtt trigger: monitor/scan/DEPART
> stopping other instances of 'monitor.sh'
> known device: xxxxxxxxxxxx will publish to: monitor/Garage/xxxxxxxxxxxx
> known device: xxxxxxxxxxxx will publish to: monitor/Garage/xxxxxxxxxxxx
rm: cannot remove '.pids': No such file or directory
================== BEGIN LOGGING ==================
0.1.745 07:26:12 pm monitor/scan/arrival/start
0.1.745 07:26:12 pm [CMD-INFO]	**** Started arrival scan. [x2 max rep] ****
0.1.745 07:26:14 pm [CMD-SCAN]	(No. 1)xxxxxxxxxxxx arrival?
monitor.sh: line 361: disown: 2828: no such job
0.1.745 07:26:17 pm monitor/Garage/xxxxxxxxxxxx

0.1.745 08:32:18 pm [ENQ-DEP]	Enqueued depart scan triggered.
0.1.745 08:32:20 pm [CMD-SCAN]	(No. 1) 6C:E8:5C:C6:A8:10 arrival?
monitor.sh: line 698: perform_depart_scan: command not found

0.1.745 08:32:31 pm monitor/scan/arrival/end
error! attempting to correct hci0 hardware fault.
0.1.745 08:33:28 pm [INSTRUCT] mqtt trigger depart
```

**Comment by andrewjfreyer** [comment]
Thanks for the report! Fixed as far as I can tell. Please reopen if you're seeing the same behavior.

**Comment by cameronkelley28** [comment]
I had had fixed this for myself and then just saw your last commit was the same thing but I'm still having the issue every once in a while. Somehow it's occasionally appending the same extra `,"` when there is nothing to append.

I can't for the life of me figure out why since it's so sporadic, even on the same device being reported. The $append variable is empty when it happens so it makes no sense.

As a temporary workaround I added a check for the $append variable being empty and removed it from the payload if it is. So far all messages have been formatted properly since. Not an elegant solution but I have no idea how it was still getting appended.

`

        if [ ! -z $append ]; then
            $mosquitto_pub_path -I "$mqtt_publisher_identity" $should_retain $mqtt_version_append $mqtt_ca_file_append -h "$mqtt_address" -p "$mqtt_port" -u "$mqtt_user" -P "$mqtt_password" -t "$topic" -m "{\"id\":\"$(basename "$1")\", \"retained\":\"$retain_flag\", \"version\":\"$version\", \"confidence\":\"$2\",\"name\":\"$name\",\"timestamp\":\"$stamp\",\"manufacturer\":\"$4\",\"type\":\"$5\"$append}" 2>&1 
        else
            $mosquitto_pub_path -I "$mqtt_publisher_identity" $should_retain $mqtt_version_append $mqtt_ca_file_append -h "$mqtt_address" -p "$mqtt_port" -u "$mqtt_user" -P "$mqtt_password" -t "$topic" -m "{\"id\":\"$(basename "$1")\", \"retained\":\"$retain_flag\", \"version\":\"$version\", \"confidence\":\"$2\",\"name\":\"$name\",\"timestamp\":\"$stamp\",\"manufacturer\":\"$4\",\"type\":\"$5\"}" 2>&1 
        fi
`
