### ISSUE TITLE
Can't discriminate between floors

### ISSUE THREAD

**Issue by JerryWorkman** [andrewjfreyer/monitor#68]
I have two monitor nodes one on each floor. Both show 100% whenever my Galaxy 7 or my wife's Iphone 7 are home. I have separated the the nodes as far as possible from each other. How do I tell which floor each phone is on. 

I also see that rssi is not reported in the mqtt payload.

**Comment by andrewjfreyer** [comment]
Rssi is not reported for known_devices based on how the scans return data. Plus, the range for bluetooth for just scan responses is close to theoretical max distance. It'll be difficult to use monitor to distinguish between rooms within 300 ft of eachother.

**Comment by JerryWorkman** [comment]
How about wrapping the bluetooth with wire or a mesh to reduce it's signal.
