### ISSUE TITLE
iphone 7 strange behavior

### ISSUE THREAD

**Issue by cdkonecny** [andrewjfreyer/monitor#69]
I got everything installed and it is working wonderfully for my Android phone but something strange is occurring with my wife's iPhone 7.   It has been indicating a confidence of '0' all day with the exception of (one and only one) brief moment when I turned on her bluetooth it went to '100' and then it returned to '0' quickly.   I have not been able to recreate any reading above '0' since then.    

 Finally, I ran from command line with -g flag and things got more strange.  iPhone was still at confidence '0' but now some 'Undiscoverable Device Name' and 'Unresponsive Devices' began to get logged to the MQTT topic.   These devices were shown as GENERIC_BEACONS manufactured by Apple, had similar MAC addresses to each other, and had confidence of '100'.   

I then switched to the Beta version to see if that would resolve anything.   The iphone is still at '0' but the beacons did not return when run from the command line again.

I don't have a beacon of any kind in the house and I dont have any beacons set up in the configuration.   Could these be coming from the iphone?   Any ideas on how to go about resolving this?    What information would be helpful?

This is an incredible app and will be great for me once I can work out the kinks.
Thank you for all your hard work.

Chris

**Comment by andrewjfreyer** [comment]
Is your iPhone's address in the known_devices file?

**Comment by cdkonecny** [comment]
It is in the 'known_static_addresses' file and I have verified that it is correct

**Comment by cdkonecny** [comment]
Well, it turned out to be the most basic of things.   Maybe it's common 
knowledge (or maybe not since googling all day didn't reveal this) but I 
didn't know that the iPhone wouldn't advertise anything except when on the 
pairing screen unless at least one device was already paired with it.   
Once I paired a random speaker to it, it has consistent contact with monitor.

**Comment by gmalbert** [comment]
@cdkonecny when you say paired a speaker to it, do you mean that you paired a speaker to your iphone to allow consistent contact with monitor? Did you just disconnect the speaker and then no longer have issues or did it need to remain contacted?

**Comment by cdkonecny** [comment]
Just pair then disconnect but dont delete.  Leave it as a known device
