### ISSUE TITLE
Blacklist overwritten

### ISSUE THREAD

**Issue by roblandry** [andrewjfreyer/monitor#72]
https://github.com/andrewjfreyer/monitor/blob/1d838cd8ba0434308c2c21cb2d0ba8dff88f1e85/support/setup#L44

Using a docker container, with a configuration directory specified, blacklist is not useable.  The script always creates new blacklist on restart, over writing edits.

Working solution:
The script should look for file here: $base_directory/address_blacklist.

Recommend changing line 44 to:
```
[ ! -f "$base_directory/address_blacklist" ] && echo "#LIST MAC ADDRESSES TO IGNORE, ONE PER LINE:
```

**Comment by andrewjfreyer** [comment]
Incorporated suggestion into beta branch. Thanks!
