### ISSUE TITLE
reduce amount of loggin?

### ISSUE THREAD

**Issue by kuifje123** [andrewjfreyer/monitor#74]
Hi Andrew, could you advice how I could reduce the amount of logging?
I use your monitor service on a Raspberry PI and want to prevent writes to SD card as much as possible.
Thanks!

**Comment by kuifje123** [comment]
Or, how could I specify an alternative logfile (eg one on a tmpfs location)

**Comment by andrewjfreyer** [comment]
If you use the `-S` flag, logging is disabled.

**Comment by kuifje123** [comment]
Thanks!
