### ISSUE TITLE
setup own mqtt server now monitor will not publish messages to it

### ISSUE THREAD

**Issue by gbdavidx** [andrewjfreyer/monitor#75]
Things i've tried: ubuntu 18.04 mqtt-eclipse, setup per Bruh on youtube, https://www.youtube.com/watch?v=AsDHEDbyLfg

I can create custom messages just fine on the server using https://www.youtube.com/watch?v=AsDHEDbyLfg however monitor doesn't publish

I can successfully talk to my server by doing the following: 
david@server1:~$ mosquitto_sub -d -h localhost -u user -P password -t dev/test
monitor: pi@raspberrypi:~/monitor $ mosquitto_pub -d -h 192.168.1.226 -u user -P password -t dev/test -m "hello"
and on the server i get "hello" as expected, so mqtt is communicating fine, not the app

these are my mqtt settings 
```
# ---------------------------
#
# MOSQUITTO PREFERENCES
#
# ---------------------------

# IP ADDRESS OF MQTT BROKER
mqtt_address=192.168.1.226

# MQTT BROKER USERNAME (OR BLANK FOR NONE)
mqtt_user="user"

# MQTT BROKER PASSWORD (OR BLANK FOR NONE)
mqtt_password="password"

# MQTT PUBLISH TOPIC ROOT
mqtt_topicpath=monitor

# PUBLISHER IDENTITY
mqtt_publisher_identity='media_room'

# MQTT PORT
mqtt_port='1883'

```
mqtt.fx can on my mac can connect to my ubuntu server without any errors and can receive commands from the server, so i know the server is working the way it should, same with home assistant

i started a thread on home assistant that shows screenshots in detail in case others have the same issue https://community.home-assistant.io/t/why-cant-pi-w-monitor-talk-to-my-mqtt-hassio-addon/89500/15

i have rebooted after each time creating a "user" on ubuntu, here it shows mqtt message broke running on ubuntu 18.04
```
david@server1:~$ sudo systemctl status mosquitto
● mosquitto.service - LSB: mosquitto MQTT v3.1 message broker
   Loaded: loaded (/etc/init.d/mosquitto; generated)
   Active: active (exited) since Sun 2019-01-06 08:34:22 PST; 30min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 573 ExecStart=/etc/init.d/mosquitto start (code=exited, status=0/SUCCESS)

Jan 06 08:34:18 server1 systemd[1]: Starting LSB: mosquitto MQTT v3.1 message broker...
Jan 06 08:34:22 server1 mosquitto[573]:  * Starting network daemon: mosquitto
Jan 06 08:34:22 server1 mosquitto[573]:    ...done.
Jan 06 08:34:22 server1 systemd[1]: Started LSB: mosquitto MQTT v3.1 message broker.
```

**Comment by andrewjfreyer** [comment]
What logging output do you see from `monitor`?

**Comment by andrewjfreyer** [comment]
Closing this issue as unrelated to monitor. If you continue to experience issues, please reopen and post logging or configuration information from `monitor`
