### ISSUE TITLE
main_pipe is out of order

### ISSUE THREAD

**Issue by RomRider** [andrewjfreyer/monitor#77]
Hi,

Thanks for your great work!!

Using the `beta 0.1.814` here.

One quick thing that I saw is whenever you inject data to MQTT (let's say on the `arrive` or `depart` topic) the `main_pipe` gets wrecked (messages overlap, line ending are not at the right place, ...). 
The consequence of this is that the main loop doesn't do it's job anymore and does weird stuff instead :)

I replaced every `> main_pipe` with a MQTT publish to get this fixed on my side, but I understand it's not a solution for everyone.

```sh
mqtt_pipe_send() {
	$(which mosquitto_pub) -I "$mqtt_publisher_identity" $mqtt_version_append $mqtt_ca_file_append -h "$mqtt_address" -p "$mqtt_port" -u "$mqtt_user" -P "$mqtt_password" -t "$mqtt_topicpath/$mqtt_publisher_identity/pipe" -l
}

# Use with:
echo "DONE" | mqtt_pipe_send
```

Reading the pipe from MQTT:
```sh
while true; do

	#READ FROM THE MAIN PIPE
	while read -r event; do
        [...]
	done < <($(which mosquitto_sub) -I "$mqtt_publisher_identity" $mqtt_version_append $mqtt_ca_file_append -h "$mqtt_address" -p "$mqtt_port" -u "$mqtt_user" -P "$mqtt_password" -t "$mqtt_topicpath/$mqtt_publisher_identity/pipe" 2>&1)
	log "[ERROR]	mqtt broker went offline. attempting subscribe in 10 seconds."
	sleep 10
done
```

Any other idea ?

Cheers

**Comment by andrewjfreyer** [comment]
> One quick thing that I saw is whenever you inject data to MQTT (let's say on the arrive or depart topic) the main_pipe gets wrecked (messages overlap, line ending are not at the right place, ...).
The consequence of this is that the main loop doesn't do it's job anymore and does weird stuff instead :)

Can you elaborate on this point? What data are you seeing that's coming out of order or malformed? 

Your edit seems like it would spam the hell out of your poor broker...

**Comment by andrewjfreyer** [comment]
I cannot duplicate this bug, but just to be sure, I changed all `"echo ..." > pipe` calls to `printf` calls since echo may close the pipe prematurely. Let me know if you still see this behavior. 

Thanks for the report!
