### ISSUE TITLE
monitor scan errors: bash[8355]: rejecting scan 1 

### ISSUE THREAD

**Issue by kenthua** [andrewjfreyer/monitor#81]
I switched over to the beta branch and after a few hours this is all I see in my logs, repeating entries of:

`bash[8355]: rejecting scan 1 xx:xx:xx...`

Prior to switching I was on the master branch, mostly good except for an iPhone device detected as confidence 0 when the device was still in the area.

No additional switches:
`ExecStart=/bin/bash /home/pi/monitor/monitor.sh  &`

**Comment by andrewjfreyer** [comment]
Have you changed settings at all?

**Comment by kenthua** [comment]
No, default settings, aside from setting mqtt broker and known_static_addresses

**Comment by andrewjfreyer** [comment]
Ok. This is interesting. I'll see if I can duplicate this issue on my end.

**Comment by andrewjfreyer** [comment]
Ah! Just a log entry for debugging. Removed in a just-posed updated. This is a log entry related to RSSI scanning for previously-connected devices. Unreleased feature currently in testing. 

To test, you'll have to pair your phone to the pi. This can be done by `sudo bash monitor.sh monitor -c [mac address of your phone]` Then follow the prompts to connect your phone. 

After pairing, monitor will report RSSI of your phone every few minutes to the topic: `$mqtt_topicpath/$mqtt_publisher_identity/MACADDRESS/RSSI`

**Comment by kenthua** [comment]
Thanks for looking into it, though it's a log entry in the beta, this is a pretty much all I have towards the end of my logs.  I'm not seeing any activity being tracked or devices being scanned.  Essentially, even though I had left the house for like 7 hours, it never triggered me as away.

**Comment by andrewjfreyer** [comment]
Update the beta, the behavior should be fixed.
