### ISSUE TITLE
How to just scan for devices?

### ISSUE THREAD

**Issue by ScottChapman** [andrewjfreyer/monitor#82]
I am interested in something like what you have for the trigger logic, but even simpler.

I would like to have it simply scan for devices, report if it finds any, and then repeats.

This would enable me to aggregate the events and determine overall presence/absence.

Note: I am working on a similar integration but for SmartThings. There is an MQTT integration for SmartThings where you can publish "present" or "not present" to a topic associated with a virtual presence device. So it sounds a little different that what you did for Home Assistant, but maybe I can leverage some of this work.

**Comment by andrewjfreyer** [comment]
The scan operation is performed by `hcitool name [mac address]`

**Comment by andrewjfreyer** [comment]
No, that is the command that will work for *most* devices that can connect. The entire point of `monitor` is that there are dozens of ways different bluetooth devices are implemented. Some beacons report differently than other beacons. Some devices respond differently than other devices. 

For scanning with known devices, the command above will suffice. For listening for beacon advertisements, you need a much more involved method to listen to reports from `btmon` or `hcidump` while an `lescan` is active.

**Comment by ScottChapman** [comment]
Right, I think you did a lot of work to try to figure all that out. I was just hoping for a way to be able to leverage that more generalized scanning (just reporting on what is found).

**Comment by ScottChapman** [comment]
Yea, I did read it, but (obviously) got kinda lost.
I do only care about specific  devices that I know the hardware addresses of, so maybe it is sufficient to just put `hcitool name <addr>` in a reasonable loop then?

**Comment by andrewjfreyer** [comment]
Have a look at the `presence` project in my repo. That's doing exactly what you're suggesting here.

**Comment by ScottChapman** [comment]
yea, I was most intrigued by that. But it isn't quite what I need. Thought I might be able to use your work as a base (since I think you did a better job than I did).

My Approach was for each scanner to post to an MQTT topic the devices is sees. Then there would be a client that would listen to that topic, and if it hasn't seen an ID in a specific period of time it would assume it was "not_present".

Thanks, I appreciate your help. I'll continue with what I have...

**Comment by nodecentral** [comment]
Hi @ScottChapman - just wondering how you got on with a setup/process that would scan and post EVERY bluetooth device it sees ?

**Comment by ScottChapman** [comment]
I actually think I ended up going a different route and using more specific commandline tooling to this...

Otherwise I would have done a PR

**Comment by nodecentral** [comment]
Would you be able to share details on what that command line tooling was/is ? I’m keen to find something that captures everything in range and regularly reports it via MQTR

Also , what is a PR ?
