### ISSUE TITLE
Only depart/arrival scan

### ISSUE THREAD

**Issue by mssmison** [andrewjfreyer/monitor#85]
I've probably missed it in the documentation but is there a way to configure the scanning to occur only when i post a depart or arrival request from a door opening?

**Comment by krambriw** [comment]
I use the -ta and -td directives like ./monitor.sh -ta -td -m
It works fine for me. I publish the scanning requests to the mqtt topics as described in the documentation

**Comment by andrewjfreyer** [comment]
@krambriw  hit the nail on the head.
