### ISSUE TITLE
monitor.sh Offline

### ISSUE THREAD

**Issue by sidhuneilkamal** [andrewjfreyer/monitor#88]
using a RPi Zero W - after about an hour or 2 the script stops and the and status says offline - at that point i would have to restart the service to get it back online.

**Comment by andrewjfreyer** [comment]
What version?

**Comment by andrewjfreyer** [comment]
I ask because the beta addresses many issues with buffer overruns that caused hangups. I'd guess that you were in a very noisy bluetooth environment?

**Comment by sidhuneilkamal** [comment]
Sorry, also I notice on beta that was not happening on prod - it is taking
long for monitor.sh to see me as away. I turn off my BT and it takes around
8 to 10 mins to show away. It sticks at 100. I have 2 pis. 1st is main
floor with no params. And 2nd is on 2nd floor with - tad is this normal
behaviour? On prod the away and home was fast!

**Comment by andrewjfreyer** [comment]
With `-tad`, a departure will *only* be recognized in response to a depart trigger. In addition, if your first pi does not include at least `-tr`, it won't report to the other pi to begin scanning for a departure. 

What are you using for your mqtt depart trigger?

**Comment by sidhuneilkamal** [comment]
Sorry so. Pi on main floor I tried setting to - tr and 2nd floor pi is set
to - tad. I currently have no triggers. Is this the way it should work?
What I am looking for is for my main pi to do all the work on its own no
triggers and the 2nd pi to only scan when the first Pi starts a arrival and
depart

**Comment by sidhuneilkamal** [comment]
i notice with using -tr on main pi and -tad on second pi that after sometime where there are no departs and arrives - the second pi (-tad) will go offline and once there is a depart or arrive detected on the first pi - the second pi will then go online.  Is this normal? Kind of like a sleep function?

Also; with pi1 and pi2 both are at 100 lets say and when i depart - pi1 starts going down 90, 45, 0 and once it reaches 0 - that is when pi2 will start its count down.  Does pi1 only sent the depart message to the other node once it reaches 0? can this be changed so it sends the signal at lets say 50?

Thank you!!

**Comment by andrewjfreyer** [comment]
Yes, there's a setting in the behavior preferneces named `PREF_COOPERATIVE_SCAN_THRESHOLD` that defaults to 60%. 

Your behavior does not seem normal for beta, no. You may see this behavior on master, due to some bugs that have been addressed in beta. Are you running any other options besides `-tr` and `-tdr`?

**Comment by sidhuneilkamal** [comment]
For my pi1 i am running -tr version: 0.1.925 and pi2 i am running -tad version: 0.1.925. 
- pi2 goes offline if there is no scans after about 5 mins.  Then as soon as pi1 gets a new scan arrive or depart, pi2 comes online and does a scan as well.

**Comment by andrewjfreyer** [comment]
There is a hanging bug in this or a version close to it. I'd update again. We're currently on version 947

**Comment by sidhuneilkamal** [comment]
ok will update now

**Comment by sidhuneilkamal** [comment]
performed update on both pi's (0.1.948) - rebooted and set pi with -tr and pi2 -tad 
- tested with phone went away and home no issues.  left BT on for a bit and noticed both pi's go offline.
- i then turned my BT off and noticed both pi status go online and showed me as away.
Is this normal?

**Comment by andrewjfreyer** [comment]
This may be an issue with homeassistant then. When you say "go offline" what do you mean?

**Comment by sidhuneilkamal** [comment]
i am monitoring the   state_topic: 'monitor/pimain/status'

- platform: mqtt
  state_topic: 'monitor/pimain/status'
  name: 'rPi Main Status'

**Comment by sidhuneilkamal** [comment]
the status shows offline and then my device in HA shows unknown

**Comment by andrewjfreyer** [comment]
Hmm.  There’s no reason that it should be reporting it off-line message.  I’ll investigate

**Comment by sidhuneilkamal** [comment]
Thank you!

**Comment by sidhuneilkamal** [comment]
just blew out my setup and pulled most updated clone set checkout to beta and my behavior file looks like this:

# ---------------------------
#
# BEHAVIOR PREFERENCES
#
# ---------------------------

#MAX RETRY ATTEMPTS FOR ARRIVAL
PREF_ARRIVAL_SCAN_ATTEMPTS=1

#MAX RETRY ATTEMPTS FOR DEPART
PREF_DEPART_SCAN_ATTEMPTS=2

#SECONDS UNTIL A BEACON IS CONSIDERED EXPIRED
PREF_BEACON_EXPIRATION=180

#MINIMUM TIME BEWTEEN THE SAME TYPE OF SCAN (ARRIVE SCAN, DEPART SCAN)
PREF_MINIMUM_TIME_BETWEEN_SCANS=15

#ARRIVE TRIGGER FILTER(S)
PREF_PASS_FILTER_ADV_FLAGS_ARRIVE="0x1a"
PREF_PASS_FILTER_MANUFACTURER_ARRIVE="Apple"

#ARRIVE TRIGGER NEGATIVE FILTER(S)
PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE="NONE"
PREF_FAIL_FILTER_MANUFACTURER_ARRIVE="Google|Samsung"
---
Seems shorter and missing items - is this normal?

**Comment by andrewjfreyer** [comment]
Interesting - have you moved the preferences file? I'd restore to default configuration first

**Comment by sidhuneilkamal** [comment]
if i press y to restore then i am only left with the 5 settings - is that how beta should be?

**Comment by sidhuneilkamal** [comment]
i just press y and now the file looks like this
`# ---------------------------
#
# BEHAVIOR PREFERENCES
#
# ---------------------------

#MAX RETRY ATTEMPTS FOR ARRIVAL
PREF_ARRIVAL_SCAN_ATTEMPTS=1

#MAX RETRY ATTEMPTS FOR DEPART
PREF_DEPART_SCAN_ATTEMPTS=2

#SECONDS UNTIL A BEACON IS CONSIDERED EXPIRED
PREF_BEACON_EXPIRATION=180

#MINIMUM TIME BEWTEEN THE SAME TYPE OF SCAN (ARRIVE SCAN, DEPART SCAN)
PREF_MINIMUM_TIME_BETWEEN_SCANS=15

#ARRIVE TRIGGER FILTER(S)
PREF_PASS_FILTER_ADV_FLAGS_ARRIVE="0x1a"
PREF_PASS_FILTER_MANUFACTURER_ARRIVE="Apple"

#ARRIVE TRIGGER NEGATIVE FILTER(S)
PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE="NONE"
PREF_FAIL_FILTER_MANUFACTURER_ARRIVE="Google|Samsung"`

**Comment by sidhuneilkamal** [comment]
i loose options like
#COOPERATIVE DEPARTURE SCAN TRIGGER THRESHOLD

-- also PREF_MINIMUM_TIME_BETWEEN_SCANS=15 (in seconds or mins)
sorry and thank you!

**Comment by andrewjfreyer** [comment]
You can still use all of these options, I have just removed them from the default preferences file for simplicity for a new user

**Comment by sidhuneilkamal** [comment]
ahh ok.. and i am using -tr on 1st pie but i notice the arrive scans not pick up quick.  I have no triggers but how long should a arrive process in the -tr? what are the best behave prefs?

**Comment by andrewjfreyer** [comment]
It’s easiest to see what’s going on by running by the command line. Try that to see what’s happening.

**Comment by andrewjfreyer** [comment]
Please report back with logs. Closing for now.
