### ISSUE TITLE
Apple Watch Confidence stay 0

### ISSUE THREAD

**Issue by ekkesa** [andrewjfreyer/monitor#9]
Hi,

I added monitor, and it is running publishing to my mqtt broker. The iphones seems to work 100%, but out Apple watches stays on a confidence of 0.

{
  "retained": "false",
  "version": "0.1.482",
  "confidence": "0",
  "name": "ekke's iWatch ",
  "timestamp": "Wed Aug 29 2018 20:09:23 GMT+0200 (SAST)",
  "manufacturer": "Apple, Inc.",
  "type": "Known Static MAC"
}

Any suggestions?

**Comment by andrewjfreyer** [comment]
Please update and report back. My watch has been consistent as of recent updates.

**Comment by gmalbert** [comment]
I'm using an Apple Watch 5 and having the identical issue above. Do you want me to open a new issue or re-open this?


`{"id":"XXXXXXX","confidence":"0","name":"Undeterminable","manufacturer":"Apple Inc","type":"KNOWN_MAC","retained":"false","timestamp":"Tue Jan 07 2020 20:59:08 GMT-0500 (EST)","version":"0.2.197"}`

**Comment by Breakerz** [comment]
Somes device (like my fitbit watch) don’t broadcast his MAC once is paired. If Iturn off the Bluetooth of my phone, my watch begin to broadcast to try to reconnect to my phone. I don’t think we can do something.

**Comment by Breakerz** [comment]
Try to pair your watch with headphones or something...

**Comment by gmalbert** [comment]
@Breakerz that worked, thank you! Is this something that can be added to the documentation?

**Comment by andrewjfreyer** [comment]
The strategy of connecting devices to bluetooth if they're not recognized is in the FAQ.
