### ISSUE TITLE
Run under hass.io on Pi3?

### ISSUE THREAD

**Issue by michaelblight** [andrewjfreyer/monitor#90]
A question not an issue. I've got this running on two Pi Zeroes, but would like to run it on my Pi3B+ which has hass.io installed (Alpine Linux). When I first run it I get an error about `bluez-hcidump`, but was able to fix this by installing `bluez-deprecated`. However when I run it, none of the known devices are found.

**Comment by andrewjfreyer** [comment]
Honestly, I'm not sure whether the bluetooth binaries required by `monitor` are available on ResinOS, and it's a bit beyond the scope of the project to investigate individual installations or configurations. Please reopen the issue if you receive an answer from someone more familiar than me

**Comment by michaelblight** [comment]
For anyone else trying it that knows more than me, I have been able to cobble it together.

The first thing I had to do was remove the `bluetooth_tracker` from the HA config to avoid conflicts.

I'm using the "SSH & Web Terminal" hass.io add-on, and updated its config to have:
```
"packages": [
    "openrc",
    "bluez-deprecated",
    "bc"
  ]
```
I tried including `monitor.sh` in its "init_commands", but that didn't work. If I kick it off manually it works fine, so I'm assuming I can just have an HA or Node Red script run it.

I installed the `openrc` package so I could have `monitor` run and restart automatically, but I haven't got there yet. First I'll let it run for a while to see how it goes.

**Comment by andrewjfreyer** [comment]
Thanks for the follow up!

**Comment by michaelblight** [comment]
I updated to the latest version and the Pi Zero's were okay, but the Pi 3 stopped working. No errors, it just did nothing after the initialisation messages. And it didn't seem to respond to MQTT scan requests. I reset back to 6ae4bd0 (not sure what I was actually on), and it started working again. So something between 6ae4bd0 and today breaks it working under Docker and/or Pi3 and/or some other non-Zero environment.
