### ISSUE TITLE
Monitor stopped 

### ISSUE THREAD

**Issue by sidhuneilkamal** [andrewjfreyer/monitor#96]
Hello; wondering what logs I can provide that will help aid in identifying my PI's scripts crashing. My 2nd pi crashed at around noon and now my first Pi script crashed. I am running the most recent master build with - tr and - tad. Thanks.

**Comment by sidhuneilkamal** [comment]
When I say offline. It's when I check 'monitor/pimain/status' it shows offline. And the funny thing is when I get home, it shows me as home and the status from 'monitor/pimain/status' changes back to online. Not sure why it goes offline like that. Even though it will still detect me when I get home.

**Comment by andrewjfreyer** [comment]
What version are you running? 0.1.625 may periodically crash due to errors that have been corrected in recent versions.

**Comment by sidhuneilkamal** [comment]
I am on the new 0.1957 version that was just promoted.

**Comment by andrewjfreyer** [comment]
We're on version 0.1.970 right now - be sure to update. Note that the "status" item has been unreliable when received from HomeAssistant. Many users have reported this on the forum.

**Comment by andrewjfreyer** [comment]
I've been running the current version for 15 minutes or so subscribing to the status topic, and I have not seen a single offline message. Have you retained messages?

**Comment by sidhuneilkamal** [comment]
I just took the latest master after it was posted yesterday. I have the monitor topic being watch in HA just as a tool to see if any of the pies script crashes. It can indicate online for a day even and then all a sudden show offline. And it will remain offline until a known device gets home and a arrive or depart message is public. That is when it will go back online.

**Comment by andrewjfreyer** [comment]
That's my point from above - this is an HA issue, not a monitor issue as reported by a number of users in the HA forum. 

By virtue of the fact that `monitor` detects a device when it appears in HA to be offline shows that this is an HA issue and that the script has not crashed. 

I'd suggest ignoring the HA availability topics until it's fixed. Please reopen with monitor logs if the script itself crashes.
