### ISSUE TITLE
A few troubles with monitor

### ISSUE THREAD

**Issue by jcastro** [andrewjfreyer/monitor#99]
**Monitor config**
Version 0.1.973

**Known static addresses**
I have 2 Apple Watch and 1 iPhone. Also this iPhone is paired with monitor so I can get the RSSI value.

**MQTT Preferences**
Publisher and topic are both monitor, so my full path will be “monitor/monitor/MAC”

**Behaviour preferences**
I got 1 attempt for arrival scan
I got 3 attempt for departure scan
Time between scans 20
Manufacturer filter “Apple”

**Hassio config**
I’m using Mosquitto Add-on. Previously I used the built-in MQTT broker on Hassio but I was getting some errors that while it doesn’t seem like interfering with the monitor I wanted to make sure it wasn’t because of this.

**Troubles I’m finding**
- Restarting monitor sometimes sets my phone or watch at 0 confidence and then goes back to 100 when it scans. Shouldn't the script check the state first or scan before setting it to 0 confidence as soon as you restart it?. It's interesting because sometimes it won't happen.

-  My phone averages around -22 dBm at my bedroom when I'm sleeping (value taken from Hassio RSSI raw sensor) but a few times at night it seems to drop to -99 together with confidence to 0. Check image below.
![Confidence on iPhone](https://user-images.githubusercontent.com/190036/52407952-f21c8e80-2ad1-11e9-9d79-dcfc827aa9ca.png)

- My Apple Watch confidence seemed a bit better tho, but they're in exactly same position on my bedroom.
![Confidence on Apple Watch](https://user-images.githubusercontent.com/190036/52407979-06f92200-2ad2-11e9-82e0-ff7457ced925.png)

- The other Apple Watch which is my GF's one is on the other side of the bed but look how much it moved the confidence during the night
![screenshot 2019-02-07 at 12 30 17](https://user-images.githubusercontent.com/190036/52408864-27c27700-2ad4-11e9-975f-3e3f6101c9ef.png)

I was thinking about using the PREF_RSSI_IGNORE_BELOW variable and set it into a lower value like -85 or -90 but looking at the graphs probably won't work. Any ideas if my troubles are configuration problem or some kind of bug? Maybe it's just my iPhone stop reporting at some point?.

Thanks a lot for this amazing tool Andrew!.

**Comment by andrewjfreyer** [comment]
PREF_RSSI_IGNORE_BELOW is unrelated at this point to RSSI scans on connection. Also, if a device departs (i.e., a depart scan concludes that there is a 0% confidence of "presence"), then all RSSI from connections are set to -99 by default. 

I would suggest setting to trigger on depart only to filter out this kind of confidence noise. I have set my depart to trigger when my door closes or when my garage opens. This will eliminate this noise. 

Alternatively, you can increase the random device expiration and continue to increase the number of depart scan repetitions. 

Please reopen if none of these techniques reduce your noise.

**Comment by jcastro** [comment]
Thanks for the reply @andrewjfreyer! I will try to implement your suggestions.

I'm also assuming the first point on my report is not a bug then, just normal behaviour of the script

**Comment by andrewjfreyer** [comment]
Yes, that is normal behavior. This is because `monitor` is, essentially, a state machine. If it restarts, best practice - in my opinion - is not to presume a positive presence state. 

That said, I'm sure I could come up with a solution to meet in the middle. I think on it. 

Thanks!

**Comment by jcastro** [comment]
What I thought the script was doing is to ask the MQTT broker the last state and use that as a initial reference, but maybe that has even more negative consequences!
Thanks a lot 🙏

**Comment by jcastro** [comment]
Btw not completely related to this report but I'm trying to implement your suggestions about triggering depart and arrival using a contact sensor but I'm unable to make it work.

Now I'm actually trying with a MQTT client instead of relying on the Hassio automation but still not working.

I have executed monitor as follows on my pi:
`sudo bash monitor.sh -tad`

And I'm publishing empty message to
`monitor/monitor/scan/depart`
![screenshot 2019-02-07 at 21 41 32](https://user-images.githubusercontent.com/190036/52441572-49961b00-2b21-11e9-97fd-a954e9a0a6c0.png)

However looking at the console log monitor is not triggering any scan.

**Comment by jcastro** [comment]
More digging into the help using `monitor --help` I'm seeing:
`a $mqtt_topicpath/scan/ARRIVE (defined in MQTT preferences file)
  d $mqtt_topicpath/scan/DEPART (defined in MQTT preferences file)`

So I've tried publishing to
`monitor/scan/DEPART` but no luck either

Also maybe it's a bit confusing that on the readme uses lower case 'depart' and on the help uses caps 'DEPART'. I read MQTT can differentiate between that but not entirely sure

**Comment by andrewjfreyer** [comment]
The capitalization doesn't matter for these, but your second guess is correct - there should only be on "monitor", presuming of course that you have named your mqtt publisher identity also as "monitor" 

Run monitor from the command line to make sure that you're connecting to your broker just fine.

**Comment by jcastro** [comment]
Yes I’m running it from command line, and I’m also getting the RSSI messages everything should be connected fine and working. I’m also connected my phone and I’m receiving the messages from I’m publishing from my Mac and the ones published from the monitor.

**Comment by jcastro** [comment]
I've tried with 0.1.985 but still I'm unable to trigger the depart or arrive scans, even if I'm seeing it's been published in the MQTT broker. Is there any way I could debug what's going on or why monitor is not trigger those scans? Thanks!

**Comment by andrewjfreyer** [comment]
can you post your mqtt pref file here? please redact address, username, and password.

**Comment by jcastro** [comment]
Absolutely! 

`# ---------------------------
#
# MOSQUITTO PREFERENCES
#
# ---------------------------

# IP ADDRESS OR HOSTNAME OF MQTT BROKER
mqtt_address=10.0.1.30

# MQTT BROKER USERNAME (OR BLANK FOR NONE)
mqtt_user=REDACTED

# MQTT BROKER PASSWORD (OR BLANK FOR NONE)
mqtt_password=REDACTED

# MQTT PUBLISH TOPIC ROOT
mqtt_topicpath=monitor

# PUBLISHER IDENTITY
mqtt_publisher_identity='monitor'

# MQTT PORT
mqtt_port='1883'

# MQTT CERTIFICATE FILE (LEAVE BLANK IF NONE)
mqtt_certificate_path=''

#MQTT VERSION (LEAVE BLANK FOR DEFAULT; EXAMPLE: 'mqttv311')
mqtt_version=''`

Thanks!

**Comment by jcastro** [comment]
Just a quick update, wanted to test the new version just in case but it seems I'm getting same result!
Thanks!
